### ISSUE TITLE
[BUG] Excessive RAM memory usage during export and user case crashes

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1002]
### --Issue Summary--
Various users have been complaining on recent issues with long-er animation projects that are failing to be rendered. 

I investigated and found that Pencil2D eats your RAM memory (at least on windows) when trying to render export video or image sequences for a specific file that had over 800 frames but with a resolution that was close to 4K.

When exporting I noticed that it was using all my RAM (8GB) just to try and export and it crashed. What I had to do was to export as Image Sequence, and even then It required a really long time and it used all my RAM (again) to export the file.

The problem is that I noticed later that the file didn't have a lot of movement, but rather that every drawing was keyframed even if there wasn't change.

Even though rendering heavy animation projects does indeed take time and computer resources, Pencil2D should have a better way to handle the RAM usage. I made a proposal here to consider a few concepts from other programs #965 

### --Expected Results--
Rendering videos or image sequences should not use all the available RAM while rendering, unless specified by the user.

### --Image Reference--
![image](https://user-images.githubusercontent.com/4912907/41791869-a8c76ed6-761c-11e8-8251-61765f937d72.png)
_This export test crashed silently so I couldn't get Windows crash report data even from the system log_

### --Steps to reproduce--
([Download the follwing project file to test this issue](https://drive.google.com/open?id=1uc71WKqdk4bYxkPGRal8xAuIENXa1VOL))

Movie Export Test
1) Open the provided file in Pencil2D
2) File > Export > Movie
3) Wait at least for the file to hit 10% of overall export progress and check your memory usage. In my case it was almost half my total RAM capacity.
4) If you want try to let it end and see if it crashes for you.

Image Sequence Export Test
1) Open the provided file in Pencil2D
2) File > Export > Image Sequence
3) Wait at least for the file to hit 10% of overall export progress and check your memory usage. In my case it was almost half my total RAM capacity.
4) If you want try to let it end and see if it crashes for you. I my case it didn't crash, and finished overnight, but it did use all of my computer resources.

### --System Information--
+ Pencil2D Version:
Version: 0.6.1.1
commit: 52db352d2bc25e650448f5b0e9c92aba14e11a64
date: 2018-06-16_11:45:26
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
**Workaround**
For users encountering this issue, there is not much you can do to reduce the memory usage during export other than reducing the size of your project (resolution and/or number of frames). If you can tolerate a temporary spike in memory usage, you can return Pencil2D to normal by doing either of these things:
- Quitting the application (after saving if necessary), and then reopening your project
- Playing through your entire animation once. You can temporarily increase the fps if you want this to go faster.

<hr>

**Technical Details**
The problem, or at least a large part of it, appears to be the fact that the movie exporter does not use the caching system which is designed to discard old frames to make room for new ones, but instead just loads all of the frames without discarding any of them.

In order to fix this, we need to load the frames with ActiveFramePool when rendering for export. Unfortunately, the rendering is done in MovieExporter, Object, LayerBitmap, and BitmapImage, none of which as far as I can tell have an easy way to access the ActiveFramePool instance which is currently a private member of Editor. I have personally suggested that the ActiveFramePool instance be made a static member of BitmapImage. I think this design is better in line with the idea of encapsulation, with the images handling their own caching. Static functions can be used to access it in other classes when necessary. Only images with a non-empty filePath would be cached to prevent temporary images (such as the onion skinning) from being cached. If this isn't good enough to prevent temporary images from being cached, then a flag can be used.

Alternatives to this approach include making a second ActiveFramePool, or adding a mEditor (or some other way to access the editor) to one of the previously mentioned rendering classes. The former could double memory usage during exporting, and the latter would add an unnecessary relation between otherwise separate classes.

I have brought this up in the general-development channel of Discord, but no conclusion was reached. I'm not in any rush though because I don't have the time to implement it at the moment.

**Comment by chchwy** [comment]
Fixed in Nightly 4 Aug 2018
