### ISSUE TITLE
My File Won't Save or Open

### ISSUE THREAD

**Issue by AsthenticCartoona** [pencil2d/pencil#1014]
I tried to save my project and a "Internal Error" message pops up. I tried to open the file in another tab but is says it can't read the file.

**Comment by Jose-Moreno** [comment]
@AsthenticCartoona Please download the latest development version to see if you still can't save or load a project. 

However if you used a relatively old Pencil2D version chances are the projects you are trying to load have been corrupted beyond salvaging. There's also a save bug which has been bothering windows users and apparently has been fixed recently, so please try out the latest "nightly build" here:
http://pencil2d.org/download#nightlybuild

If you want us to take a look at the file you're trying to load please upload it to a file sharing service you trust and drop the link on a comment.

Other than these suggestions without further information we can't do much and developers can't investigate it further, that's why there's a template to guide you for the description, so at least let us know the following:

1) What is your current version of Pencil2D (go to menu HELP > ABOUT)
2) What is your current OS (windows, mac, linux, etc)
3) What did you do when each issue happened, and what kind of error appeared (try to take a screenshot if possible)

**Comment by Jose-Moreno** [comment]
@AsthenticCartoona Please copy and paste the full error text that appears in that window and also try to upload the project file you are trying to laod to a file sharing site like dropbox, google drive, mega.nz, zippyshare, etc and then link the download address here. I'll tag developer @chchwy so they can review the error, the file and see how to help out with this.

**Comment by AsthenticCartoona** [comment]
Raw file path: C:/Users/Nicole/Animation, yEET/ghostsmeme.pclx
Resolved file path: C:/Users/Nicole/Animation, yEET/ghostsmeme.pclx
  File name: C:/Users/Nicole/Animation, yEET/ghostsmeme.pclx
  Is old format: false
  Recognized New zipped Pencil File Format (*.pclx) !
  XML file: C:/Users/Nicole/AppData/Local/Temp/Pencil2D/ghostsmeme.Y2xD/main.xml
  Data folder: C:/Users/Nicole/AppData/Local/Temp/Pencil2D/ghostsmeme.Y2xD/data
  Working folder: C:/Users/Nicole/AppData/Local/Temp/Pencil2D/ghostsmeme.Y2xD/
  Main XML file does not exist
System Info
Pencil version: 0.6.1.1 (dev)
Build ABI: x86_64-little_endian-llp64
Kernel: winnt, 6.3.9600
Operating System: Windows 8.1 (6.3)
end

https://www.dropbox.com/s/xkmiuc8l7n6e3ny/ghostsmeme.pclx?dl=0

**Comment by Jose-Moreno** [comment]
@AsthenticCartoona Thank you for the report, I tried to recover the drawings in the file using the method described in the following comment on the Pencil2D forum, if this ever happens to you again let us know and use that method to recover some of your previous work:

https://discuss.pencil2d.org/t/i-cant-open-the-animation-file/2700/2

For now, you can download a PCLX file I reconstructed with the drawings that were on the file. You might have to move the drawings to match their previous position as I only imported each image as a sequence, but at least you only have to do that instead of redrawing.

https://drive.google.com/open?id=1zsf4NGy6pzJJvvwm8Msu-IslsDUZSXq8

**Comment by AsthenticCartoona** [comment]
@Jose-Moreno I downloaded the file and opened it up and there's only 5 frames. The original animation had frames 99-471

**Comment by Jose-Moreno** [comment]
@AsthenticCartoona I'm really sorry to hear that, it was what the file had inside. I did find it strange that the images reference frames above 400+. :slightly_frowning_face: 

I honestly wish there was another way to help you but as far as  I know there isn't a way to recover those files because the temporary files that are created during a work session become deleted after the program is closed. 

I personally work in animation and I know the pain of losing your work over any manner of ill-fated events like blackouts, software misbehaving, bad colleagues and many more. My only real advice would be to never, ever depend on a single project file to host your work; make several copies per work session. For example I work with After Effects (a commercial product) for my day job and at the end of a single project I can have over 200 backup copies that comprise most work sessions from beginning to end of the project. That is because, unsurprisingly, even commercial software fails, and it hurts more when you paid for it expecting it not to lol.

Anyway, developers of Pencil2D are working hard to improve those kind of problems, but in the end we as users will always have to be extra careful because software is made by humans, and humans make mistakes too.

Hopefully you can try again and make up for most of your work, even if it isn't done with Pencil2D, and that would be totally understandable, but no matter what app you use next please don't forget to make extra copies of your work :slightly_smiling_face:

**Comment by ilikememes123** [comment]
i don't know what to do, i get this error when i try to save
FileManager::save
sFileName = C:/Users/gamers4life/Downloads/boss fite meh.pclx
New zipped Pencil File Format (*.pclx) !
TempWorkingFolder = C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/
Total 3 layers
Layer[0] = [id=1, name=Camera Layer, type=5]
Layer[1] = [id=2, name=Vector Layer, type=2]
Layer[2] = [id=3, name=Bitmap Layer, type=1]
  Layer::save
    LayerBitmap::saveKeyFrame
      KeyFrame.pos() = 5
      strFilePath = C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/data/003.005.png
    BitmapImage could not be saved
  - Keyframe[5] failed to save
    LayerBitmap::saveKeyFrame
      KeyFrame.pos() = 4
      strFilePath = C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/data/003.004.png
    BitmapImage could not be saved
  - Keyframe[4] failed to save
    LayerBitmap::saveKeyFrame
      KeyFrame.pos() = 3
      strFilePath = C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/data/003.003.png
    BitmapImage could not be saved
  - Keyframe[3] failed to save
    LayerBitmap::saveKeyFrame
      KeyFrame.pos() = 2
      strFilePath = C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/data/003.002.png
    BitmapImage could not be saved
  - Keyframe[2] failed to save
    LayerBitmap::saveKeyFrame
      KeyFrame.pos() = 1
      strFilePath = C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/data/003.001.png
    BitmapImage could not be saved
  - Keyframe[1] failed to save
  !! Failed to save Layer[2] Bitmap Layer
All Layers saved
Failed to save the palette xml
Writing main xml file...
Done writing main xml file at
C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/main.xml
Miniz
  Creating Zip C:/Users/gamers4life/Downloads/boss fite meh.pclx from folder C:/Users/gamers4life/AppData/Local/Temp/Pencil2D/Default_Y2xD_ol5lklfx/
  Add file to zip: data/002.002.vec
  Add file to zip: data/002.001.vec
  Add file to zip: main.xml
  Miniz finalize archive failed
System Info
Pencil version: 0.6.4 (stable)
Build ABI: x86_64-little_endian-llp64
Kernel: winnt, 10.0.17134
Operating System: Windows 10 (10.0)
end

**Comment by Jose-Moreno** [comment]
@ilikememes123 Hi, Thanks for sharing your report. Next time if possible please create a new ticket instead of commenting a closed one, otherwise it is really hard for developers to get alerted on new issues like yours :disappointed: 

While I've asked them to take a look when they are available, if you can't save your work right now, try to export sequence of images (preferably PNG so you preserve transparency) for each layer you have. With this your work will be preserved at least and later you'll be able to import back those image sequences into a new file or a previous version of your current file so you can keep working (and you'll have a hard copy of your work in case the file gets corrupted again).

It is important that you keep several backup copies around because Windows10 has been acting up on Pencil2D.

While we investigate this, if you can please zip the pencil2d file that caused the issue and uplaod it here. You can attach the file by dragging & dropping it.
