### ISSUE TITLE
Selected color in Color Palette 

### ISSUE THREAD

**Issue by jcome** [pencil2d/pencil#1024]
### --Issue Summary--
In Color Palette, selected color patch is overlapped with highlighting color causes not accurate of color shade

### --Actual Results--
<img width="345" alt="p2d1" src="https://user-images.githubusercontent.com/417336/43110364-22436034-8f1e-11e8-959a-17e266c63ced.png">
<img width="345" alt="p2d2" src="https://user-images.githubusercontent.com/417336/43110375-2ec9f66a-8f1e-11e8-8431-e5304ed6f34f.png">

### --Expected Results--
<img width="345" alt="p2d2a" src="https://user-images.githubusercontent.com/417336/43110382-38b445f4-8f1e-11e8-9eb6-2520be79ed0e.png">

### --System Information--
Pencil2D Version:
Version: 0.6.1.1
commit: 4f73eb168e0539e02789f0fdf009f18588278a02
date: 2018-07-17_10:20:55
Development build

**Comment by Jose-Moreno** [comment]
@jcome Thank you for reporting! Now that this has been mentioned I actually think it's rather important from a color styling perspective as not to confuse the artist if they have several colors with similar hues in succession.

As a note for the developers maybe the "selection highlight" should come below the color thumbnail and not above it in List Mode. I believe in Grid Mode this happen as well but since only the swatch is visible it's possible for that particular mode we need outlines rather than a shade to indicate the selected swatch.

**Comment by jcome** [comment]
@Jose-Moreno thanks for quick reply and detailed information. I guess I should do search before open new issue here.

**Comment by jcome** [comment]
@Jose-Moreno Yes, I misunderstood it. I was thinking there was already opened issue for it. :) my bad
