### ISSUE TITLE
pen cursor completely misaligned with tablet pen.

### ISSUE THREAD

**Issue by AKamp2** [pencil2d/pencil#1029]
### --Issue Summary--

When I draw the pen cursor is 4 inches to the left of where my tablet pen was physically on the screen
### --Actual Results--

Read summary
### --Expected Results--

Cursor and line should be where I drew it on the tablet (right below my pen)
### --Steps to reproduce--

Opened Program, drew one line, cursor and line completely to the left of where the pen was.
### --System Information--
+ Pencil2D Version:

0.6.1
+ Operating System:

Windows10
+ RAM Size:

+ Graphics Tablet:

Artisul D13
---

**Comment by Jose-Moreno** [comment]
@AKamp2 Normally Screen tablets have this issue. For example the Wacom Cintiq always has a physical offset that is critically annoying. But this is a defect from most screen tablets, not the software. 

For now all I can advice is to try to use your screen tablet drivers to calibrate the cursor as close as accurately as possible, if it provides you with that option (wacom cintiq, huion and other screen tablet brands have this).

Now it's different if this happens ONLY on pencil2D, which you should include as part of your description. Also please include what brand of screen tablet you are using, what is the reference model (normally a serial number that is akin to the "template" of the product e.g WTH-450 or similar) and also look what are the drivers version, and if you can update them to the latest version.

**Comment by Jose-Moreno** [comment]
I'm closing this for the following reasons:
1. Even though it is possible that Pencil2D had a problem with the Artisul D13, without further feedback from the user it is impossible to troubleshoot the issue.
2. Since the user is using a non-standard graphics tablet brand, we can't be sure about the driver compatibility with Windows 10 either, which is a factor.
3. The original report is from 2 years ago and user is using Pencil2D 0.6.1. so it is possible the newest versions will help improve or even fix the issue completely, assuming it was a problem with Qt framework or Pencil2D itself.
4. As mentioned in a previous comment, screen calibration is NECESSARY when using a screen tablet. Not one of these devices has perfect calibration, even on Windows 10, so this is the most difficult variable to troubleshoot; we simply don't have enough information.

Please download the latest version at http://pencil2d.org/download and try to use the screen tablet again with it. If you have properly calibrated the screen, installed the latest drivers and other software works correctly but not Pencil2D, please comment here again with this information and we'll reopen the bug report.
