### ISSUE TITLE
Pencil tool breaks when when used on a vector layer

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#1037]
### --Issue Summary--
After drawing on a vector layer with the pencil tool, it becomes unusable on any bitmap layers.

### --Actual Results--
Pencil tool does not draw anything on bitmap layers after drawing on a vector layer.

### --Expected Results--
Pencil tool always draws visible lines on bitmap layer.

### --Steps to reproduce--
1. Create new document
2. Switch to pencil tool
3. Switch to vector layer
4. Draw an invisible line on the vector layer
5. Switch to bitmap layer
6. Attempt to draw something on the bitmap layer (fails)

At this point, switching tools or layers does not fix the issue. It appears that the only way to get the pencil tool to work again is a full restart of the program.

### --System Information--
+ Pencil2D Version:
Nightly build 2018-08-02_20:35:58 (commit dd86ae4cd791ecc2f98e229af02464838137567a)

+ Operating System:
macOS 10.13.6

+ RAM Size:
16 GB

---

### --For Code Contributors--
A probably related minor bug is that the cursor stays as the bitmap pencil tool when the layer is first switched to the vector layer, suggesting that it isn't switching to the vector pencil tool until drawing on the canvas.

**Comment by Jose-Moreno** [comment]
@scribblemaniac I had confirmed this issue last time...however I revisited the problem once more on august 16th version. I noticed that what's happening is that when you use the pencil tool in the vector layer, and then switch back to the bitmap layer, the brush size is fixed to 0,50, so that's why there seems to be no painted strokes but actually it keeps painting just below the pixel size, and since the minimum bitmap unit is a pixel... well nothing shows but Pencil2D is recognizing the painting operation (autosave is invoked normally for example) on the bitmap layer. Once you make the pencil size bigger (+1px) you'll be able to draw normally. Can you confirm if this is the case on your end? or if the initial bug that you noticed still stands on MAC only?

**Comment by scribblemaniac** [comment]
@Jose-Moreno I can confirm that I am experiencing the same behavior as you. I did not notice the brush size had changed.

**Comment by scribblemaniac** [comment]
Thanks @Jose-Moreno. You observation saved me lots of time looking for the source of this issue. The width is no longer set to 0.5. Not sure why that broke the bitmap tool but setting it to 0.5 manually does not, but I don't really care as long it works now :wink:
