### ISSUE TITLE
Request a toolbar so can do Copy/Paste/Undo without keyboard

### ISSUE THREAD

**Issue by shakin1** [pencil2d/pencil#1047]
I can not do anything from the keyboard, nothing happens. I need to do anything with the toolbar. For example - copy, paste, undo a last action. All these and more are not working on the keyboard
what can i do?

**Comment by Jose-Moreno** [comment]
@shakin1 Hi, first of all, there is a report template laid out for a reason. Without knowing what operating system, and what version of Pencil2D it becomes very difficult for developers to understand why the problem might be happening. 

This is a bug tracker for confirmed bugs, but if you're not sure how to solve something it doesn't mean it's a bug. For that we recommend that you first use the software forum and the discord channel to ask about the problem you're having before actually submitting a bug report. 

You can find the other channels here http://pencil2d.org/community

So, please let us know what is the pencil2d version and what is your operating system version, so we can at least begin from there.

**Comment by Jose-Moreno** [comment]
[2019] This was discussed to become the implementation of an actual file operations toolbar that had the most common file operations from the File and Edit menus in button form, with their respective icons, such as:
- [ ] New File
- [ ] Load File
- [ ] Save File
- [ ] Save As
- [ ] Copy
- [ ] Cut
- [ ] Paste
- [ ] Undo
- [ ] Redo
- [ ] The toolbar icons should use of the current tooltip system
- [ ] This tool bar should have a visibility toggle, so it should work similar to panels (if not even be based on the same code) in order to preserve screen real-state when the user does not need the toolbar.


Example of a file operation toolbar:
![image](https://user-images.githubusercontent.com/4912907/65920804-c5412280-e3a5-11e9-88d2-ee9431003f73.png)

**Comment by davidlamhauge** [comment]
I would put those icons in a dockable window. Then it would take up less space, than a toolbar across the screen, and I (and probably many others) could close that dock, since I always use shortcuts.
That said, I still think it's a good idea, and maybe it should even be visible as default?

**Comment by chchwy** [comment]
A few Microsoft Surface users have asked this as well. The toolbar will help the users who are working on a touch screen (usually without a keyboard).

Qt's toolbar is very flexible. You can drag it around like a dock widget, also can show/hide it very easily.

**Comment by CandyFace** [comment]
On the flexible note I might add that Qt layout docking system is limited if you want to optimize the space of the toolbar as well as keep it possible to dock it, with our current dock setup I might add.

Because of this you won't for example be able to have it be as wide as the main window but will instead be put between the left and right widgets, like the timeline.

To me that's a problem because it will take up more space of the canvas than necessary but maybe that's just me.

I think a toolbar with easy to access actions is a fine idea though.

**Comment by davidlamhauge** [comment]
As long as a toolbar can be easily hidden, than I have no objections whatsoever.

**Comment by chchwy** [comment]
We can hide toolbar by default. Those who need it will find it.

**Comment by nickbetsworth** [comment]
I'd like to try and pick this up if it's still available 👍

**Comment by davidlamhauge** [comment]
Please go ahead @nickbetsworth, and make sure that toolbar can be hidden ;-)

**Comment by nickbetsworth** [comment]
I was planning on using a similar workflow to the existing dockable widgets (where they can be closed and re-opened via the (Windows ->) menu. The only exception to this would be the toolbar is hidden by default.

**Comment by Jose-Moreno** [comment]
It is unfortunate but the lead developer decided to reject the PR that was opened well over a year ago. The reason can be read on [this PR comment](https://github.com/pencil2d/pencil/pull/1289#issuecomment-681196477) but it basically involves asking for an implementation requirement to replace the widget that was used for a `QToolbar` which AFAIK seems to be the standard way to do it in Qt.

We'll gladly receive a new PR that has addressed this requirement by anyone who decides to contribute, We've also added the PR to the [**Never Forget**](https://github.com/pencil2d/pencil/issues?q=label%3A"Never+Forget"+is%3Aclosed) label in case anyone wants to reference it to supply an alternative. Thank you for your patience 👋
