### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MelodicMelon** [pencil2d/pencil#1052]
Whenever I use the select and move tool, after I use it, when I press my left and right keys, it doesn't move between frames. 
(update: nvm i found out how to fix it i just had to deselect all)

**Comment by CandyFace** [comment]
Hi MelodicMelon

This is the intended behaviour because one might want to adjust the selection. The arrow keys will become available for switching between frames after you deselect again, as you figured out.
You can however always use "," and "." to move between frames if you need to.

Please mind though, github issues aren't for help or uncertain bugs. Please use the forum for those kind of things, then when it's been confirmed or supported whether the bug is legitimate then you can file it as a bug here. In this case though it was the intended behaviour, which you could have asked about on the forum :)
