### ISSUE TITLE
Pencil 2d can't save

### ISSUE THREAD

**Issue by VoiceCrack** [pencil2d/pencil#1057]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by Jose-Moreno** [comment]
@VoiceCrack Hi. Please do the following:

1) Download the latest development build to confirm this issue is fixed for you: http://pencil2d.org/download#nightlybuild (make sure you download the version form AUGUST 31st from the Google Drive links)
2) Follow this guide to avoid losing work due to this problem: https://discuss.pencil2d.org/t/answered-making-jpegs-stransparent/2981/4

**Comment by scribblemaniac** [comment]
Closing due to lack of information.
