### ISSUE TITLE
can't enter numbers with the keypad into the fps field

### ISSUE THREAD

**Issue by wesen** [pencil2d/pencil#106]
on osx

**Comment by Jose-Moreno** [comment]
@wesen Sorry to bother you as I'm sure you no longer use the software, I'm parsing the repo looking to close issues that no longer apply, so could you confirm if this bug is fixed on Oct 10 Nightly Build for MAC OSX? . Thanks!

Here's the link: https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by wesen** [comment]
Works just fine!

Indeed, no time atm to do anything OSS / animation related.

Manuel

**Comment by Jose-Moreno** [comment]
@wesen Thanks! wish you well!
@chchwy This issue can be closed now.

**Comment by chchwy** [comment]
Thanks guys.
