### ISSUE TITLE
This is all it lets me write. ._.

### ISSUE THREAD

**Issue by LoganDidAThing** [pencil2d/pencil#1063]
![_pencil2d v0 6 1 1 - pencil2d 21_09_2018 12_48_31](https://user-images.githubusercontent.com/43471547/45879730-74174f80-bd9d-11e8-8315-313597154ad2.png)

### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by Jose-Moreno** [comment]
@LoganDidAThing Hi. This is a place to submit support tickets, and as such you have to clearly describe your problem. 

If you don't know what your issue is, or want you want to chat about it a bit more please use our [DISCORD](https://discord.gg/8FxdV2g) server or create a thread on the [FORUM](https://discuss.pencil2d.org/) so we can review the problem before considering it a critical issue.

**Note**: If you want the Pencil2D team to consider this or any other submission as a bug report you need to describe your problem in a very specific way. From the screenshot alone it's very difficult to understand if there's an an issue here. If you don't update this ticket with relevant information within the next 48 hours I'm afraid we'll have to close it on grounds of being an incomplete report. Thank you for your understanding.
