### ISSUE TITLE
Copy and Paste Doesn't Function

### ISSUE THREAD

**Issue by Deoro** [pencil2d/pencil#1089]
When I try to copy and paste part of an image in the bitmap or vector layer, it doesn't do it's job.

Nothing happens when I press ctrl v but I can see that ctrl x works due to the image disappearing when it is cut. 

In an earlier version I was using, I think this wasn't an issue, but what should happen is the copied or cut selection should show up after pressing ctrl v.

1. Use the selection tool and highlight any drawing.
2. Ctrl x or Ctrl c
3. Ctrl v

+ Pencil2D Version: 0.6.2

+ Operating System:

Windows 10 Home
Nvidia GTX 1050ti
Ryzen 5 1500x
Corsair Vengeance 16GB 2833ghz RAM

+ Graphics Tablet:

XP Pen G430

**Comment by Jose-Moreno** [comment]
@Deoro Thank you for your report we'll get right to it to investigate your issue!

**Comment by Jose-Moreno** [comment]
I just confirmed this issue on Windows 7. This isn't working in the RC1 either.

- Neither command is working via shortcut nor via edit menu.
- When attempting to paste inside a selection as well it's not working either.
- When trying to paste to another program (e.g Krita) like I could before it isn't working. 

By process of elimination the problem seems that the drawing is not being sent to the clipboard after copy and cut operations. But it might have to do with the selection tool since it was touched up before release. Perhaps a by product of auto cropping? 

Last working nightly was Version: 0.6.1.1
commit: 3892671dcd7c43f159949e0fb99f8fe078a85feb
date: 2018-09-05_14:03:10
Development build
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by scribblemaniac** [comment]
Issue caused by [these lines](https://github.com/pencil2d/pencil/blob/e0259f0276217b439fb80505a366f8876ae151a5/core_lib/src/interface/editor.cpp#L495-L498) in [this commit](https://github.com/pencil2d/pencil/commit/e0259f0276217b439fb80505a366f8876ae151a5). If anyone wants to fix it go ahead, I don't have the time to today.

**Comment by chchwy** [comment]
I am working on this issue.

**Comment by chchwy** [comment]
Please check the Nightly build 5 Oct 2018

**Comment by ExplodingLlama** [comment]
Same issue is happening on mac.
Version: 0.6.2
Operating System: macOS 10.14

Has it been fixed in the nightly builds?
