### ISSUE TITLE
Implement transparency channel export for movie formats

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1115]
### Issue Summary

Movie formats that we support like MP4, WebM and APNG can support alpha channels. I've had a few request for this from professionals where they want to export the video with the transparency enabled due to editing software limitations. 

This would go in tandem with #1114

**Comment by scribblemaniac** [comment]
For reference, this is very closely related to #1113.

**Comment by scribblemaniac** [comment]
I have just implemented transparency support for WebM and APNG export in bfd3d7443440276040af5a0dc7051dbfc63051d3. Obviously support for viewing the transparency will depend on the player you use to play back the exported file, but I have verified that the transparency channel works in Firefox and ffmpeg. In order to get ffmpeg to recognize WebM transparency, you must use the libvpx-vp9 codec before importing like this: `ffmpeg -c:v libvpx-vp9 myanimation.webm ...`

Two currently supported formats still remain: MP4 and AVI. What's important to understand is that these are both flexible container formats for various codecs. Currently we are using the h.264 codec for mp4 export and the mpeg4 codec for avi, which are both standard pairings from what I've seen. Both h.264 and mpeg4 do not support transparency. Well h.264 technically does support transparency, but nobody actually uses it and as far as I can tell ffmpeg does not even support it. We can create .avi and .mp4 files with transparency if we use a different codec, for example the png codec (different from apng) would work well for this purpose and can inside both avi and mp4 contains. *However*, the files it produces are much larger, there is no control over the quality of the result (always lossless I think), and it is less widely supported. For instance, Firefox views an mp4 file with a png codec as corrupt and cannot play it. To me that's a deal breakers since we do not want people thinking our program is broken because their players are unable to process our exported videos.

I think the best idea is to continue to use the same codecs for mp4 and avi, and add a new option for FFV1 export. Most people who need transparency are using it for transferring their animation from Pencil2D to some other application (ex. a video editor). The FFV1 codec supports transparency, is one of the best lossless formats, and [is well supported](https://en.wikipedia.org/wiki/FFV1#Applications_supporting_FFV1), making it ideal for this use case. I would probably put it in the .mkv format which is a common container format for FFV1 and eliminates the confusion that would occur if avi was used instead. It should be very quick to implement so I will just make a PR for it right away and we can discuss it further there.

Until we get some export format suitable for application to application transfer, I will leave this issue open.

**Comment by scribblemaniac** [comment]
@Jose-Moreno Yes we could add .mov with the png codec, you're right that it does seem to be commonly used like that in the video industry. While FFV1 is technically superior, it is more commonly used for video archiving, so it may be better to use .mov instead. Of course we could add both, but there isn't much benefit to having both of them.

A matte would be easy to implement as well. ffmpeg has an extractalpha filter which does exactly what you want. Alternatively we could do the extraction ourselves, it's a pretty trivial operation. Not sure which would be better from a resource/speed standpoint. What should the UI look like for this though? Should it create a second video file at the same time when a checkbox is clicked? Should it be a separate export matte option?

IANAL but there should not be any licensing issues since all decoding/encoding is done by ffmpeg not us.

**Comment by Jose-Moreno** [comment]
@Jose-Moreno That'd be great then. I was reading also on the AVI codec and some people pointed that TGA was used, again this from a studio perspective as AVI is mostly used with editing consoles (hardware) and TGA is ancient as well mainly used with older but industry grade video cards, so it's kind of like a industry standard, but i digress.

As for the UI on the matte thought, I'd have to think about it and make a draft but I was considering having a "preview" window in the export dialog. If the matte functionality was to be implemented checking it's toggle would enable be a split-screen preview window with the "final" video look on the left, and the b&w matte on the right.

This preview window could be a separate widget though (perhaps invoked by a "preview..." button on the export dialog) as It would be great to also have it for the movie import as well (along a timeline to extract portions of said video to avoid importing the whole thing, but again that is a separate issue altogether)

**Comment by Jose-Moreno** [comment]
@scribblemaniac given our previous discussions and that the "matte" option for exporting a separate alpha mask should be filed under a different request issue, and that you already implemented the WEBM and APNG transparency option should we close this?

**Comment by scribblemaniac** [comment]
> Until we get some export format suitable for application to application transfer, I will leave this issue open.

Although I said this, it does make more sense to treat this as a separate issue too, so I suppose we can close this.

Issue TLDR; We now support transparency for the .webm and .avi formats. There are no current plans to implement transparency support for the .mp4 file format due codec limitations. Other features such as .mov and matte export will be explored further in the future.
