### ISSUE TITLE
bitmap: Smudge tool is broken

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#1122]
### Issue Summary
The smudge tool is broken in newest nightly build... it's likely an unexpected bug coming from #1059 

 

### Actual Results
![bug](https://user-images.githubusercontent.com/1045397/47952107-d05bba80-df6a-11e8-97ec-01a47fb00bbe.gif)

 

### Expected Results
![real](https://user-images.githubusercontent.com/1045397/47952113-e5384e00-df6a-11e8-8a54-0968c58b4715.gif)

 

### System Information
+ Pencil2D Version: b12c7109eedf4519af6bc036ee8fb2f45a3e1a67

**Comment by Jose-Moreno** [comment]
I'm sincerely considering that we discuss disabling the smudge tool while we fix it :unamused: I mean it was considered "broken" before how can it be "more" broken now? :joy:

**Comment by CandyFace** [comment]
Nah, we just gotta backtrack and figure out what went wrong and fix it. It's probably a one liner somewhere >->. the most annoying and scary thing though this is that the smudgetool code itself hasn't been touched, so it's some global thing we're doing in (assuming) mousemove in scribblearea that broke it.

**Comment by scribblemaniac** [comment]
Summary of issue: because of some changes during the tablet input changes, `mCurrentWidth` was no longer being updated from it's default state of 0 in SmudgeTool. I fixed this by adding the same `mCurrentWidth = properties.width` line that is found in the other tools. I'm not even sure why we need a member variable for it though if we're always going to update from properties.
