### ISSUE TITLE
Onion skin bug

### ISSUE THREAD

**Issue by Viligor** [pencil2d/pencil#1124]
My Onion skin doesn't work!

**Comment by Jose-Moreno** [comment]
@Viligor A few questions:
1) Are you using the latest version of Pencil2D? If not please download it here: http://pencil2d.org/download
2) Did you press the button on the timeline that says "onion skin"? If you did, that button does not enable the onion skin functionality. To enable it please go to the **Display Panel** and turn on the Onion Skin Prev / Next buttons OR go to View > Onion Skin > Toggle Previous / Next (O / Alt +O)
3) Are you using a full image as a background? If so, then please turn the background image to be able to see your onion skins, this is a known bug and the developers are already aware of it.

If neither of these troubleshooting questions solve your issue, please capture a screenshot of the whole Pencil2D interface that descriptively shows you trying to use the onion skin feature so we can at least analyze what is happening.

**Comment by Viligor** [comment]
Thanks very much! It worked!

**Comment by Jose-Moreno** [comment]
@Viligor Alright. I'll close this then. Please remember that this is a site to report confirmed software bugs, it's not used to handle support tickets.

Next time firstly please ask for help in our dedicated forum at http://discuss.pencil2d.org or visit any of our community driven hubs at http://pencil2d.org/community so we can categorize it as a bug or not. It helps a lot so developers can focus on fixing bugs instead of giving one-on-one support. Take care :slightly_smiling_face:
