### ISSUE TITLE
Group Onion skin functionality in a panel

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1125]
### Issue Summary

This is a request to group the onion skin functionality, that is scattered through Pencil2D, into a single place to avoid segmentation of the user experience and improve the efficiency in workflow as well as to avoid misconceptions (user does not know certain features exist) and confusion (people instinctively click the onion skin button on the timeline > doesn't work > label it as nonfunctional)

I'd like to ask for a new onion skin panel to be designed and implemented as well.

**Discussion**: The problem with having the display panel hold the onion skin at the moment vs having it grouped with the other parameters, is that if you want to turn just the onion skin options off or the "canvas visibility options" only you have to also hide the other one as well. 
I also think it would be better to leave the display panel as a general purpose panel that handles anything related to how the user views the canvas, and create an onion skin panel to groups said functionality together as other panels do in general (e.g tools, options, palette, etc).

**Note**: This migration would not include any future layer-based onion skin switches or other future widgets that are dependent upon onion skin operations like the proposed "shift & trace" functionality. Just the elements on the preferences and the button on the timeline.

**Migrating functionality**

- [x] Move the Preferences > Tools > Onion skin section outside the preferences and onto the panel. These options are often needed for quick access.
- [x] Move the Onion Skin: Toggle Match Keyframes to the panel
- [x] Move the Onion Skin display during playback from Preferences to the Panel

### Video or Image Reference

**Note**: Only consider the components, not the graphic design itself or the space used by the components.

![image](https://user-images.githubusercontent.com/4912907/48025458-75b09300-e111-11e8-8559-2f002d72d6d0.png)

_Is it possible to have a double slider as in the mockup with QT? or would it have to be programmed from scratch?_

**Comment by scribblemaniac** [comment]
> Is it possible to have a double slider as in the mockup with QT? or would it have to be programmed from scratch?

There is currently no qt widget for a double slider like that. We may be able to use [this code](https://stackoverflow.com/questions/17361885/range-slider-in-qt-two-handles-in-a-qslider?noredirect=1&lq=1) as a starting point though.

I agree these should all be grouped together. I think if we do this, it might be best to get rid of the display widget all together. The show invisible line and show outlines only are not things I could see changing all that often, especially since vector layer use is discouraged right now. They could be moved to the preferences. The flip view buttons are useful and could conceivably be changed often, but I don't think we should have a widget for just two items. Actions in the top menu with shortcuts would probably be fine. We have also seen that they can lead to confusion if left on (https://github.com/pencil2d/pencil/issues/847), so if there should be some obvious visual indication that the canvas is flipped, but that could be its own issue.

**Comment by CandyFace** [comment]
I like the proposal and agree. I think that this could be a good opportunity for a popup window. Instead of removing the display panel however I think that we should remove the onion skins related icons from there and add an onion skin preferences icon instead. Clicking on this icon would open a window as a popup, so that one can quickly access the mentioned actions and simply click outside the boundaries of the window again to get back to the canvas. No need to confirm or press ok or cancel. The actions you make in here should be perceived as final.

**Comment by Jose-Moreno** [comment]
I have addressed this issue and grouped the onion skin features in a single panel on a PR. We've had far too many support tickets asking about the onion skin options, so I decided to expose them clearly to the user as first priority. 

This new panel is functional, which means it has the same options as before organized logically, but there are no graphic design improvements or changes, only UX.

Later on I'll open a new "enhancement" issue regarding the graphic design so we can address this on the road to 1.0 or after :slightly_smiling_face:
