### ISSUE TITLE
The 'install' target doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [pencil2d/pencil#1127]
It is supposed to install files into ```$(DESTDIR)$(PREFIX)``` or ```$(INSTALL_ROOT)$(PREFIX)```.

Observed this problem while trying to create the FreeBSD port.

**Comment by J5lx** [comment]
When I originally added install support I made it Linux-only because I
wasn't sure how much of it was truly *nix agnostic or whether part of it
might be Linux specific (see
https://github.com/pencil2d/pencil/pull/671#issuecomment-301484555) –
though looking back I have no idea which parts that would've been.
Still, while you're here would you mind taking a quick look at the linux
section towards the end of app/app.pro and check whether all of it
applies to FreeBSD as well? If that's the case we might as well turn it
into a unix:!macx section.

**Comment by scribblemaniac** [comment]
@J5lx Beat me to it, but I'll post this anyway. We do use `$(INSTALL_ROOT)$(PREFIX)` with `PREFIX` being defined during `qmake` and `INSTALL_ROOT` during `make install`. It appears to be working fine in our travis builds if you want to use those for reference.

The code that @J5lx was talking about which you may have to modify for FreeBSD can be found [here](https://github.com/pencil2d/pencil/blob/b5ae22c8d1ed0fbe28c8b580406d028616f9efd6/app/app.pro#L138-L157).

**Comment by yurivict** [comment]
@J5lx This linux section perfectly matches FreeBSD. You can just assume that it would match it for all ```unix``` systems, IMO.

**Comment by J5lx** [comment]
Alright then. I’m still not entirely sure about mac support, though, so @scribblemaniac could you tell me:

- Are Desktop Entries, MIME packages and icons contained within icon themes (as detailed in their respective fdo specifications, which I note originate in X11-based software) useful on mac as well?
- Bash and Zsh completion need to be placed in specific paths. Are these [prefix]/share/bash-completion/completions and [prefix]/share/zsh/site-functions on mac as they are on Linux (and other unices I suppose) or does mac use other default paths?

**Comment by scribblemaniac** [comment]
Well there is no such thing as desktop entries in mac. Mime types and icons are specified in the Info.plist file and the icons themselves are contained in the .app package. I don't think here would be any use for these on mac.

Now that I look at it, I don't think bash completions are installed by default. zsh completion might be installed by default because I do have a /usr/share/zsh/site-functions. We could leave both of them out for now and modify our homebrew cask to install them in the correct place. Or we could install them even if the completion program isn't installed. If bash-completion is installed, I'm pretty sure it would read form [prefix]/share/bash-completion/completions.
