### ISSUE TITLE
copy paste doesn't function (again) 24-dec-2018 windows 10 32 and 64 bit both

### ISSUE THREAD

**Issue by Sitearm** [pencil2d/pencil#1146]
### Issue Summary
Copy Paste does not function with a selected item, neither from the menu Edit Copy   Edit Paste menu nor from the short cuts CTRL C  CTRL V. The selection rectangle stays lit.  See attached screen shot.

 

### Video or Image Reference

![pencil2d copy paste bug 24-dec-2018](https://user-images.githubusercontent.com/46113472/50407084-09a7ee00-0796-11e9-8e67-898791a81a1b.png)

 

### Steps to reproduce

Draw something in the first frame. Select it. Try to copy and paste it to a new frame.

 

### System Information
+ Pencil2D Version:

Version: 0.6.2
Operating System: Windows 10 (10.0)
CPU Architecture: x86_64

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@Sitearm Hi. First of all, thank you for submitting a report :slightly_smiling_face: 

Can you please check that you're using an actual nightly build? Currently the nightly builds are the ones that have the fix, but the download version on the pencil2d website does not as that is the **release version** and will be replaced with an upcoming version.

I mention this because the latest build is from december 20th, not the 24th, and copy paste is working in that version. Or did you compile from source to test this?

Either way please use the Nightly Build from October 14th where possible as this one is the most stable and has the copy/paste fix implemented:

**Win64:** https://drive.google.com/file/d/1-kZs1-OMhX8E2bc4rYLcP8hCkJH-2-4B/view?usp=sharing

If you need to use several sound samples though, there's an issue that was fixed but has not been implemented just yet, but if you require that build, a custom one was made for another user to test said issue. You can find that in this forum thread:

https://discuss.pencil2d.org/t/please-help-no-sound-when-exporting-to-movie/3283/6

**Comment by Sitearm** [comment]
@Jose-Moreno Hi. I have installed Nightly Build from October 14 / pencil2d-win64-2018-10-14.zip and verified I can copy paste thank you! PS I had no idea how quickly response would be! 👍

**Comment by Jose-Moreno** [comment]
@Sitearm You're welcome! We try to answer as fast as possible in order to triage the bug reports. Fixing actual bugs might take more time of course but we try our best :smile: Let us know if you have other issues that are not reported in this repository, other than that Merry Christmas! :santa:

**Comment by BugReporter-01** [comment]
@Jose-Moreno Hello, the link to the Nightly Build from October 14th is now dead. Could you please reupload it? Or tell us, please, which build can be considered the most stable at the moment?

**Comment by chchwy** [comment]
Hi @BugReporter-01 Please download the latest nightly build. It's very close to the final version of v0.6.3.

**Comment by Jose-Moreno** [comment]
@BugReporter-01 Hi, the nightly builds are always publicly available at https://www.pencil2d.org/download/#nightlybuild

Here's a direct link to the latest ones for each major system:

- **Windows (7+ | x64bits)** https://drive.google.com/open?id=1i1gQRE4En5YMKvU44Hkyt-cTiTy__M2k
- **macOS (10.11+)** https://drive.google.com/open?id=16M8BkbeNpCxhRuoUwYSkQgyZ9uvRga5e
- **Linux (AppImage)** https://drive.google.com/open?id=17jHH9rjyHVlzntqTZ-0Z7819AobCnxON

**Comment by BugReporter-01** [comment]
@chchwy @Jose-Moreno Thank you for the instant answer! I'll use the latest build.
*Glad that nice program is back in development!*
