### ISSUE TITLE
[ISSUE] Not able to use the Dynamic Control Size accurately

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1150]
### Issue Summary

 
When using my pen tablet and try to resize the size of any tool using the shortcut (Shift + Drag Left/Right) , the range of values moves too fast.. It worked fine on previous versions
It works fine when using a mouse

### System Information
+ Pencil2D Version:
20/12/2018

 

+ Operating System:
Win 8.1 x 64bits
 

+ RAM Size:
32GB

 

+ Graphics Tablet:
HUION HD185

**Comment by Jose-Moreno** [comment]
This is true, although to be fair I think originally that feature was bit weird. It would be better if this could be made form scratch once the brush system is replaced also so it can be configured to work with other shortcuts like the ALT key instead of the SHIFT key, so we can use the SHIFT key to draw straight lines.

**Comment by MrStevns** [comment]
This has been fixed in release 0.7.0
