### ISSUE TITLE
Debug-like text in menu for Undo and Redo

### ISSUE THREAD

**Issue by davidlamhauge** [pencil2d/pencil#1170]
### Issue Summary
Odd text is appearing in the menu for Undo and Redo. It looks like debug messages, and then again - it's not...?
 

### Actual Results
(Se pictures below)
Picture 1: A new scene. Menu looks perfect.
![undoredo01](https://user-images.githubusercontent.com/1292931/52415284-da9bd080-2ae6-11e9-8c23-770056cf0e19.png)
Picture 2: I write '1' and '2' on the canvas, and the menu shows what tool I used(?) + a number
![undoredo02](https://user-images.githubusercontent.com/1292931/52415285-da9bd080-2ae6-11e9-83ad-1c72374e8e08.png)
Picture 3: I Undo, and the menu gets even weirder...
![undoredo03](https://user-images.githubusercontent.com/1292931/52415286-db346700-2ae6-11e9-9048-233287479d83.png)
 

### Steps to reproduce
As mentioned above
 

### System Information
+ Pencil2D Version:
Latest master branch.
My guess is that @CandyFace maybe has the key to this issue?
 

+ Operating System:
Ubuntu 18.04
 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by scribblemaniac** [comment]
The number appears to be the position of the item in the undo stack. That is a little bit weird, but maybe there's an argument to me made for it's value since it makes it easier to tell that your actions are having an effect when you are trying to undo many of the same actions like brush strokes for example.

The redo text definitely should not be "Menu item text 2" for everything though. That's a bug for sure.
