### ISSUE TITLE
The audio is only on one frame

### ISSUE THREAD

**Issue by Sarah-Ann-H** [pencil2d/pencil#1180]
### Actual Results
The audio would only attach to a single frame instead of many when i imported sound and it was only on one frame and when i made a new frame in the sound layer it went to my files so that i could import a new sound.
 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@Sarah-Ann-H Hi. Thank you for issuing a report. Please make sure to fill in all the necessary information  as outline on the template though. 

What's most important is: which Pencil2D version you are using. What is your Operating system and when you have issues related to sound files it's very important to mention what type of audio file you used (mp3, wav, etc) otherwise it's really hard to help as the program is not behaving like that for most people.

From the get go I can assume you were using an MP3 file as we've had very similar cases where users have problems with those types of files. And the problem doesn't really come from Pencil2D, but it lies with those files as there are a handful of patented codecs in the music bussiness that are not compatible with open-source software due to licensing.

So my proposed solution for you, while you provide us with the necessary info, is to convert the MP3 file to WAV using a free sound editor like [Audacity](https://www.audacityteam.org) and try to import it again.

If this workaround does not allow you to open the sound sample either, then please also let us know about it so we can narrow down the root cause of your issue and developers can review it properly. Thanks in advance.

**Comment by chchwy** [comment]
A one frame sound file usually means that you imported an unsupported audio clip. Please convert the audio clip to an **mp3** or **wav** and try again.

**Comment by Jose-Moreno** [comment]
This is not working in **Ubuntu 18.10** Appimage. Let's keep this issue open to address that specific problem on Linux considering the other OS are not exhibiting this issue.

**Comment by Jose-Moreno** [comment]
@Sarah-Ann-H Hi. We noticed you closed this issue. Did you manage to fix it? if so what did you do? Since we were waiting for more information based on the questions we posted earlier in order to start the troubleshooting we never knew what was the issue or if it was related to other problems. 

We'd appreciate if you could at least tell us how you solved this problem or if you didn't then we'd keep this issue open until there's a proper solution. Thanks in advance.
