### ISSUE TITLE
High feathering values do not allow pixel application on canvas

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#1193]
### Issue Summary

Any feathering value above 96 (tested with Qt by modifying ui files) will clamp the feather and not draw any pixels at all. This affects particularly the Brush Tool as it is the only active tool that paints with variable feathering but this is a global issue, so the Pencil tool, the Smudge tool or any other tool that would be set to sue feathering would suffer from this issue.

### Expected Results

I mentioned before a value fo 200 might be good, but what I meant was that a value that amtched the maximum SIZE value, would work, however it seems the calculations say otherwise.

On Discord it was suggested to clamp the feathering values from 0 to 100, but the maximum feathering value should never stop the user from painting, at most it will give a very faint and smoothed out paint feel.

### Steps to reproduce

1. Open Pencil2D
2. Select the brush tool and move the slider to the right most edge. The input box will say 80, but this is another bug reported here: #1194
3. Try to draw anything.
4. Move the slider to the left little by little until you can draw and compare.

### System Information
+ Pencil2D Version:
Version: 0.6.3
Operating System: Windows 7 SP 1 (6.1)
CPU Architecture: x86_64

**Comment by davidlamhauge** [comment]
I have looked into this, and it seems as if feather values from 99.6 and up, will prevent any changes to the canvas.
I don't know how feathering is working under the hood, but it seems logical to set maximum to 100 (or 99), since we don't want frustrated users.
I have noticed that the opacity value, when you use the feather, is 0.5 or lower! My guess is that this is the key to the problem, but I have no clue what happens.
