### ISSUE TITLE
Better document/handle supported Mac OS & Qt versions

### ISSUE THREAD

**Issue by follower** [pencil2d/pencil#1222]
### Issue Summary

Pencil does not run on certain Mac OS (Mac OS X/macOS) versions due to OS & Qt support. The versions supported may differ between source & binary releases.

Ideally as many versions as possible would be supported but when this is not possible it would be good to document the supported versions & use the OS & Qt supplied tools/conventions to communicate the supported versions.

Minimum:

 * Document (and ideally verify) the supported versions on binary download page.
 * Document required versions to build from source.

Better:

 * Use existing Qt & Mac functionality to:
     * support as many versions as possible.
         * e.g. via `QMAKE_MACOSX_DEPLOYMENT_TARGET`, `MACOSX_DEPLOYMENT_TARGET`, `--macosx-version-min`.
         * Use Qt versions built with for the correct OS version.
         * Ideally use features that are backward compatible rather than just "new" but not better. 
     * communicate when a version is unsupported.
          * e.g. via `LSMinimumSystemVersion` in the `Info.plist`.

### Actual Results

On Mac OS 10.9.5 the Pencil app opens and (after the usual verification the first time) then immediately closes without further messages--including in logs.

If run via the command line (with `Pencil2D.app/Contents/MacOS/pencil2d `) the following message appears:

> Sorry, "Pencil2D" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.9.5.

However this never appears in the GUI.

### Expected Results

Ideally, Pencil runs.

Less ideal but understandable, the lowest version is documented on the download page and/or the app appears with the "Circle with Diagonal" No symbol on the app icon.

### System Information
+ Pencil2D Version: 0.6.3 (binary download)
+ Operating System: Mac OS X 10.9.5
+ RAM Size: N/A
+ Graphics Tablet:   N/A

### Related links

 * [MAC OSX 10.9.5 Pencil2D Won't Open - Bug reports - Pencil2D Community](https://discuss.pencil2d.org/t/mac-osx-10-9-5-pencil2d-wont-open/1317/9)
 * <https://github.com/pencil2d/pencil/wiki/Building-Pencil2D-on-macOS> Specifies macOS 10.12 mentions macOS 10.10 suggests Qt 5.9.
 * See also: "[Configuring a Project for SDK-Based Development](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html)"

*Edited:* Added last related link.

**Comment by scribblemaniac** [comment]
> Document (and ideally verify) the supported versions on binary download page.

Supported OS versions are now documented on the Downloads page.

> Document required versions to build from source.

There are no requirements on our end for what version is required to build from source, it all depends on which compiler and Qt version you use, which is documented on their respective websites.

> support as many versions as possible

We now have a Mac OS X legacy build available. Between the legacy build and the main build, we support all versions >= 10.7. There are currently no plans to support older mac versions as the code will not work easily with any Qt version below 5.6 because of some of the features we use, and Qt 5.6 only supports 10.7 and higher.

> via LSMinimumSystemVersion in the Info.plist

I have added this to the info.plist, it will be in the next release and all future nightly builds.

Specifically for your situation of Pencil2D not running on 10.9.5, you should have no problem running it now with the v0.6.4 legacy mac version. And with that I think we've address all of the problems associated with this issue. I will close it now, please reopen this issue if I missed something or open a new issue if you've thought of something else. Thanks for your detailed report.
