### ISSUE TITLE
[ISSUE] When Exporting a PNG image, the PNG extension is not added when selected

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1224]
### Issue Summary
When wanting to export an image as a PNG file the extension is not added when it is first selected
 

### Actual Results
You have to select another extension and came back to PNG in order for it to be added.
 

### Steps to reproduce
Open Pencil2D as default
make a stroke
Go to File > Export > Image > FILE (browse to the path you will like the image to be saved) > Select the name of the image > Click Save (it will bring back the Export-Image window) > Go to the FORMAT bar and after opening all formats by clicking over the bar, select PNG by hitting it > PNG extension is not added to the image name on the File bar.
Continue the last step but this time selecting JPG > it is correctly added to the image name > now go and hit PNG > the extension is finally added to the name

 

### System Information
+ Pencil2D Version:
Compiled Code from 31/May2019

 

+ Operating System:
Windos 8.1 x 64bits

 

+ RAM Size:

 

+ Graphics Tablet:
Huion Tablet

**Comment by Jose-Moreno** [comment]
@Kaikogf This for some reason has been happening to Windows users that upgrade to any version between 0.6.2 and 0.6.3+. This also happens when exporting movies.

The workaround and individual (per user) fix is that you have to manually type the filetype (e.g PNG) along with the name when the file explorer opens (e.g my_image.png), if you do that the PNG extension will continue to show properly in new work sessions.

Please try that, and let us know if it solves this issue for you, but even if it works I have to ask you not to close this Issue. I personally want to investigate this problem to see if after deleting all the Pencil2D preferences this continues to happen in Windows 7. If not then it might be a problem that is particular to Windows 8 & 10 instead.

**Comment by scribblemaniac** [comment]
I do not believe this is a Windows specific issue. The program will remember whatever filename you saved as before, and if that doesn't include a filename, then it doesn't add it. It could be argued that this is not even a bug as long as the initial default filename has an extension, because the only way for it to lose that extension should be for the user to explicitly remove it at some point. Having said that, I think that it should add an extension if there is none when the dialog is opened. Perhaps an extension should even be required.

**Comment by CandyFace** [comment]
^I'd still classify it as a bug, it should not be possible to export without an extension.

**Comment by Jose-Moreno** [comment]
@scribblemaniac with #1123 an original issue on filetype naming was "fixed", but after merging the PR the extension was supposed to be forced, but this problem started appearing roughly around the time 0.6.2 was released. I mean even if you type the name without the extension, the filetype extension is forced in latest versions, it's not possible to remove it by user input.

However exactly what happened related to the current issue is that Pencil2D was not adding the extension by itself on the first run of the program (at least that's what i've gathered). 
As such I've provided support for various users who were making new files, with the latest versions of Pencil2D downloaded after a release at the time, and when they were about to export movies or images, the files themselves had no filetype extension attached. I even had to do a teamviewer session to fix the problem for a user on facebook. It took a while to manage spotting the issue and understanding how to "solve" it. 

I had this issue before, when I downloaded Pencil 0.6.2, but it only happened once. After that I've never been able to reproduce this problem on my own machine, after that it kept working as expected. But the real problem is that it keeps getting reported from time to time, and so far all the reports have three criteria: 1) The user has Windows and 2) It has a spanish language locale installed. At least those are the only things i'm positive about that connect all these users.

While some also used the spanish version of Pencil2D, others didn't necessarily. Also most of the users had used Pencil2d before in some way. Manually adding the extension once, fixes the issue.

For now i'll try to reproduce the issue actively, but other than a mild annoyance this issue has a permanent workaround and it's not a critical bug, but I'm requesting leaving this open until I've exhausted all means of finding why this keeps happening.

**Comment by Jose-Moreno** [comment]
Ok, when opening the latest nightly from Jan 9th I tried to reproduce this and I could. I must be because I usually never export still images but since this was the "first" time I got this result:

![image](https://user-images.githubusercontent.com/4912907/72395638-26e48d00-3708-11ea-9093-7152ace716eb.png)

As @Kaiko originally mentioned, using the drop down menu to change the extension type will indeed add the extension afterwards. It's just not added by default the very first time.

However, according to the original issue saving the **file name** would not append the **filetype**, but now when using the "Browse" button and saving the image to a new file folder the PNG, or any other, extension will be automatically added to the name.

![image](https://user-images.githubusercontent.com/4912907/72395747-7b880800-3708-11ea-9cf9-d46b6176904b.png)

Can you test it if this behavior satisfies your requirements to close this issue?

**Comment by scribblemaniac** [comment]
We should add a check for the extension when starting up the dialog too to avoid confusion.

**Comment by Kaikogf** [comment]
Already fixed
👍 

[build 04Jan2021]
