### ISSUE TITLE
Selecting tool with "eraser" end of stylus swaps "pencil" and "eraser" ends of stylus

### ISSUE THREAD

**Issue by ryan17171** [pencil2d/pencil#1271]
I'm not sure if this is the intended behavior but if you select a tool such as the Pencil from the Tools pane using the back ("eraser") end of a tablet's stylus, the back end of the stylus becomes the drawing end and the front end becomes the erasing end (opposite of what it should be).  You can reselect the tool with the drawing end of the stylus to fix the issue.  I'm using a Wacom Intuit graphics tablet.  This occurred for me in a Bitmap layer.

 

See above explanation

 

I think the drawing/erasing ends of the stylus should be fixed.

 

### Video or Image Reference

 

See above description

 

### System Information
+ Pencil2D Version:
Version: 0.6.4
Operating System: macOS Sierra (10.12)
CPU Architecture: x86_64

 

MacOS Sierra 10.12

 

+ RAM Size: 8 GB

 

+ Graphics Tablet:
Wacom Intuos CTH-480

**Comment by J5lx** [comment]
@Jose-Moreno I recall you mentioning somewhere that you have a tablet with pen flip, have you had a look at this?

**Comment by Jose-Moreno** [comment]
@J5lx The problem is that the OP had macOS 10.12, I use Windows 10. I could test this and narrow it down as a OS specific issue just in case if that's what you meant 👍

**Comment by J5lx** [comment]
Yes, that is what I meant. Since this issue was originally posted, it has been lying around for nearly two years without anyone having a closer look at it, so I figured that’s the least we could do.

**Comment by scribblemaniac** [comment]
I have a similar tablet as well. I have tested this on macOS 10.13 with Pencil2D versions 0.6.4 through to 0.6.6. I also tested this on linux with 0.6.6. I can confirm that this is still an issue in all of these tests. This behavior is not too surprising given how the temporary tool functionality is coded. When testing with the latest master branch, the behavior is better as it no longer seems to get "stuck" when switching back to the pen side. However, there is still has a lot of room for improvement. In part motivated by this and in part just because it was already in need of refactor at least, I have rewritten the code to handle temporary tools in a PR I will make shortly, which will completely fix this issue and hopefully give a logical consistent behavior to the temporary tool features and pen eraser recognition.
