### ISSUE TITLE
Pencil 2D save problem

### ISSUE THREAD

**Issue by mael-ui** [pencil2d/pencil#1272]
There is the problem : 

FileManager::save
strFileName = /Users/mael/Desktop/Animation panéte.pclx
strTempWorkingFolder = /var/folders/yx/6_wc8ldd3fg3j1fxlb8c031m0000gp/T/Pencil2D/Animation panéte.Y2xD/
layerCount = 3
layer[0] = Layer[id=1, name=Calque caméra, type=5]
layer[1] = Layer[id=2, name=Calque vecteur, type=2]
layer[2] = Layer[id=3, name=Calque image, type=1]

Error Display
Title: Erreur interne
Description: Une erreur interne a eu lieu. Votre fichier peut ne pas être enregistré avec succès.

System Info
Pencil version: 0.6.1.1
Build ABI: x86_64-little_endian-lp64
Kernel: darwin 14.5.0
Product name: OS X Yosemite (10.10)

**Comment by Jose-Moreno** [comment]
@mael-ui Hi, first of all sorry to hear about your issue. We see that you're using an older version of Pencil2D, please upgrade to the latest version available which is 0.6.4, and we have a special build for 10.7 up to 10.11 available.

https://www.pencil2d.org/download/

![image](https://user-images.githubusercontent.com/4912907/65905025-6075d000-e385-11e9-83bd-b9e61ba6bc54.png)

We still haven't tested this special version thoroughly since we lack the equipment to do so, but it should be generally more stable, we also will be releasing 0.6.5 before December which should also contain a fix related to a file saving issue we discovered recently.

If you have any other piece of information you can share on what you were doing and when the crash triggered, please let us know.

**Comment by mael-ui** [comment]
thank you

**Comment by scribblemaniac** [comment]
Given how old the version of Pencil2D was that this occurred on and that we haven't had any other reports like this, I'm going to close this. Please create a new issue if this is still an issue with the updated version.
