### ISSUE TITLE
Is it normal to have the same image exported as PNG and JPG with so much difference in size?

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1310]
### Issue Summary
I think I have mentioned this before else where but I was not able to find it so I would like to refresh it here: When I export the same image as JPG, the result is an image 10 times smaller than the one exported as PNG (with or without transparency)

So, is this a  normal behavior?

Windows 8.1 x 32Gb, Huion HD185

**Comment by chchwy** [comment]
Do you mean file size?

**Comment by scribblemaniac** [comment]
If you do mean file size, yes this is expected behaviour. PNG is a lossless image file format while JPG is lossy. This means that JPGs can usually be made much smaller than PNGs, but the trade-off is that they do not exactly represent the original image, they only look similar. Exactly how similar depends on the quality level the JPG is exported with, but  in many cases it's visually identical.

You will find that BMP is even larger than PNG because it is also a lossless format but does not use compression. PNG uses a lossless compression algorithm to make its file size smaller without loosing any information about the image.

**Comment by Kaikogf** [comment]
I was referring to the file size @chchwy and @scribblemaniac :+1: 

Thank you @scribblemaniac for the explanation. It really come in handy :1st_place_medal: 

So, as there is no issue here I am going to close this post
