### ISSUE TITLE
pressure doesnt work

### ISSUE THREAD

**Issue by PomfPomfMe** [pencil2d/pencil#1316]
i have bamboo cth-470 , win7 and both the latest version of the soft and the newest dev verion.

my problem is :  pressure check is on and no brush will draw, if i disable pressure then i can draw but obviously with no pressure. and yes i have up to date drivers (just installed them) and everythign updated .

heads up is i work in telecommunications and general IT so its not a user error as far as i can tell

my photoshop cs6 works with pressure just fine

**Comment by Jose-Moreno** [comment]
@PomfPomfMe Hi. Thank you for taking the time to outline your hardware specs, it really helps.

In regards to Wacom, in general there's a bit of an issue with their drivers, regardless of date. While having the latest drivers is a good thing, the company itself has never fixed a weird problem where the drivers simply shut off. 

I had Windows 7 Ultimate until 2 months ago, and I can tell you I suffered from this with an Intuos Pro 5 every single day, and with every art software. Only Photoshop and some other commercial apps tried somewhat to preserve the WINTAB socket connection, but after a while there's a moment where you HAVE to reboot your computer. Fortunately I found a way to actually refresh the service to avoid rebooting.

With that said let's try a few things in order:
1. Run Pencil2D as an Administrator. Test
2. Run Pencil2D with XP compatibility. Test
3. On your Wacom preferences, create an application preset to control only Pencil2D and try testing different settings such as:
    + Changing the pen mode to mouse mode back and forth
    + Changing the Hover Click setting to Click & Tap and back (for more info please review this link https://101.wacom.com/UserHelp/en/AdvancedOptions.htm)
4. On your Wacom preferences, Turn OFF the Windows Ink checkbox. 
![image](https://user-images.githubusercontent.com/4912907/77601938-2e7b9b80-6eda-11ea-8bbe-f6deb6be3ed1.png)

5. Lastly after trying all of those options in order close Pencil2D and restart the Wacom service here's a guide to do that https://machollywood.com/blogs/news/restarting-your-wacom-services-driver
6. After you have stopped the service make sure that the processes that are related to "Wacom" have been removed from the task manager, otherwise restarting the service will not work properly
![image](https://user-images.githubusercontent.com/4912907/77601438-bfea0e00-6ed8-11ea-81f2-0c92c3c66484.png)
7. Open Pencil2D only after the service has been restarted. Not before or it won't work either way.

After that also try the latest development build (march 19th) for windows (64bits) from this link: https://drive.google.com/open?id=118ihk6CcsCKmw3U14QRDo9Ig5hfJhl3k

Let us know if anything works at all so we can try to troubleshoot your issue in a different way, however if truly none of the steps fix your issue there may be a very specific problem linked to your current system that we are not aware of, but I'm hoping this won't be the case.

**Comment by Jose-Moreno** [comment]
@PomfPomfMe If I may ask for an additional thing. Can you possibly record a small session of the issue? just exactly like you described testing the tablet with the pressure checkbox turned ON and the pressure checkbox turned OFF? I can recommend OBS for this task, but if you have any other software that's fine too.

Additionally maybe I can also ask you to try out the Pencil2D experimental branch that uses MyPaint as the brush engine, if this one works, then it might be a QT Framework issue with the current brushes.

This is a direct link to this specific build: https://drive.google.com/open?id=1BllqBX496jkNYvLJUuE90uvYAoWkrMm0

Mind you the animation stuff isn't fully ported or functional, but if the brush system works, then this can help narrow down the problem. Thanks in advance!

**Comment by PomfPomfMe** [comment]
thank you su much for ur help, i tried the admin and comparability with my ctl-490/w tablet and it works!!! the older one i have doesn't even have half the settings that you asked me to try

i have noticed that my old tablet is just garbage and old tbh, it was awesome back in the day but i think its time for it to go to sleep, thank you very much for ur help i can wait to animate !!!!

i dont believe there is any point in showing you the steps for the older tablet , half of which i cant even do due to my old tablet. just to show you how it doesnt work. i tried other(3) softs for animation and it also doesnt work. like i stated i am just going to trash this tablet its like 10 years old

**Comment by Jose-Moreno** [comment]
@PomfPomfMe Thank you for reporting back. It's a shame you have to get rid of the old tablet. Although I had a Genius 8x6 mousepen that is even older than that and it used to work with Windows 7, but to be honest the drivers from wacom barely cut it and with old models it's a certainly a pain.

If you have any other issues let us know, also just in case please be aware that Pencil2D currently has a file corruption issue for files that are too big under specific circumstances. 

The latest dev builds should have countermeasures for that but just in case please take a read of this guide meant to both help prevent and recover files that have suffered data loss https://discuss.pencil2d.org/t/pencil2d-project-file-corruption-prevention-partial-recovery-guide/3105

Other than that, our best wishes to you in your animation journey 🙂
