### ISSUE TITLE
audio problems while exporting

### ISSUE THREAD

**Issue by mineramirali** [pencil2d/pencil#1342]
### Issue Summary
when i export a project into a movie             randomly it will or it will not include the audio  
(most times it will not include the audio)
 

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@mineramirali Hi. Please fill properly the template so the developers can at least to know the exact Pencil2D version you are currently using as well as your current operating system version, and troubleshoot your issue based on this information.

Depending on the version and the operating system there are various problem that are already known related to sound.

From my point of view, most likely you've been using MP3's a lot, which have unfortunately a lot of issues due to encoding patents and there are problems with how they work during export, so we recommend that you try to convert all your sound files to WAV before importing them into Pencil2D.

Additionally if you cna please test the most recent development version of Pencil2D which had various fixes related to sound problems implemented recently, this way along the recommendation of using WAV files for new projects should minimize your issues significantly. 

We would appreciate if you could test several of your projects to see if the latest version helps exporting them properly and report back as well.

https://www.pencil2d.org/download/#nightlybuild

**Comment by scribblemaniac** [comment]
If you are using the current stable build, please try saving your project, restarting Pencil2D, and then exporting again.

**Comment by Jose-Moreno** [comment]
Closing as there was not further feedback from the user after 3 months. 

As a sidenote audio export problems have been fixed or otherwise improved in the latest release Pencil2D version 0.6.5. Please download the release or try out the current development version at http://pencil2d.org/download#nightlybuild and try again.

If you still have the same issue please comment so we can reopen this report.

**Comment by scribblemaniac** [comment]
As of v0.6.5, not all audio export issues have been fixed. However the only known serious issue can be fixed with the workaround that I previously provided here. It will be fixed for the next version.
