### ISSUE TITLE
Drawing with polyline on top of another vector stroke causes artifacts

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#1433]
### Issue Summary
While working on getting vector useable again for the mypaint branch, I noticed that the polyline is broken when painting on top of another stroke.

I already have a fix for this, I'm just creating the issue so we have something to tie the bug to. 

### Actual Results
While artifacts appear whereever the stroke touches or it's update area.

### Expected Results
No artifacts should appear.

### Video or Image Reference
![vector bug](https://user-images.githubusercontent.com/1045397/90610727-219f7180-e206-11ea-888f-52cf33b91caf.gif)

### Steps to reproduce
1. Draw a vector stroke
2. Draw a polyline stroke on top 

### System Information
Development Build Aug 19 2020 (master)

Operating System: macOS Mojave (10.14)
CPU Architecture: x86_64
Qt Version: 5.15.0

+ Operating System:
Mac OS 10.14.5

**Comment by Jose-Moreno** [comment]
@CandyFace I'm having an issue with the polyline tool where undoing the line will not update the canvas painter. After looking at this, do you think that issue is related to this one? or should I report it as an individual issue? I'm asking mostly because I saw your fix involves the canvas painter rendering.

The bug I'm having I can reproduce like this:
1. Draw a complete stroke with the polyline in the bitmap layer
2. Undo the stroke. You'll notice however that the stroke is still visible
3. Create a new stroke and you'll notice the old one will disappear (the canvas painter render is updated I suppose)

**Comment by scribblemaniac** [comment]
@Jose-Moreno This is a vector-only issue and fix, so the issue which you mentioned which affects the bitmap layer is something else and should be reported separately.

**Comment by CandyFace** [comment]
Indeed this pr touches only vector painting logic, what you're describing @Jose-Moreno  is another problem that needs to be fixed.

**Comment by Jose-Moreno** [comment]
@scribblemaniac @CandyFace Thank you for the explanation 🙇 I will report it separately then 👍
