### ISSUE TITLE
[BUG]  Windows panels are not *reset* when a new document is created

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1467]
### Issue Summary
When creating a NEW document (File > New), I was asked to save/or not a previous document in which I draw some lines and undocked some panels. So, when discarding those changes, the new document brings a blank canvas with the same undocked panels

### Steps to reproduce
Just open Pencil2D, draw some lines and undock some panels to a different position.
Create a new document (File > New). Select _Discard_ when the window _save/discard/cancel_ appear.
Result: the new document is created with a blank canvas but the panels remain undocked

### System Information
+ Pencil2D Version:
Built the last code from 11thSet
__
+ Operating System:
Win 10

+ Graphics Tablet:
HUION

**Comment by chchwy** [comment]
I suppose this is the expected behaviour?

**Comment by Jose-Moreno** [comment]
@chchwy @Kaikogf This is certainly expected behavior. Customizing the **_interface_** is different than customizing the **_document_**.

The interface level considers all the windows, panels and buttons that relates to Pencil2D as an application and how it behaves in your computer, but the document level includes everything related to the **content**, that is, the internal elements that make up a file of the project itself and how it behaves inside Pencil2D (the tool that modifies such elements). 

I honestly don't know any software that resets a user customization such as positioned interface panels, when creating a new file. Perhaps for convenience some might try to do this, but the most sensible thing to do is to respect the user customization.

For example, what if you're trying to work with two computer screens and want Pencil2D to keep the panels as separate windows between both monitors? I have used one window only as a canvas and another one one for looking at timelines with lots of layers. In such real-world case creating a new file would be hell as you would need to detach them over and over every time you start a new file.

**Comment by Kaikogf** [comment]
> I suppose this is the expected behaviour?

@chchwy 
I wanted to post it as a question. But I think I am going to close this since I am starting to think this is the expected behaviour as you mentioned it 👍 . I tested two other programs (painting) and they behave the same.

Any way...

**Comment by Kaikogf** [comment]
> @chchwy @Kaikogf This is certainly expected behavior. Customizing the **_interface_** is different than customizing the **_document_**.

That is what I thought @Jose-Moreno 👍

**Comment by Kaikogf** [comment]
I believe this is also not an issue 👎 

Closing it
👍
