### ISSUE TITLE
[QUESTION] Is it normal moving some frames while the remaining untouched moved  together to fill the empty spots?

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#1474]
### Issue Summary
I searched for a post with similar issues but didn't find any, but in case it is duplicated, let me know

The issue has to be with moving frames on bitmap layers.
Open pencil2D
go to frame 1 and draw "1" for easy reference. Go to frame 2 and draw "2" and so on till layer 8 (the more frames you go the crazy it takes LOL)
Select now layer 1, 3, 5, 7 (CTRL+LMB) and move them dragging the whole package to some frames ahead.
RESULT: the selected frames where moved correctly while the remaining frames moved together filling the empty spots left by the first one (is this a normal behaviour? If YES, then this post is duplicated to some extent since the result after checking the content of the frames bring us to the other post #1465)

### System Information
+ Pencil2D Version:
Last code from 17thSet

+ Operating System:
Win 10 pro 

+ Graphics Tablet:
HUION

**Comment by Jose-Moreno** [comment]
To answer your question: No, it's not normal. Dragging a keyframe should not displace another one
To answer if it's a duplicate: Yes I already reported this in  https://github.com/pencil2d/pencil/issues/882 so please close it.

As a related note, I have to ask you myself, for **questions** please use the forum or the discord server. If you're not sure it's a bug just don't raise the issue here. It's extra work for us 😅 

For your other issues I have tried to improve them so other developers can take interest in solving them, but also consider making the titles shorter. I know it's hard but it helps a lot since most of us use email or feed readers and long names are cut and easy to forget.

**Comment by Kaikogf** [comment]
I am closing it. 
👍
