### ISSUE TITLE
Selection in last git version his shifted

### ISSUE THREAD

**Issue by Popolon** [pencil2d/pencil#1485]
### Issue Summary
In current git version, when using  select tool (V), the selection is shfted some hundred of pixels toward right-bottom.
 

### Actual Results
selection isn't under the cursor
 

### Expected Results
Selection should follow cursor
 

### System Information
+ Pencil2D Version:

 

+ Operating System:
ArchLinux on x86_64
 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@Popolon Hi! Thank you for contributing with your report 😄 For new reports we like to encourage users to search first for potential duplicates in the tracker before posting or you can ask us in the forum or discord as well. 

This error in particular has already been reported here https://github.com/pencil2d/pencil/issues/1461 and it was under review. Due to this I'm going to close the current report and mark it as a duplicate so we can prioritize one ticket per issue 😃

If possible I'd like to ask you to consign your experience as a comment in the other issue so it gets activity and we can continue the follow up over there.
