### ISSUE TITLE
Tests - Permission Denied

### ISSUE THREAD

**Issue by AndyMender** [pencil2d/pencil#1542]
### Issue Summary
I am the new maintainer of the Pencil2D package for Fedora. As I was cleaning up the SPEC file, I wanted to add the test suite located in `<build_directory>/tests/bin/tests`. Unfortunately, I get the following error no matter what permissions are set on the `tests` binary:
```shell
+ chmod +x tests/bin/tests
+ ./tests/bin/tests
/var/tmp/rpm-tmp.cv16c2: line 36: ./tests/bin/tests: Permission denied
```
Oddly, this problem does not occur when building the package manually from the git source tree.
 

### Actual Results
Permission Denied on the `tests` binary.
 

### Expected Results
Being able to run tests as part of the package building process.
 

### System Information
+ Pencil2D Version:
0.6.5
 

+ Operating System:
Fedora 32 (targeting Fedora 34/Rawhide)
 

+ RAM Size:
32GB
 

+ Graphics Tablet:
N/A

**Comment by J5lx** [comment]
Hi, thanks for reporting! Since this happens only when packaging and regardless of the file permissions, I’d say it’s probably your build environment that’s interfering, but to be honest with the information in your report I can do little more than guess. The tests are primarily for development and I don’t think any other distributions run them during their packaging process, but I added them to the Arch package to see how it goes and there were no issues. Would you mind sharing the complete build output and the package source files you used so we can get a better idea of what’s going on during the build?

**Comment by AndyMender** [comment]
Here's a Koji build for Fedora 34/Rawhide: https://koji.fedoraproject.org/koji/taskinfo?taskID=56406396
It contains the SRPM and RPMs with the tests now enabled.

The current SPEC file submitted to Fedora is here: https://src.fedoraproject.org/rpms/Pencil2D/blob/master/f/Pencil2D.spec
Note that in this version the tests are still disabled.

I think the previous interference with my local build environment was only temporary (even though builds are executed in a chroot) as the problem no longer occurs.

I tried building Pencil2D from the SPEC file with tests enabled locally in `mock` for Fedora 32 and 34/Rawhide and I had no problems.

I will go ahead and submit a new revision of the SPEC file (with tests enabled) shortly.

**Comment by AndyMender** [comment]
Updates to the Pencil3D package were now submitted to Fedora.
Koji build for Fedora 34/Rawhide: https://koji.fedoraproject.org/koji/taskinfo?taskID=56406520
Koji build for Fedora 33: https://koji.fedoraproject.org/koji/taskinfo?taskID=56406933

There is an intermittent failure on Rawhide s390x builder machines, but it's not related to this project.

I think this ticket can essentially be closed.

**Comment by J5lx** [comment]
Good to hear the error resolved itself! I’ll close this issue then.
