### ISSUE TITLE
Adding sounds 

### ISSUE THREAD

**Issue by abvguess** [pencil2d/pencil#1570]
Issue Summary
 When I wanted to add a sound (not movie audio) it hasn't been adding. I used all the all of the methods for adding it. Though, it worked once, soon it deleted by itself and now I can't add audio.
 

Actual Results

So, after adding audio, only one key is creating (not full audio)

Expected Results

Added audio

Video or Image Reference

https://youtu.be/1aMOBtMppMo

Steps to reproduce

All the mentioned methods on forum

System Information
Version: 0.6.5
Operating System: macOS 10.16

**Comment by Jose-Moreno** [comment]
Hi. Thank you for your report 🙇 It is always advised to search for existing issues in github before reporting since this issue https://github.com/pencil2d/pencil/issues/1449 was reported already. Fortunately this and other sound problems have been fixed in the recent development builds since **January 4th 2021**.

Please read the [**Sound Import Guide**](https://discuss.pencil2d.org/t/guide-how-to-import-sound-into-pencil2d/5203) on our forum to learn about current **known issues** and their workarounds. At the **bottom of the guide** you can access the links to the development versions for all platforms, including macOSX. You can also download them in the [**Nightly Build download section**](https://www.pencil2d.org/download/#nightlybuild) on our website

Make sure to get the most recent one that has the following format: **pencil2d-mac-2021-01-30.zip** Note that these builds are meant for testing so while they are not perfect in general will be better than the release version.

Please review the nightly build and confirm if your issue has been solved so we can close this.

As an additional note, Pencil2D was not developed and has not been tested in 10.16 (Big Sur) so additional issues might occur to you that we have not found before. In that case we ask that you report them if you can. Thank you 🙂
