### ISSUE TITLE
Losing half The frames and audio background

### ISSUE THREAD

**Issue by CatlinCreeper** [pencil2d/pencil#1582]
### Issue Summary
I finished a layer for my sketch for a animation i was doing and did another layer for lineart, i was taking a break for a few times then i paused halfway through then Pencil2D crashed, i opened it back up again then i noticed when i was playing the animation i couldnt hear the audio, so i checked and it was gone. i thought nothing of it then placed it back, but half way through, where i ended the layer of lineart since i wasn't finished. the Low opacity sketch under it was halfway gone! the first half was fine, still shows my sketch and the lineart but After the lineart the layer of sketch after it was all gone, it still had my frames but it was all blank. i closed it and opened it but it didnt work, i turned my pc off and back on and it was still gone :( all that hard work was all gone. 
 

i lost half of all the drawings i did. i am extremely upset. What was the reason for the almost every 5 minutes auto save when all the Drawings i did was GONE. i am so upset and disapointed right now
### Video or Image Reference
![image](https://user-images.githubusercontent.com/79972678/109788773-9be78e80-7c4a-11eb-8d78-337b62d660b7.png)
this is the one where the sketch was gone V the lineart was the one left
![image](https://user-images.githubusercontent.com/79972678/109788881-ba4d8a00-7c4a-11eb-9698-c927a49905ae.png)

 

### Steps to reproduce
i was just drawing, casually pressing ctrl-z to undo my drawings then game crashed.
opened it back up Audio gone, half drawings gone.
 

### System Information
+ Pencil2D Version:

 

+ Operating System:
Windows 10
 

+ RAM Size:

 

+ Graphics Tablet:
Huion HS64

**Comment by CandyFace** [comment]
Hi CatlinCreeper

First, I'm sorry to hear about your loss of frames.

What version of pencil2D are you using, this information is crucial so please don't skip it.

Always make sure that you're using our latest release as some of the older builds had bugs in them that could corrupt the project structure and erase frames.

**Comment by CatlinCreeper** [comment]
It’s okay.. Uhm it says here Pencil2D v0.6.5

**Comment by Jose-Moreno** [comment]
@CatlinCreeper Sorry to hear about case. Currently there's recent release labeled as **version 0.6.6** you can get from the website. As a first step please use this new version from now on to get improved stability. Obviously there's no perfect software but we have yet to get reports of crashes from this version, so hopefully it will work better for you.

Related to your animation recovery, Pencil2D's new version also has a basic crash recovery feature which should allow you to get the files that were written to the disk before the crash. Usually this means that you saved prior the crash at some point, however Pencil2D can't recover files that were not saved at any point in time.

Additionally we have a **partial recovery guide** on our dedicated user forum with an emphasis on windows OS (however you can also try the steps on macOS or Linux usiong the **Help > Open Temporary directory** option)

This will guide you to your temporary file folder to locate any leftover resources that may have been stored on your computer before the crash and afterwards.

https://discuss.pencil2d.org/t/pencil2d-project-file-corruption-prevention-partial-recovery-guide/3105

While we can't assure you will recover all your work, since Pencil2D saves files from last to first frame, it is possible that you might be able to recover the second part of your animation, as long as some of it was saved to the mentioned temp folder.

For now let us know how it goes.

On the other hand if after getting the latest version you have another crash, please let us know in this same thread what you were doing and how it crashed. If you get a system warning please copy the contents of the error here so we can help better 🙇

**Comment by J5lx** [comment]
Hi! As Jose said, version 0.6.6 includes a number of improvements regarding stability and crash recovery. Since we haven’t heard back from you, I’ll assume the new version works for you and close this issue. If you are still experiencing instability or need help recovering files, please let us know.
