### ISSUE TITLE
Pen Pressure

### ISSUE THREAD

**Issue by NInaDoesStuff** [pencil2d/pencil#1583]
I'm using Pencil2d v0.6.6. I have a Wacom Intuos Pro and I'm using Windows 10. I have Windows Ink turned off, but my pen pressure still does not work in the program. I'm unsure how to fix this and would like some help.

**Comment by scribblemaniac** [comment]
Pressure in Pencil2D generally will not work with Windows Ink disabled. You can find a very good writeup about your options here: https://discuss.pencil2d.org/t/wacom-intuos-jagged-lines-windows-10/4963/3. Basically you will either have to enable windows ink for Pencil2D, or run Pencil2D in Windows 7 compatibility mode.

If this solves your problem, please close this issue. If it does not, please let us know what you have tried.

**Comment by Jose-Moreno** [comment]
@NInaDoesStuff Hi, one of the developers provided you with a guide on how to address this issue and we'd like to check if this worked for you or not. 

Please let us know soon if you still have difficulties after following the suggested procedure or not. In case you don't reply in the following weeks we'll close this ticket. If you continue to have the same issue however, we can reopen this ticket at your convenience. We'll be pending confirmation on this issue, thanks in advance.

**Comment by J5lx** [comment]
Hi, since we haven’t heard back from you I’ll assume you were able to get pen pressure working using the guide and close this issue. If it still doesn’t work please let us know so we can try to figure out what’s wrong.

**Comment by DearFox** [comment]
> Pressure in Pencil2D generally will not work with Windows Ink disabled. You can find a very good writeup about your options here: https://discuss.pencil2d.org/t/wacom-intuos-jagged-lines-windows-10/4963/3. Basically you will either have to enable windows ink for Pencil2D, or run Pencil2D in Windows 7 compatibility mode.
> 
> If this solves your problem, please close this issue. If it does not, please let us know what you have tried.

I encountered the same problem that pressing works in Windows Ink mode, but not in WinTab mode.

But your solution to enable Windows 7 compatibility mode causes problems
With Windows 7 compatibility mode enabled and Windows Ink disabled in the tablet driver settings (the same thing happens if you enable Windows Ink):
![0](https://github.com/pencil2d/pencil/assets/59219907/0d31b932-587d-43d3-b5fe-4b540abf241c)
The line when drawing is less smooth


Without Windows 7 compatibility mode and using Windows Ink
![0](https://github.com/pencil2d/pencil/assets/59219907/76212efe-ff35-417c-8e35-7e1211d3e559)
Smooth beautiful line

I'm using the latest build: Nightly Build 2024-04-29_17:31:48
