### ISSUE TITLE
Undo 2x = Delete

### ISSUE THREAD

**Issue by kippy470** [pencil2d/pencil#1585]
### Issue Summary
When I double tap undo or just press it two times in a close and similar fashion, My whole animation gets shut down and deleted, I've lost an animation storyboard and whole 300 framed animation to this. I am not sure if this was intended.

<!-- WRITE ABOVE THIS LINE -----

### Actual Results
The whole animation gets deleted after a moment of loading.

<!-- WRITE ABOVE THIS LINE -----

### Expected Results
It will delete two frames.

<!-- WRITE ABOVE THIS LINE -----

### Video or Image Reference
None since it deletes too fast to take a picture.

<!-- WRITE ABOVE THIS LINE -----

### Steps to reproduce
If this was intended you can leave it be. I'm no programmer, But I'm an artist and animator, so when in trying t quickly delete frames this is frustrating.

<!-- WRITE ABOVE THIS LINE -----

### System Information
+ Pencil2D Version:

0.6.6

<!-- WRITE ABOVE THIS LINE -----

+ Operating System:

Windows 10

<!-- WRITE ABOVE THIS LINE -----

+ RAM Size:

![image](https://user-images.githubusercontent.com/80468988/110802688-69dabb80-824c-11eb-983f-7f6da85f1b21.png)

<!-- WRITE ABOVE THIS LINE -----

+ Graphics Tablet:

pc only.

<!-- WRITE ABOVE THIS LINE -----

**Comment by Jose-Moreno** [comment]
@kippy470 Hi. Sorry to hear about your issue. Obviously such behavior is not intended, it rather sounds like a nasty bug that has not been noticed until now, unfortunately. That said if you want the developers to look into this issue it's important you provide more specific information.

Please let them know the following:
1. What version of Pencil2D you are using. FYI using any version below the recent 0.6.6 is not recommended, so if you're using an older one, you're expected to upgrade asap to have a base line for comparison.
2. What is you current operating system brand and version (eg. Windows 10 Pro, macOSX Catalina 10.15, etc)
3. Exactly what were you trying to undo, was it a keyframe? a stroke? importing something?
4. When you say "shut down" mean the program crashed? If so did you get a crash window?
5 When you say "deleted" you mean the drawings are blank if you open the file? or the file itself was deleted from the hard drive? Did you save at least once before committing to do 300 drawings? If so what happened with the last saved state of your file, can you open it?
6. Did you save any other file copy or did you keep saving to the same file? If so please as a recommendation save your progress in different files with suffixed numbers. e.g my_animation_001, my_animation_002, etc This is a common work habit since every animation software in the market, either free or paid, can crash. As a personal example, even by following this habit I still have lost a LOT of work to Adobe Animate CC 202X just in this year alone since it crashes all the time.

Anyway as an additional measure please take a look at the forum where we have a guide to help at least partially recover lost work from corrupted files. In the case that you file was not deleted please try the recovery methods mentioned here to improve your chance to recover part of the work https://discuss.pencil2d.org/t/pencil2d-project-file-corruption-prevention-partial-recovery-guide/3105

--- 

Another possibility is that If by an odd chance you never saved your file even once after you created the new document, and went on to work on the drawings, this could have led to the crash, since everything will be stored in RAM instead of Disk because Pencil2D does not know where you want to save. Autosaving only can kick in once you save the file to the hard drive at least once.

And so if the file was not saved, everything you did you be stored in the volatile memory. This is not a Pencil2D problem, this is how computers work, so even Flash or Harmony require you to save your work the first time, lest you want them to crash as well. I know this sounds obvious but you'd be surprised to how many people simply don't save the file when they begin working, even though there's a warning message that prompts them to save.

Either way, hopefully you can answer the questions above and read the guide in case there's potential to recover.

**Comment by CandyFace** [comment]
Hi

This issue might have been fixed via #1629, please try the latest nightly build and see if it has solved your problem
You find our nightly builds here:
https://www.pencil2d.org/download/#nightlybuild
