### ISSUE TITLE
Can't download vc_redist.exe

### ISSUE THREAD

**Issue by TheInzane** [pencil2d/pencil#1632]
### Issue Summary

 When I try to download vc_redist.exe it doesn't work/error

### Actual Results

 Got an error

### Expected Results

 Working and I can animate

**Comment by CandyFace** [comment]
Hi @TheInzane

The Issues section is for bugs related to pencil2D, not windows or packages that pencil2D rely on. If you want proper help regarding whatever issue you're having, come to our discord server or join our forum and we'll try to help you. 
https://www.pencil2d.org/community/

I will close the issue since it contains no information of value.

**Comment by Jose-Moreno** [comment]
@TheInzane For convenience to help fix any missing `VCRUNTIME140` DLL related issue, Pencil2D comes bundled with an appropriate vc_redist.exe installer in the download ZIP. As long as you've downloaded the correct version, you should be able to use it and fix the related problems that affect Pencil2D's use.

That said as mentioned in the previous comment, any further problem you have with the visual studio redistributable or missing operating system files is something we have no control over since these files are supposedly meant to be provided directly by Microsoft on their Windows operating systems. 

If you continue to have severe issues with their system we recommend contacting Microsoft's technical support directly as well.
