### ISSUE TITLE
It can't open the file so i can't save the file

### ISSUE THREAD

**Issue by thelegoplayer** [pencil2d/pencil#1634]
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@thelegoplayer Hi, this is a place to open tickets and report concrete errors for the program. To that end the developers require specific details to be provided in order to improve the possibility of finding and fixing the issue. 

Your report unfortunately lacks most of these necessary details so it will be a bit hard for them to provide you with proper assistance. Sometimes if you are not sure what's happening, it's better if you ask in the dedicated user forum at https://discuss.pencil2d.org to avoid getting bogged down by technicalities.

That said, going off by the title you wrote and since we don't have more information from you, i'll outline some possible problems and their potential solutions:
1. Your file was corrupted by an external source (i.e the software crashed, there was a blackout, windows or an antivirus interrupted the saving operation without you noticing).
  - **Possible solution**: To attempt recover of the file please visit our dedicated file recovery guide https://discuss.pencil2d.org/t/pencil2d-project-file-corruption-prevention-partial-recovery-guide/3105
  - **Advice**: Please always save multiple copies of a project file. Never save over the same file for a long time, particularly with large projects. Also if you're using Windows 10, please follow this guide to improve how the operating system treats third party apps, including Pencil2D https://discuss.pencil2d.org/t/guide-how-to-train-your-pencil2d-windows/4106
2. You saved the file as a different type of file.
  - **Possible solution**: The Pencil2D editor is only meant to work with project files in the PCL or PCLX format. It is different to SAVE & LOAD project files, that IMPORTING & EXPORTING image or video files. If by any chance you used the File > Save procedure but saved as a "movie", you might need to change the file format extension to PCLX
 - **Advice**: To properly output data from Pencil2D use **File > Export** to write images or videos to the hard drive. Saving is only meant for Pencil2D project files.
 
 I recommend you at least upload the file you can't open to a cloud storage website like Google Drive or MEGA and post a link here so the developers can at least review the file itself, otherwise there's little we can do to help.

**Comment by CandyFace** [comment]
It's been five days and there is no useful information provided here, so I'll close the issue. If it gets updated with proper information, then we can re-open and look into it.
