### ISSUE TITLE
Accidently but my timeline bar to low and now the taskbar is overlapping it and i cant use it, please find a way to fix this fast

### ISSUE THREAD

**Issue by JustAAnimator** [pencil2d/pencil#1660]
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
@JustAAnimator Hi and welcome. I'd like to let you know that this place is to place confirmed bug tickets. It's very important that you always try your best to describe what how and when you experienced the issue so the developers that review the ticket can reproduce it and fix it when posible.

With that said the way you describe your issue in the title seems like you're new to the software and might have not been able to explore all of it's features. 

Since you don't say which version you are using (usually required to be in the reports) I'll assume you are using version 0.6.6 which is the current default download on the project's website (https://pencil2d.org/download) 

As a **first step** to know if you are using this version you can go to the topbar menu **Help > About** command. However if you do find that this is not your current version, this will be the first step to fix your current issue.

![image](https://user-images.githubusercontent.com/4912907/131375575-2616c0f6-5774-487c-8c87-165a72f82926.png)

The **second step** is to go to the **topbar menu** and select the **Windows > Resets Windows** command. This will ensure that Pencil2D is restored to its default inerface layout.

![image](https://user-images.githubusercontent.com/4912907/131375515-699a9ad8-64bd-4198-8010-e6895c7586ca.png)

**Additionally** to avoid this from happening later on you can go to the **topbar menu** and select **Windows > Lock Windows** command. This will lock all the panels in place (including the timeline) to avoid the user accidentally misplaces the panels by using a trackpad or any input device.

In the future I kindly ask you to consider reserving placing tickets in this website to submit issues that you have confirmed with the project moderators and developers to be actual errors (we call them bugs) either by using the projects forum (https://discuss.pencil2d.org) or our dedicated support **discord server** For more links to the community hubs pelase visit. https://www.pencil2d.org/community/
