### ISSUE TITLE
vector layer filling and smudge

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#1678]
the filling tool in vector layer dosent work properly as when i need to make a figure which needs bone i  usually go to vector layer and use smudge tool in these cases it wont work properly
it goes other places where i dont want to fill 
i know pencil 2d focuses on hand drawn figures but if these can be solved it would be better that synfig or animate.cc
and try to make smudge tool to add more featueres like bones and others

**Comment by scribblemaniac** [comment]
Please be more specific than "doesnt work properly". Provide screenshots of what you're trying to fill, describe what you expect it to fill and show what it actually fills. On the vector layer, the bucket tool will fill the currently selected strokes. If it is filling more than you want it to, it is probably because you have extra strokes selected or you have not created a full-enclosed region to fill.
