### ISSUE TITLE
There's a bug reported on vector full, see attached image. This is operating as at should & is not an error!

### ISSUE THREAD

**Issue by AnimatorElisa** [pencil2d/pencil#1689]
![Screenshot_20220102-090018_Firefox](https://user-images.githubusercontent.com/79369348/149229107-c6b8eeae-7870-4f33-a54e-296d32369354.jpg)

### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:

**Comment by Jose-Moreno** [comment]
Hi. Thank you for your message.

The image you shared contains a list of **known issues** that is applicable for a specific **release version** of the software. That means it applies to only that version. When there is a new release of the software, the known issues will change accordingly.

For now the only issues I see on this image related to vector are still valid in the development version of the program. I even tested them again just now and they are still **not working as intended**, that means, it might work in some scenarios, but it's not an ideal outcome.

I'll explain why. When you draw a vector stroke it comes pre-selected by default (you can see a blue-ish centerline on the stroke). Using the fill tool on a stroke in this state will definitely change the stroke color and thickness. 

**However** if you de-select the stroke by using the selection tool and try to change the color of the stroke again, it will no longer allow you to modify it with the fill tool no matter how many times you click. 

**Unselected vectors cannot be modified by active tools**, that is simply a functional fact of the software.

Regarding the second vector issue from top to bottom, this is considered a bug because we want the stroke thickness variation to be preserved for strokes drawn with pressure sensitive equipment, and not become completely uniform unless the user wants  that.

Additionally we and other users don't want the stroke thickness to be changed **at the same time** when they fill a vector shape color, so this is also a bug (though it's not mentioned explicitly in your screenshot).

I hope this clarifies the complexity of this problem and explains why there is no mistake in the bug report. Good day.

p.s. We will look into clarifying the text, but it won't be removed since we can still reproduce the problem as explained above.

**Comment by AnimatorElisa** [comment]
Hi Pencil2D Team

Firstly I would enforcise that I have over 30 years experience using vector
based drawing packages on mini computers and PC's.

The vector fill operation works exactly as it should, and is definitely not
an error! All vector drawing packages from the first AutoDesk Animator to
the current Affinity Draw and Adobe Animator work in the same way as
Pencil2D Vector Fiil.

Remember each shape in vector mode is a separate sub layer within the
Vector Layer.

Therefore the first layer say coloured red, is overlapped by the second
layer, say blue. The over lap area has no meaning and therefore cannot be
independently filled.

This is on contrast to bitmapped drawings where shapes drawn on the same
bitmapped layer are intertwined and thus any overlap can be filled with a
different colour.

Try drawing two overlapping shapes using say Inkscape then attempt to fill
these shapes. You'll have to select the shapes to apply fills, like in
Pencil2D, and like in Pencil2D the whole selected shape will be filled.

The fact that all vector lines are visible currently in Pencil2D is
confusing, because with Inkscape etc the outline is hidden beneath the
overlying filled lines!

DIane Kivi

**Comment by Jose-Moreno** [comment]
@AnimatorElisa Thank you for sharing your experience. I understand you enjoy using Pencil2D's vector system, and you are trying your best to use it. 

I'm personally glad you have had a positive experience with this software, however I'm sorry to say that this has not been the case for a majority of confirmed users in the Pencil2D community.

Of course It's true that the vector drawing system may work on specific scenarios or use cases, it's precisely because of it that users like yourself have been able to create interesting artwork with the system.

We welcome that you consider the tools to be working properly for your specific workflow, but being able to use something in your own creative way, doesn't mean it will be applicable for a different person to use it the same way.

So it's important to understand that we want to provide _all potential users_ with a complete and improved experience moving forward, thus a set of new tools and workflows will be required to work practically in _any_ use cases we consider relevant. In that sense the current state of the vector system is not ideal for us, and this sentiment is shared by a big portion of the community from what we can tell.

However don't feel the need to share this view, or be swept by our or the community's opinion. Just as we have the freedom to present Pencil2D in a way we consider ethical for the community, you are free to use the software in any way you see fit. You could even consider modifying it and rebranding it to create your own animation software if you want.

As a team we will keep working on the software known as Pencil2D for as long as it is reasonable, but maintenance is different from innovation, and currently we are focused on the former due to our limited resources. It might take a _really_ long time before we can reach a stage where truly innovative development can take place.

In my personal opinion, I'm trying to be empathetic with your requirements and seeing your continued interest in the software, I honestly think you'll probably have a far more greater experience if you fork the project source code, rebrand it, and hire a skilled worker to develop a customized version of the application, in a way that your expectations and requirements are adequately met.

Quite frankly at the pace of development we are going, we may never be able to fulfil your expectations no matter how long it would take. So with utmost respect to you here's a guide on how to obtain and compile the source code (free) for yourself https://github.com/pencil2d/pencil/wiki

I wish you the very best with your endeavours, have an excellent weekend,

**Comment by AnimatorElisa** [comment]
Hi Morr

I've never used a vector package where I haven't had to apply work around's
to some extent.

In other words I've always pushed the packages very hard, to achieve the
results I require.

I see getting the required results as challenges not problems! Often these
lead to my best work.

I continue to be very impressed by Pencil2D.

Elisa Kivi
