### ISSUE TITLE
Glitching when used with Kamvas 13

### ISSUE THREAD

**Issue by Gizmo564** [pencil2d/pencil#1699]
### System Information
+ Pencil2D Version:

 

+ Operating System:

 

+ RAM Size:

 

+ Graphics Tablet:
When I try to use Pencil 2D with my Huion kamvas 13 the window zooms and becomes squished on my screen, all the text and buttons become dislodged from the ui and the software becomes virtually unusable. i can still draw but the timeline disappears and can't be found again.

**Comment by Jose-Moreno** [comment]
@Gizmo564 This is mostly a problem with the resolution used for the screen tablet itself. Most drawing apps suffer from this but it's not their direct fault.

What you need is to force Windows or your preferred OS, to bypass managing the app resolution, and let the software control it. 

First check this guide by Microsoft in their **Workaround** section on how to adjust the scaling factor for each monitor and how to change the compatibility for each app https://support.microsoft.com/en-us/topic/windows-scaling-issues-for-high-dpi-devices-508483cd-7c59-0d08-12b0-960b99aa347d

If that's not enough check the FAQ entry in the Pencil2D website that explains how to do this with some images. 
https://www.pencil2d.org/doc/faq.html#i-have-a-hi-dpi-screen--high-resolution-desktop-but-text-is-wonky--icons-are-too-small-in-pencil2d

The procedure is meant for fixing Hi DPi issues, but it also works for fixing mismatched app resolution (usually it's either text and icons are **too big** or rather **too small**)

You must also make sure the screen tablet resolution is adequate for their size. a Kamvas 13 screen tablet should have at most a 1920 x 1080 resolution, but it's possible that if you're using the "extended desktop" option to have the screen tablet as a second monitor, it needs additional configuration in your display drivers.

Lastly make sure you are using the latest version of the software which is numbered as `0.6.6` since the older versions had an issue that constrained the layout of the window "popping" off the timeline, so just having the latest version could improve your problem.

**Comment by Jose-Moreno** [comment]
@Gizmo564 Hi it's been almost an entire month and we haven't heard of your reply. 

I'm going to close this considering your issue is a most common problem where there's a mismatch between the main screen monitor resolution and your screen tablet resolution.

Said mismatch usually occurs when the main screen where the app was placed, is then moved to a screen space that has a resolution that's either higher (Hi-DPi screens up to 8K) or lower (Limited by hardware, like in a laptop) than the original screen.

Such behavior usually has to be corrected with the **display settings** from your OS; currently there's no other way.

High DPI support (due to Pencil2D icons and text appearing minuscule) can be tracked with #597 and #822 However in the case of lower resolution screens you are limited by your hardware and Pencil2D can at most adapt to XGA (1024 x 768) resolution before becoming unusable and having all the panels bloating the screen.
