### ISSUE TITLE
The eraser stop working

### ISSUE THREAD

**Issue by GalaxyWondersD** [pencil2d/pencil#1742]
When i try to erase something from the layer, it wont work.I double check if i was in the right layer but still it did not work.I even try to reset pencil2d and still does not work.

Here is proof:  

https://user-images.githubusercontent.com/119114590/204091325-5a910b11-6486-412e-8c41-cae57dd30f3e.mov

I hope u can fix this issue

**Comment by MrStevns** [comment]
Hi @GalaxyWondersD 

In order to help you we'll need more information.
Are you using the latest stable version 0.6.6 or a nightly build? if the former, could you please try the latest nightly build to see if it's fixed there.

**Comment by GalaxyWondersD** [comment]
at first i was not using the latest one but when i try the stable version, the eraser still does not work.


proof:
https://user-images.githubusercontent.com/119114590/204115486-5c044216-3edc-4ccf-932d-65f7ce757c66.mov

unless i did something wrong then, please let me know.If it is a bug problem please fix it.

**Comment by scribblemaniac** [comment]
@GalaxyWondersD Check the feather setting of your eraser tool. This can be found in the options panel which, since you have closed, can be reopened in the top menu by going to Windows > Options. The eraser tool (and brush tool) can appear not to be working if you have the feather set very high because its effect is very dispersed. This can happen accidentally if you have control (maybe command on macOS) held while trying to draw and you have quick sizing enabled (Pencil2D > Preferences > Tools > Use Quick Sizing).

**Comment by GalaxyWondersD** [comment]
When i check the preferences in macOS, it still wont work.

https://user-images.githubusercontent.com/119114590/205417884-58950752-946f-43ee-a287-c463e2ec72b8.mov

**Comment by scribblemaniac** [comment]
Please go back and reread my entire message. The issue is very likely the feather value of your eraser being set too high. Perhaps I was not clear with this, but the Quick Sizing is just a possible explanation of how you could have unintentionally got the eraser tool into this state. Disabling or enabling Quick Sizing will not affect your tool's current feather value. You need to reenable your options panel, and check that the feather is not set close to its maximum value.

**Comment by GalaxyWondersD** [comment]
Thank You for solving my problem😄
