### ISSUE TITLE
Pencil includes itself in "Sound & Video" menu categores

### ISSUE THREAD

**Issue by hughsie** [pencil2d/pencil#195]
In Linux, Pencil has a file pencil.desktop with "Categories=Graphics;2DGraphics;Development;AudioVideo;"

This means it gets put into the "Sound and Video" groups on some desktops, and _both_ the "Audio" and "Video" menus on other desktops.

Could you please either drop AudioVideo  to make it "Categories=Graphics;2DGraphics;Development;" or add AudioVideo  to make it "Categories=Graphics;2DGraphics;Development;AudioVideo;Video"

I don't think Pencil2D is really an Audio/Video program, and I don't really think it's a Development program either, although I 100% agree with "Graphics;2DGraphics;"

Comments welcome, thanks.

**Comment by Jose-Moreno** [comment]
@mapreri Sorry to bother you Mattia with a Pencil2D issue, but do you know how to change the category of an application in linux distros? Is it a problem of the source code or just how the distribution categorizes it? It's just so we can at least advance a bit with this issue. Thanks :smile:

**Comment by mapreri** [comment]
Well, it comes from the .desktop file, as the OP wrote.

pencil2d "ships" one from the util/linux-debian-packager.sh but I don't know who uses that script.  In Debian I added [my own .desktop file](https://anonscm.debian.org/git/collab-maint/pencil2d.git/tree/debian/pencil2d.desktop?h=debian/0.5.4%2bgit20170323.ec4712d%2bdfsg-1) (although I realize only now that I forgot to add a respective .mime file…)

**Comment by CandyFace** [comment]
I don't think the linux-debian-packager is used anymore? or it has been updated since then because nowhere does it say "Development;AudioVideo".

**Comment by J5lx** [comment]
I don’t have any idea where the categories named above come from. I searched for that combination on the internet but I didn’t find anything related to Pencil2D. Anyway I think it’s safe to say that this was introduced somewhere downstream. On top of that I recently introduced a [a more recent desktop entry](https://github.com/pencil2d/pencil/pull/671/files#diff-37648b414abdcad00bf7f64e37d08dfb) to the repo anyway as part of #671, which is now automatically installed when using `make install` on Linux. That entry is currently using `Categories=AudioVideo;AudioVideoEditing;Graphics;2DGraphics;VectorGraphics;RasterGraphics;Qt;
`. In other words, while there is no `Development`, it also uses `AudioVideo` without `Video` and IIRC the OP is right in that this can cause some shells to list the entry in two separate categories for “Audio” and “Video”. I could add `Video` to resolve this issue, unless somebody would prefer a different solution.

Other than that, I, too, believe that linux-debian-packager.sh is no longer used, and the same goes for several other scripts in util/ (namely linux-debian-chroot-setup.sh, macdeploy.sh and osx-app-packager.py) which have never really been updated ever since they were first added; at least some of them seem pretty outdated / obsolete / broken now. The debian and osx-app scripts in particular have only ever been used by the Morevna Project as it seems, and judging from their homepage they haven’t actively been working with Pencil for several years now. I’d suggest we remove the scripts named above to avoid confusion. Thoughts?

**Comment by CandyFace** [comment]
I agree, in general all useless files and such should be removed to avoid causing such confusions.

**Comment by chchwy** [comment]
Hey @J5lx 
I just took a look at the current .desktop file
```
Categories=AudioVideo;AudioVideoEditing;Graphics;2DGraphics;VectorGraphics;RasterGraphics;Qt;
````
The `AudioVideo` and `AudioVideoEditing` are still there. What do you think? should we remove them or keep them?

**Comment by J5lx** [comment]
[Quoting myself](https://github.com/pencil2d/pencil/issues/195#issuecomment-306255441): 

> I could add Video to resolve this issue, unless somebody would prefer a different solution.

After all, animation is also a kind of video, and I’d find it weird to include Pencil in the Graphics category but not in the video category, too. The question is whether we want it to be in audio as well (it’s not at the core of what Pencil is about but still lots of animation comes with audio, even if it’s just bgm). I feel pretty neutral about this, so I’d like to know what others think we should do.

**Comment by chchwy** [comment]
Alright. I'll keep the `AudioVideo` but remove `AudioVideoEditing` because pencil2d definitely is not able to edit audio or video.

**Comment by chchwy** [comment]
New categories are
`Categories=Graphics;2DGraphics;VectorGraphics;RasterGraphics;Qt;AudioVideo;Video;`

I'm closing this.
