### ISSUE TITLE
No pen pressure

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#23]
It works in 0.4.4, but broken now.

**Comment by OrangeBurrito** [comment]
Pen pressure is not working in Pencil2d v.0.6.1! works fine on other programs, e.g. photoshop (mac version)

**Comment by Jose-Moreno** [comment]
@OrangeBurrito Hi, we would require more information, so please answer the following questions:

1) What graphics tablet do you use? please state the brand and if possible the product reference number
2) What version of MAC do you have? (10.13, 10.8, etc)

If you are using a non-standard tablet from brands like HUION, Yiynova, Ugee, Genius, Monoprice, etc, you need to update their drivers first, even if it works fine with other applications chances are Pencil2D is unable to support them due to driver compatibility coming from the underlying framework that is used to glue the program together so updating to the latest drivers might help; it's not guaranteed though.

Also just in case, it's probably better that next time you open a new thread next time instead of commenting a closed issue, since this issue was for a very old version of this program.
