### ISSUE TITLE
[REQUEST] What about to match the Grid size to the actuall Window Render´s size?

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#235]
Last Nightly build December 9 2013
Win7 Ultimate, SP1 64bits

While working with an image that had its canvas initially zoom-out, I noticed that when exporting that image (File -> Export -> Image -> select a place and save it), only the image Inside the Grid was the one exported.
Of course, if I select the Camera-Layer and repeat the previous path, it will save the entire image.

I have read of the lack of boundaries for the final Render in Pencil2D, and may be this is part of the problem already written. But in any case, here it is what I experienced.

EDITED: and every time we change the size of the window render, the Grid size (boundaries) will readjust to it.

Thank you

**Comment by Jose-Moreno** [comment]
@chchwy This request is a bit confusing, but seems to be implemented as of Oct 10 Nightly Build. 

Grid size is properly being displayed when zooming in and out, and since the image export procedure was changed  the problem itself does no longer apply since you now are forced to export an image by selecting the camera size resolution and image encoding.

I suggest we close this.
