### ISSUE TITLE
probable memory leak

### ISSUE THREAD

**Issue by mikshaw** [pencil2d/pencil#253]
Here's something i never noticed before, but while working on my current high resolution project there appears to be a huge vacuum of ram. I've been working on a simple 1-layer 56-frame animation at 1920x1080. The only thing about this particular project that is different from my previous ones is the size of the frame. I'm not adding any more frames, nor am i increasing the complexity of the drawings by any significant amount, yet ram usage by pencil2d has increased to over 3gb in the course of a few hours. This happens both in the morevna 0.5.4 debian package and recent source from git.

Sorry i have no more specific information.

EDIT: RAM use jumped by about 2gb immediately after selecting and moving the contents of a layer, so maybe that helps a little. Last night that same action resulted in my desktop becoming essentially unresponsive (some very minimal but ineffective cursor response, and sporadic short bursts of audio from the music that was playing) for half an hour before i decided to just press the power button.

Debian Testing (jessie) 64bit
Intel i5 / 6gb ram / Intel HD 4000 graphics

**Comment by Kaikogf** [comment]
I can confirm this behaviour with the last build (Jan2018). 

Pencil2D was sucking 3,3GB of memory for playing an animation with several layers and 370 frames in the main one.

It is of very interest to have it improved since it is important to have Pencil2D smooth for all different types of animations, well not all for the moment but mostly for short-animations and middle-long animations
;)

**Comment by chchwy** [comment]
I'm on it.

**Comment by chchwy** [comment]
Checked again, no major memory leaks detected in the latest pencil2d, and the total memory usage has been lowered down when loading a large project.

Regarding the memory bumping up on select & move, that's because the current bitmap frame is backed up for undo operations. I can confirm it's not memory leak.
