### ISSUE TITLE
Camera layer rendering bug

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#266]
In “regular” Pencil, when switching to camera layer, all bitmap/vector layers are being drawn without “darkening”, i.e. same as they’d be drawn when exported. That was very useful.

Unfortunately, in this build, layers are still “darkened” in a way that corresponds to last selected layer, i.e. last selected non-camera, non-sound layer is being drawn on top.

http://www.pencil2d.org/forums/topic/camera-layer-rendering-bug-nightly-june-10-from-nightly-2k14-topic/

**Comment by Jose-Moreno** [comment]
@chchwy I think this bug is already fixed in the latest Nightly build ever since feeef fixed the camera rendering order. I can export images just fine without "darkening". If you find this to be solved please close the issue. Thanks :smile:

**Comment by chchwy** [comment]
Thanks, @Jose-Moreno.

**Comment by scribblemaniac** [comment]
This bug isn't completely fixed yet. The original post wanted nothing to be darkened when the camera layer is selected so they could see what the rendered result would look like, instead everything is darkened.

**Comment by Jose-Moreno** [comment]
@chchwy @scribblemaniac I think there's a problem of communicating what exactly the problem is then. As far as I understood the export was getting darkened pictures due to the camera layer. I just tested it out today with latest Nightly Build and I don't get my pictures darkened when exporting.

This bug was submitted before feeef coded the new camera rendering and order layer. Before the camera behaviour was that only when you selected your camera you would get the passe-partout / viewer frame to "preview" your canvas size. Now you see it all the time, since a lot of people complained that they didn't know what the canvas size was when they were drawing.

There was another commit that allowed the vignette to be turned on / off by toggling a button, but it was disabled and now you can only hide the viewer frame by turning off the camera layer by just clicking the circular button to the left of it's name.

I have the windows version, but if you say it still exists maybe it's a problem for the other Operating Systems? Maybe I'm not understanding this problem adequately, so can you share a screenshot of how it looks on your end? It might shed some light on this issue.

**Comment by scribblemaniac** [comment]
Maybe I misunderstood what this issue was talking about, I'm just going to file a new issue to avoid confusion.
