### ISSUE TITLE
[request] WebM, or Upload to Youtube

### ISSUE THREAD

**Issue by QMulative** [pencil2d/pencil#288]
Hey there.  I've enjoyed using Pencil on my Linux systems and am elated to know that development is continuing on a fork of it.  

https://www.youtube.com/watch?v=xU4nQuRw-e4

I'd like to know if there could be an option to export our creations to the WebM format, for its slim form and relative lack of patent encumbrance.  It'll make for easy uploading to sites like Youtube.  Alternatively, if it'd be possible to upload our cartoons directly to Youtube, that'd be just as good.

**Comment by J5lx** [comment]
Since this is now on the road for 6.1 it seems, maybe we should think about the codecs to use (i.e. VP8 vs VP9 for video and Vorbis vs Opus for audio, common combinations seem to be VP8+Vorbis and VP9+Opus). Particularly interesting here is browser support since WebM is one of the formats commonly used on the internet. [According to HTML5test](http://html5test.com/compare/feature/video.codecs.webm.vp8/video.codecs.webm.vp9/audio.codecs.webm.vorbis/audio.codecs.webm.opus.html), VP8 and VP9 are currently equally well supported among the most used browsers while Opus has a slight edge over Vorbis due to Microsoft’s new browser Edge. On that basis, it seems that VP9+Opus might be the best choice, but there might be more factors to consider as well. Thoughts?

**Comment by chchwy** [comment]
Did a quick test with `ffmpeg`. If I just tell `ffmpeg` to export a webm video without any parameters, it will use VP9 & Opus. As I know, youtube use VP9 & Opus as well.

**Comment by chchwy** [comment]
Hey @QMulative 
Export to a webm format video has been added. (VP9+Opus codec)
Please check it in the nightly build 11 Dec 2017 
http://pencil2d/github.io/download/

There is no plan to do a Youtube uploader at the moment.

**Comment by QMulative** [comment]
Great!  I'll be sure to try it out as soon as I can
