### ISSUE TITLE
I get an error trying to install pencil2d deb on Ubuntu

### ISSUE THREAD

**Issue by paweljonik** [pencil2d/pencil#297]
On Ubuntu 14.04 64bit i get this when installing Pencil2d from deb file:
dpkg: error processing archive Downloads/pencil2d_0.5.4-20130728.1_amd64.deb (--install):
 trying to overwrite '/usr/share/applications/pencil.desktop', which is also in package evoluspencil 2.0.5.

Obviously, I've got evoluspencil (http://pencil.evolus.vn/) package installed as well which uses the same name for some of its files (e.x. pencil.desktop & probably more).

**Comment by mikshaw** [comment]
They were supposed to have fixed this already, as far as i know.  In any case you can probably move one or the other to an arbitrary location and run it from there. If the version you have installed is based on 0.4 then it should be even easier, since it was just one file...copy the pencil binary (/usr/bin/pencil) to wherever you want it, uninstall pencil, then install pencil2D.

I have no idea what the evolvus version is, why it's listed as version 2.0.5, or why it's called pencil. The name at least should have been changed, and personally i wouldn't trust any project that doesn't know enough to do that. In fact i think it's a license violation.

**Comment by mikshaw** [comment]
The more i look at that evolus website, the more i think there's something wrong with it.

"Beside the option to use GPLv2, Evolus also provides Pencil source code under a commercial license in which licensees can obtain the source code, modify it and integrate it into their own commercial application without the need to re-publish any of the code in the terms of the GPL."
I don't believe the GPL allows that except when the licensor is also the author of the code.

**Comment by paweljonik** [comment]
@mikshaw interesting. I haven't had time to dig that deep into it - I remember it was taken over at some point of development by someone else few years ago AFAIR & then there were some name missmatches. 

But still - the licensing issues you mentioned doesn't help this app at all...

**Comment by mikshaw** [comment]
There was a name conflict between binary packages of the original Pencil (website just recently deceased) and the binary packages of Pencil2D--the package name was changed and the binary wasn't--but the Evolus site looks like it's unrelated to both packages.  As I said I'm completely unfamiliar with Evolus...maybe it was known from the original Pencil forums, which i had visited only briefly before Matt started this fork. For all i know, maybe the Evolus project is fully legitimate, but it seems very suspicious to me. I have heard of softwares that are released under multiple licenses as well as GPL, but this is a situation where a *fork* of a GPL project is being released under multiple licenses...very unusual, and suspicious. It's possible that Pascal & Patrick gave Evolus special rights outside the scope of the GPL, but that's a difficult conclusion to draw, particularly since the inactivity of the original project.

Addressing your problem again: Have you considered building from source? You're here at github after all, which is where the source is made available, and a simple qmake and make (with the necessary build environment installed) will build a working Pencil2D that is separate from whatever binary you also install.

**Comment by paweljonik** [comment]
I played with compiling anything from source a long time ago - definitely have to go back to it ;-), but for now I just digged into the Pencil2d deb file, modiffied the filenames here & there and packed it back to install & test it out quickly as I had just few nights to learn to animate in 2d under linux for one project.
I'll surely get back to it - looks promissing!

**Comment by mikshaw** [comment]
I would say Pencil2D is among the simplest, if not the simplest, for creating basic 2D animation in Linux. There are others you can experiment with, though:
Tupi -  http://www.maefloresta.com - vector animation, still very basic set of tools.
Synfig Studio - http://www.synfig.org - probably the most advanced, but also the most frustrating in my opinion. Raster (bitmap) animation is not quite there yet.
Blender - http://www.blender.org - with the 2.73 release you can now do 2D frame-by-frame animations with the grease pencil. The drawing tools are extremely limited, but this is the only open source program i know of that can do audio-video sync in 2D animation.

**Comment by paweljonik** [comment]
Thanks @mikshaw for suggestions! I was looking for something to animate UI mockups. I use Blender for 3d modeling but was frightened by the amount of functions related to animation there, so I went and tried Synfig. It's pretty tough too, annoying sometimes & often unstable but it did the trick.
But I wish I knew Tupi - it looks pretty simple & may be exactly what I need! I'll give it a try.

**Comment by tasaif** [comment]
Duplicate #396
