### ISSUE TITLE
[Improvement] Add function to insert / delete / duplicate frames

### ISSUE THREAD

**Issue by jensenr30** [pencil2d/pencil#320]
First, I want to thank all of the people who have worked towards making this program better and better. I'm amazed that this software exists and is free.

Second, I want to express how amazed I am that I cannot insert, delete, or duplicate frames. The frame system seems very static. It would vastly improve my workflow if I could move frames around on the fly.

**Comment by Jose-Moreno** [comment]
@jensenr30 Hi. I'm sorry to bother you as I'm sue you no longer use this program. However I wanted to let you know there's now an add, duplicate and delete frames function in the latest code as well a new "multiple frame selection" function where you click and drag over the frames first, and when they are tinted with dark-grey, you can then click and drag the stack over.

We now are able to insert / duplicate frames and any point in time and between existing keyframes. The system however works so you can duplicate any existing keyframe or add a new frame, but the new frame container will be moved to the next possible open space. 

So for example, lets say I have 3 drawn keyframes on frame 1,2,and 3. I want to add a new keyframe. If I press the add / duplicate frame, the new empty container will be sent to the fourth frame, because it's currently the next logical open space in the timeline. However If i drag select frame 3 and 4, move them over to frame 4 and 5 respectively, I can select frame 1 and add a new frame inbetween them, either a duplicate or a new empty keyframe.

I would argue tho that we need to do this automatically, so following the previous example, If i'm on frame one, and press add or duplicate, it should automatically insert it next to the one that is selected instead of creating it there.

If you want to test the functions I'm speaking of, please download the newest Oct 10 2016 Nightly Build here:

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

**Comment by Kaikogf** [comment]
@Jose-Moreno 
I think this issue can be closed since the TimeLine was improved with those features referred by @jensenr30.
 
[A note: About your last words, when you say that we need to do this automatically, you may create a different Issue as "Request/Enhancement" for additional functionality]

**Comment by chchwy** [comment]
I'm closing this since all issues have been fixed
