### ISSUE TITLE
Lots of bugs....

### ISSUE THREAD

**Issue by M1dnyght** [pencil2d/pencil#323]
First off, if I have been drawing or animating for a while my paint bucket will glitch up and be unable to access. Plus this feature (paint bucket) isn't usable in vector image, the colors won't change and if they do so, it is no color previously clicked upon. Also when using paint bucket and the pen tool with the same color they appear different, it has me struggling to repeat designs in differing layers. On the contrary, I would like if you added in a free form version for the selection tool, and maybe an option for blurring. If anyone could help me unglitch the paint bucket, help would be appreciated, I quite frankly would like to finish my YouTube video before July..

**Comment by hellocatfood** [comment]
Can you report each of your issues as a separate bug report/feature request?

**Comment by JonasThomas** [comment]
@M1dnyght 
There there many changes and fixes since your bug request has been submitted.  These issues may have been addressed.  
When you submit a bug request it should really be one issue for one problem so the developers can focus on it.  
If you you are still having problems with the issues you've mentioned   or any new issues for that matter, please bring them up on the forum first.  @Jose-Moreno has been doing a nice job keeping track if we have if we have a unreported problem or if it's duplicated problem.
I'm closing this request, but as I said if you're still using pencil2d and are finding unreported bugs we want to here about them.
