### ISSUE TITLE
Error importing anything from the importing option (Menu File)

### ISSUE THREAD

**Issue by ghost** [pencil2d/pencil#35]
BUG
Last build

An Error occurs when I try to IMPORT anything from the importing option under the FILE MENU
ERROR: a window with the text "please select a bitmap or vector layer to import"

**Comment by Jose-Moreno** [comment]
@tasaif I tested this on v 0.5.4b and everything works. It seems the UPPERCASE / lowercase problem was fixed. In Nightly Build JAN 15 2016, things work as well but file formats were limited to png, jpg and bmp while exporting. And some imports give warnings whereas the previous version didn't.

**VERSION 0.5.4b** 
The following file formats had problems with different import / export choices:

**Export Single Image:**
*.gif (this one actually gives an warning )
[Unable to export single GIF image error warning](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/gif-single-image-export.jpg)

**Import Sequence:** 
**.TIFF (*.TIF)**
**.BMP**

The files previous file formats are parsed as seen in the debugging window for version 0.5.4b 
![0.5.4b debug window](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/debug-window-file-parsing.jpg)

And the playback indicator goes to the actual frame that represents the total amount of image files, But nothing is imported:
![Timeline playback indicator moves](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/parse-timeline-playback.jpg)

**.GIF** for animated gif files, pencil2D only imports the first frame.

**Export Sequence:**
**.GIF** When you export an image sequence you have to select where you want to export and you choose the filetype

[Export Image sequence first filetype choice](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/first-export-type-choice.jpg) 

Later Pencil2D gives another options dialog to "encode" it to png, jpg, bmp or tif. 
![Export Image sequence secondary Encoding](http://www.pencil2d.org/wordpress/wp-content/uploads/2016/02/export-image-secondary-encoding.jpg)

What this did was that you ended up with, for example a png file format that has a TIF encoding on it's name, plus the numbering ends up being put after the format if you don't export while selecting the camera layer.

**JAN 15 2016 Nightly Build for Windows**

Exporting now forces the user to select the camera layer always before exporting (whoever thought of that good job!)

The reported 2013 behaviour was fixed. And the "encoding" problem from version 0.5.4b was also fixed. So now you get the options dialog before telling the program where to save the image sequence.

But the export file formats for image sequences was reduced, now you can only export to png jpg and bmp.

Using still image import option, you can now import animated GIF's which fixes the previous related problem. If you try to force-import an animated GIF with the image import option using *.gif* on the name prompt to search for .gif files that are not within the scope of the explorer, it will only import the first frame, but since it's restricted to jpg's, bmp's and png's for now, I don't think it's a real problem.

I didn't test force-importing image sequences from different file formats that weren't initially supported (like .TIF(F), or .XMP) if that is required i'll do it for a new case.

These are my findings, so I think that unless more evidence shows up from other users we can close this issue for now.

**Comment by tasaif** [comment]
Thanks for testing this you're a credit to the force

**Comment by Jose-Moreno** [comment]
@chchwy I think we should close this, as I commented earlier this year and checked this was working as of JAN 15 2016 Nightly Build.
