### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AngelicilySweet** [pencil2d/pencil#384]
Hi! So the pencil program always crashes when I try to import audio files. (I use a mac) I've seen the forum on bugs and the whole thing with downloading the file "4.8.5-VC2010" or something like that, but the problem is, it doesn't work. For one thing, the instructions said to rename the file from "C:***" and that the "C" stands for the folder it is in, but, when I download it on my mac, it doesn't even show up in a folder. It just shows up as one file... I don't know what to do, and I would really like some help on this!
Thank you!

**Comment by Jose-Moreno** [comment]
Angelicily, I'll be honest ever since a few years back Pencil has no real stable support for audio. The fix you read on the forum is for Windows only, and even so, it doesn't always work, particularly with pencil2D versions that are different from 0.5.4b.

The only thing we can do right now is to find a MAC developer who is willing to assist us into fixing and testing this under the newest OSX available. My only recommendation at this point is to use another open-source software alongside Pencil2D.

For example you could export your animation as a PNG sequence from Pencil, then import it into the video editing editor inside Blender (www.blender.org) where you can also import sound no problem. The advantage of this is that, if you overwrite your PNG sequence, it will update over Blender after pressing a button. You can also scrub the audio there. If you require an in-depth explanation let me know over the forums and I'll gladly make a quick tutorial for you.

I know this is not ideal, but for now is the best piece of advice I can give you meanwhile we manage to fix the audio issues inside Pencil for every OS.

**Comment by AngelicilySweet** [comment]
Thanks for the quick reply~

**Comment by chchwy** [comment]
Fixed in Nightly build July 1 2016. Could anyone check for this?

**Comment by Jose-Moreno** [comment]
@chchwy It's late here, but can confirm that July 1 Nightly Build DID NOT CRASH when importing the following files:

1) Type: WAV
Duration: 00:11 seconds
Bitrate: 88kbps
Size: 126kb
2)  Type: WAV
Duration: 9:30 mins
Bitrate: 1411kbps
Size: 95,9 mbs
3) Type: MP3
Duration: 19:02 mins (I'll talk about the duration limit of sounds, as related to another file I couldn't import due to this, in the bug report)
Bitrate: 320kbps
Size: 43,5 mbs

There were some other bugs and important issues that need to be resolved for the sound layer to be usable for animation, but as base functionality goes, sound import / playback IS working in Pencil2D with this new Nightly Build :) Great work!!!

Do you want me to make a report with the bugs I observed and do a separate report on what is missing for the sound functionality to work as expected, since that could sound like feature requests but they are actually critical components of any program with sound capabilities.

**Comment by chchwy** [comment]
Please made separate reports for other problems.
I'm glad to hear about your feedback, thank you @Jose-Moreno
