### ISSUE TITLE
Bug when drawing after moving bitmap objects with select and move tools

### ISSUE THREAD

**Issue by ManuAros** [pencil2d/pencil#385]
1. Start fresh Pencil and draw something in frame 1
2. use select tool to select the object you drew
3. use move tool to move the object to a new location
4. Add one frame
5. Use pen tool to draw something in the new frame (2)
   and you will se that what you draw will be moved to about the same place 
   as you moved the object in frame 1

Comment: same behaviour even if you start with making two frames.
Comment: I don't see this behaviour on vector only bitmap layers

Tested on 32 bit Windows 10, Pencil2D Dec 19 2015 Build.

**Comment by feeef** [comment]
This is one of the main bugs of the current build. It is very annoying. jonasthomas from the forum said he would have a go fixing it.

I have implemented the current transform feature so I can help understand how that works.

- The select tool is used to select
- The move tool is used to handle the transformation of the selecton
- The ScribbleArea handles the transformation at the BitmapImage / VectorImage level
- For a bitmap image (the problem is here!) the transformation display is generated by the CanvasRenderer (called in ScribbleArea paintTransformedSelection()). This is just a temporary display. It must be applied or canceled. If we go back painting or if we go to another frame without applying (deselect) or canceling (esc key) the transformation (ScribbleArea applyTransformedSelection() / cancelTransformedSelection()), the CanvasRenderer doesn't "switch off" its transformation mode.

**Comment by ManuAros** [comment]
This can now be closed, tasaif fixed this issue.
