### ISSUE TITLE
Camera boundary.

### ISSUE THREAD

**Issue by tclancey** [pencil2d/pencil#488]
I might be missing something, or being a bit dim, but when on a bitmap or vector layer, why can't I see the boundary of the camera lens?  

I understand the idea or creating new camera positions, zooming, rotating etc.  But I can't get my head around an unlimited canvas, but not knowing where the camera is.  Could there not be a bounding box type border displayed?

**Comment by tclancey** [comment]
PS, I don't have a button in the Display Options for the camera border.  v0,5,4 dev

**Comment by Jose-Moreno** [comment]
@tclancey Hey, this was a design impediment (not really a bug persay) in build 0.5.4 dev. However ever since **it has been implemented in the Nightly builds** which are the experimental / development versions, but for whatever is worth, they are indeed the newer versions of Pencil. We have been allowing people to download the 0.5.4 dev because it's somewhat the most stable version, but it has several shortcomings, such as the one you describe.

Please try to download the latest **Nightly build** to see what has been fixed, and what is "in the works" you can fin them in the first port of this thread: [www.pencil2d.org/forums/topic/pencil2d-nightly-builds-2015/](www.pencil2d.org/forums/topic/pencil2d-nightly-builds-2015/)

**Comment by Jose-Moreno** [comment]
This has been implemented through these efforts #332 #334 #408 #485 So if you find this issue solved, please close it :)

**Comment by chchwy** [comment]
Close issue.
