### ISSUE TITLE
Win build crashes when moving selection

### ISSUE THREAD

**Issue by Kerlasia** [pencil2d/pencil#495]
To reproduce:
1) Draw something on a frame.
2) Select the drawing with the selection tool.
3) Select the move tool, and use the arrow keys to move the drawing to either the right or left.
4) When the drawing moves a certain distance, the following things may occur:
- The drawing will disappear. It will only reappear when you move it back to the exact position it started in.
- The entire canvas will disappear, leaving only the grey background of the window.
- If any click or keypress is made in this state, the program crashes.

This is very annoying, as I need to create a scene in which the character pans across the stage.
Is there an alternative way of handling this besides using the move tool and physically moving the drawing? Thank you in advance.
EDIT: Found out that a camera layer can be used for this, however, I still would like to be able to move objects without the program crashing.

**Comment by Kerlasia** [comment]
It also crashes any time I save... Not sure if this is only on my end or what?

**Comment by sumitmak** [comment]
Some questions to verify if what you're doing is correct or not.
Firstly, are you using the latest nightly build version or the default download version 0.5.4 something?
Using the nightly build is preferred(not recommended yet) as it has some good tweeks.

Secondly, are you trying to move the drawings using the move tool on the same key frame or different one?
I drew some rubbish things and selected it, and then using the move tool, I used the mouse to move the image on the same keyframe, there was no crash for me. I even zoomed out to infinity and kept moving until I could hardly see my drawing and I lost it somewhere in the grey zone -_-

Thirdly, If you are indeed moving the image on another frame, then once you have move, make sure to click somewhere on the canvas to deselect the drawing, as this will confirm the new position.

**Comment by Kerlasia** [comment]
Hi, thanks for the quick reply.
I am using the 0.5.4 version, so I will install the nightly build instead (a friend also experienced the same issue on 0.5.4).
That version seems to crash very often for a variety of reasons (mostly unknown) so I'm not sure, but it happens while moving objects on any frame (same or different). Also, the bug is best recreated using the arrow keys to move the selection. It has occurred when using the mouse as well, but mainly the arrow keys.

**Comment by sumitmak** [comment]
Yea, that's like an ancient version so its quite buggy, try using the polyline tool and you will get the picture. lol
Anyways, you don't need to install the nightly build, just unpack the zip file and directly use from it. There are a lot of improvements that you will notice. I myself have uninstalled the 0.5.4 version and sticking with the nightly build until the devs release the "secret" 0.6 version in the near future.

**Comment by Jose-Moreno** [comment]
@Kerlasia Thanks to sumit for the assistance. This is similar to a previous report which had to do with the selection tool and was causing a display glitch. This was fixed already, however the crashing part is new so it would be worth investigating depending on your version. Also when reporting let us know your Operative System as well.

Indeed the Camera Layer can be used for panning, in newer version since devs are still testing stuff the automatic interpolation for the camera layer was disabled, but the selection tool works now.

If you want to download a suitable nightly build please take a look at our new download page and follow the proper links: https://pencil2d.github.io/download/

**Comment by chchwy** [comment]
Hi @Kerlasia 

Thanks for submitting the bug.
I believe this bug has been fixed in the recent 0.6 version.
If you still like to use Pencil2D please try it here: http://pencil2d.github.io/download/

I'm gonna to close this issue and don't hesitate to contact us if you get anything else wrong.
cheers.
