### ISSUE TITLE
Can't login to the forum

### ISSUE THREAD

**Issue by feeef** [pencil2d/pencil#500]
It has been a few weeks since I logged in to the forum.
I tried this morning and got a 406 " the request is not acceptable" response from the server.

Thanks for your help!

**Comment by Jose-Moreno** [comment]
@feeef Hey man, apparently it is related to this post gordie made on the forum http://www.pencil2d.org/forums/topic/bruteforce-attacks/

We've still had lots of spammers lately as well so this is not going well. I don't understand why people are so adamant on fucking up a non-profit software like Pencil2D :(, I mean they could use their programming skills and help us finish the god damn software faster instead of trying to hack the site...

Anyway we've all been really busy so I hope at least you're doing good in health and life itself. Take care!

**Comment by gordielachance** [comment]
I think it's because they are bots...  It's not "personal" :)
Well, it should be fixed by now.  Added some more security.  You should be able to login !

**Comment by Jose-Moreno** [comment]
@gordielachance Although this Fahima Faruzi botgirl has re-registered in the last 2 hours again.
http://www.pencil2d.org/members/fahimaferu/

It's one of the many that have been reported to send spammy private messages with an email to contact them (and possible extract your information)

**Comment by feeef** [comment]
Merci @gordielachance ! :)
I managed to login! :)

I agree with you @Jose-Moreno , It would be cool to see all this programming energy to be used for the public interest building freedom, but not everyone thinks this way.
So, never mind if they are annoying, it doesn't prevent us to go forward and I am happy to bring my little tiny stone to public freedom! ;)

**Comment by chchwy** [comment]
Excuse me, I meet the same problem, how do you login to the forum?
