### ISSUE TITLE
0.6 Release Plan

### ISSUE THREAD

**Issue by chchwy** [pencil2d/pencil#505]
@feeef @Jose-Moreno @gordielachance  

I have a little free time recently, maybe it a good timing to talk about 0.6 release.
There are three main issues that i will focus on:
1. sound layer 
2. movie exporting
3. translation

I am also going to fix the issues marked as milestone 0.6
https://github.com/pencil2d/pencil/milestones/0.6
(please tell me if I missed any urgent issues)

I plan to release 0.6.0 as soon as possible, maybe in 2~3 weeks after I solve all the major problems, and start to solve other bugs in the following small patches 0.6.x

I have already started my working yesterday, I will continuously update my progress.

**Comment by feeef** [comment]
Thanks a lot @chchwy !

I will too have some free time for Pencil in June and I will keep focusing on the MyPaint implementation (which should be our 0.7 release).

**Comment by Jose-Moreno** [comment]
@chchwy @feeef  Thank you Matt. Glad to have you back, I know we've all been really busy these days. 

Yes I think those issues have been the most requested for a lot of time, particularly the first 2.

However I want to also bring to your attention that I've had several reports related to a memory leak, or something similar that "corrupts" the pencil files as well as the single image files located in the data folder, becoming literally unusable. It seems this is a problem when memory isn't enough (using more than 200 frames or so)

This is something that has been detected ever since version 0.4.b and it was somewhat fixed in 0.5.4 but it's still a source of immesurable frustration to several users, which has even prompted them to bad mouth the program as an "unusable piece of shit"

Hence I propose that once these priority fixes are done, we also focus on finding these memory and segmentation fault bugs which are critical for the program operability and stability.

Regarding the MyPaint, thanks again Francois for your hard work. I'll stay alert for anything I can do to help.

**Comment by gordielachance** [comment]
HI guys, that is very nice to have news from you,

It's the first time I read about roadmaps here, and I guess this is a sign
of maturity for this project :)
I know I'm not always available but I do my best to keep the website up.
There were a lot of problems recently, but I think things are going better.
As I already said on the forums, I had a new theme in development but
hadn't the chance to work on it recently.

Well, let's join our forces :)
Thanks for your work.
Please tell me if you need anything !

Gordie



2016-05-24 20:21 GMT+02:00 Morr <notifications@github.com>:

**Comment by Jose-Moreno** [comment]
@chchwy I also forgot to mention, si there any way to get a 32bit version of pencil2D along with the current 64bit version? a lot of people have been complaining about not being able to use Pencil2D because they have a 32bit OS.

**Comment by chchwy** [comment]
No problem @Jose-Moreno, I will release next nightly builds for both 32bit and 64bit!

**Comment by chchwy** [comment]
OK, now the translation and sound layer are basically done, except bugs are found :p
I'm going to work on exporting issues next.

**Comment by hankofficer** [comment]
@chchwy Good job. :+1:

**Comment by chchwy** [comment]
Just keep you all posted.
Movie export works on Windows now, and I will upload a nightly build tonight.
Next things is make it works on Mac/Linux.

**Comment by Jose-Moreno** [comment]
@chchwy Fantastic Matt! thank you for all the hard work! :)

**Comment by feeef** [comment]
Beautiful @chchwy ! :) You are amazing!

**Comment by chchwy** [comment]
https://github.com/pencil2d/pencil/milestone/1

**Comment by Jose-Moreno** [comment]
@chchwy I think many elements have been greatly improved ever since last year that were beyond the scope of the initial plan. Regarding the points:

1) The **sound layer** you implemented is working and has been improved over time. For which we also really have to thank @martinvanzijl for his contributions as well.
2) The movie export is working great so far as well as the GIF import/export. However I don't know if we should include #681 into the milestone though, considering @J5lx was working on it already, or leave it for the next "release". Thoughts?
3) I think you already fixed many issues with translations during last year and the beginning of 2017. There is one thing though, since many features have been implemented or changed since last year, all the OneSky translations have become dated. For example the Spanish language needs to translate all the new terms, and other languages share the same fate.

The memory leaks from #520 have been difficult to replicate, but I think we have a much more robust and stable program than what we had one year ago and that is a remarkable achievement.

I think think we should begin to use Github's version release scheme to centralize the downloads as I suggested on #560 

Last but not least, re-implementing the camera interpolation is not an easy task, so I don't know if we should post-pone that for the next release, or if we should keep it for 0.6

Once release date nears, I'll try to communicate with most open-source news outlets I can, to see if they would help out on spreading the news as well as our plan to monetize selective task development, so people both users and developers can have an incentive to contribute to the future of Pencil2D.

Thanks for all the hard work! we're finally near the milestone!

**Comment by J5lx** [comment]
As for the movie exporter rewrite, I think I *might* be able to get it working (and get it working *well*) until the deadline if I really concentrate on that task, but nonetheless there are still some parts left that I haven’t gotten to that could be anywhere from “easily doable” to “quite tricky”. And then we also need to think about testing, since not all Pencil2D users are running Arch Linux, and especially not with my setup. In the end it might not be impossible but I’m not sure whether rushing this in before the deadline is worth the effort.

Also, speaking of translation issues: Personally, one of my biggest problems with the translation infrastructure is OneSky. It’s slow, it has no glossary (aka term base) and no concordance search (aka TM search), it’s filtering mechanism is extremely limited and doesn’t even support more than one filter at the same time, it seems to automatically generate arbitrary, sometimes confusing character limits, and lastly it isn’t even possible to translate strings offline with a better program and then upload them all at once (at least not for me as a translator, I bet the project maintainer can upload files freely). Especially the lack of glossary and concordance search is a real deal-breaker for me since those are fundamental tools for producing consistent, high-quality translations. It would be great if we could find a solution that doesn’t have those shortcomings. Here are possibilities I see:

- Find a way to magically fix all those shortcomings in OneSky and keep using it
- Find another provider. Some that we could use for free would be:
  - Transifex (<https://transifex.com/>). It is free for non-commercial Open Source projects, but some features such as the ability to attach context screenshots are apparently only available in the rather expensive paid plans.
  - WebTranslateIt (<https://webtranslateit.com/>). It is free for all Open Source projects that have explicitly been approved as such. Has ready-to-use GitHub integration to automatically update the source translation file (Language.en.ts) when it is changed in the repo.

Regarding the last two, I created test projects for Pencil2D there so everybody can have a close look at those tools, membership requests will be accepted automatically atm. If any decision is made I’ll happily delete or transfer ownership of the respective test project(s) again accordingly.
- Transifex: <https://transifex.com/pencil2d/pencil2d> (Join by clicking on “Join team”)
- WebTranslateIt: <https://webtranslateit.com/en/projects/16300-pencil2d> ([Join here](https://webtranslateit.com/en/projects/16300-pencil2d/invitation_request))

Leaving that behind, I agree regarding GitHub releases and camera interpolation. Also, thanks a lot for always taking care of communication with the rest of the world, @Jose-Moreno!

**Comment by chchwy** [comment]
#567 Camera layer is completely broken at the moment, I'm working on it. Don't worry about it, it is not really hard to me though.

#681 I agreed with @J5lx just no need to rush since we have a not-perfect-but-work exporter.

#520 I checked a few months ago, there is no serious memory leaking in pencil2d. I'm thinking that's not really a leaking problem. It may just run out of memory. 

A Windows 32bit application can only use at most 1.5GB ram. A 1024x1024 image takes 4MB. So 1500/4 = 375. Generally pencil2d(32bit) will use up all available memory after creating 375 frames. We might need to think about how to manage memory properly, probably we cannot keep all images in memory like what we are doing now.

#560 Definitely it's a must. 

About translations, any better option are welcome! No reason to stick with Onesky if there is something better. Onesky is just my randomly picked solution after 15 mins google lol. 

I have created both accounts on Transifex and WebTranslateIt, will try them soon!

**Comment by Jose-Moreno** [comment]
@chchwy Regarding the leak, I agree. I've conducted several independent tests on the memory, and what happens is Pencil2D loads all the images at the same time once you open the file, so when you have more than 200~ images it uses a lot of RAM. I've managed to have around 1200~ individual frames, on a single layer, with drawings ranging from 360 to 1024 px square and it used all my 4GB ram, without crashing. But I have a 64bits OS, so many others with 32 bit OS will not be that fortunate.

Also when you erase the frames, it takes about 3~5 minutes to activate the garbage collection (if that's what it is) and release the image memory for other processes. However if you erase frames and create new ones this process happens faster.

In the past I remember discussing with someone (I think it was feeef or CandyFace) the idea of having a "cache" system, like what after effects has, not only for faster previewing, but also for working on particular segments at a time. Since you don't really need to look or read the whole timeline unless it's playback. Maybe if we allowed the user to select a portion of the timeline so Pencil2D can cache that and unload the other frames? It's something we definitely need to discuss. If you raise the issue for 0.7, I think we can incorporate that along the timeline rewrite as well.

I also agree with both that we don't need to rush the exporter, I was actually asking if we should include it or not on the 0.6 milestone.

@J5lx Hopefully I can work further to bring more people in. I have some small scale media plans to help improve Pencil2D as a brand, but most importantly I'm considering creating a small set of audiovisual products with the software and FOSS technologies to spread the word. Hopefully things will get interesting, we'll see!

**Comment by scribblemaniac** [comment]
If you needed further proof that there are no serious leaks, I did run Pencil in Valgrind a while back, which found no major memory leaks (a few minors ones which were fixed in #573 and a few from qt and the third party libraries which can't be helped).

Remember we do already have a way of selecting only a portion of the timeline for playback (i.e. the timeline range), we just need to configure it so only those frames are cached. It's still not an ideal solution, but it would be an improvement for sure.

I would say to leave the exporter rewrite for 0.7. Even if it can be finished in time, the last thing we want is for some regression bugs to get into the release. If the exporter works now, leave it imho.

@chchwy If the camera layer interpolation is going to take a long time, I think we should just leave it until the next release. It doesn't seem like a simple task and I kind of just want us to get something out already. People can easily work around this issue by making a large selection and moving it manually.

**Comment by scribblemaniac** [comment]
@chchwy What's the status on v0.6? I've got a bit of time off the next couple weeks, so is there anything I can do to help speed this along?

**Comment by chchwy** [comment]
@scribblemaniac i'm working on camera tweening. The code is in the `feature/camera-tween` branch if anyone is interested, it's nearly done. I think the date of releasing 0.6 is coming.

**Comment by Jose-Moreno** [comment]
@scribblemaniac I spoke with @chchwy on the discord server a few weeks ago, we established that I'd migrate all the feature requests into an "issue tracker" here on Github to allow for developers to review and create separate issues from it in order to better organize and parse the amount of work needed to finish certain tasks. This was also so we could have an easier way to identify these features and implement them in the future. 

There's also been talks on the importance of rewriting the timeline, so if you have some time would you mind looking into that implementation / issue?

As for general bugs, I think we should give it a test round once the camera tweening is implemented, because I'm sure many things will require some ironing before release once all the milestones have been achieved. Thanks a lot!

**Comment by scribblemaniac** [comment]
@Jose-Moreno We have a discord server? Can you share a link to it please? It might also be worth adding to the website sidebar if it's somewhat official.

**Comment by Jose-Moreno** [comment]
@scribblemaniac Hey! actually @Spark01 create it for us in all his niceness. So we've been checking it out from time to time. We can't add it on the website sidebar because I don't have control over the website layout, and the webmaster has been very busy.

Spark announced it on Pencil2D's tumblr (which he also opened a long time ago) and I was planning to reveal this server when we announced the 0.6 version. Right now it's basically a beta test to acquaint ourselves with the platform.

https://discord.gg/sEhPg8

**Comment by chchwy** [comment]
Just keep everyone posted.

The nightly build 1st Nov is our second release candidate. 
We will release it as our 0.6 If no deal-break issues are found before next Monday.

**Comment by chchwy** [comment]
@J5lx Thanks for your suggestions, I think it's a good timing to migrate our translation platform from OneSky to Transifex.
Could you please add me to the Transifex project so that I can upload/download ts files?

**Comment by J5lx** [comment]
@chchwy I added you as a project maintainer. Great to see this make progress!

**Comment by J5lx** [comment]
@chchwy I just figured out I can add you as organization administrator as well, so I did that. So basically you should now have full control over everything Pencil2D on Transifex.

**Comment by chchwy** [comment]
Thank you @J5lx  I'm going to sync ts files and then we can deprecate OneSky.

**Comment by chchwy** [comment]
@Jose-Moreno @scribblemaniac  @J5lx  @CandyFace  @gordielachance 
Alright, the nightly build 7th Nov 2017 will be our third release candidate (hopefully the final one).
It will be released as official 0.6 on next Monday If no deal-break issues are found.

**Comment by Jose-Moreno** [comment]
@chchwy Alright. Will test to see if there's anything that breaks. If things seem good then hopefully we can move forward and start thinking on the much needed features that are already half way done, along others you all have suggested in the past. 

Congratulations to everyone for the hard work and hopefully with this we can finally begin to pave the way in order to go beyond the old Pencil and make a great tool for creative professionals and hobbyists alike. :smile:

**Comment by chchwy** [comment]
After resolved #774 #797 #782,  now the 14 Nov 2017 build is our 4th release candidate.
The scheduled release date is next Monday, which is 20 Nov.
Hope everything goes well. ;)

**Comment by J5lx** [comment]
Yeah, hopefully we won’t need another rc :) While we’re at it, how about introducing tags? Not just for the final releases but also release canditades and such (which GitHub allows to explicitly flag as pre-releases). Then we could attach the appropriate binary builds to them and make them more visible (and also make it clearer that they are in fact release candidates that will soon be followed by an actual release).

**Comment by CandyFace** [comment]
Upon initial inspection it looks good to me, nice work! What about the smudge trailing white color bug #720 are we going to leave in the stable release..?

**Comment by Jose-Moreno** [comment]
Thanks @chchwy I'll test right away!

Also agreeing with @J5lx on the tags, I requested to use the release tags here #560 a while ago, and I think it's good for the project to begin using them.

Regarding the bug / odd behavior that @CandyFace referenced I agree that currently the tool is currently not usable in bitmap workflows.
I understand it was untouched since we've been considering the mypaint integration in order not to much "too much" work into a system that will be replaced anyway, but I think that aside the polyline tool, it's one of the most useless tools we have for raster work at the moment. 

On the other hand on vector layers the finger tool work in a very different matter, and it's critical to the vector editing workflow, so disabling it would deeply affect that pipeline.

The only options I see are: 
1) Disable the button ONLY for bitmap layers, for this release.
2) Change the behavior so it works similar to modern graphics editing software for 0.6 release. Maybe we can review some code form The GIMP?, 

The downside for the previous options is that the time for bug fixes might be expanded if anyone tackles that for release and it ends up breaking the tool environment. 

3) We patch it on a coming up version, like 0.6.2 or something. But again, we might be wasting resources since we should really focus on the mypaint integration, considering there's important work already done by feeef.

What do you think?

**Comment by J5lx** [comment]
IMO: Just put it in a Known Issues section for the release, maybe with an explanation of why we haven’t attempted a fix (→MyPaint). Sure, it’s broken, but it’s not the it-makes-me-wanna-ditch-the-whole-program kind of broken (unlike crashes etc.), and it’s not like we’re attempting a one-and-only, perfect release here. If anything, disable it, but that might look like it’s been removed from bitmap mode to people who’ve been using the nightly builds.

**Comment by chchwy** [comment]
Good suggestion @J5lx, will do a pre-release on Github.

I'll leave smudge tool as a known issue. Don't worry. 0.6 is not a final version, more fixes will come with 0.6.1, 0.6.2... soon.

**Comment by chchwy** [comment]
Guys, I've created a new `release` branch and tag it as `0.6-rc`.

From now on, `master` branch will be the place for our daily development, fixes and merge requests and  `release` branch will be considered stable always.

@mapreri maybe you would like to know this

**Comment by mapreri** [comment]
ACK.
I've been silently following the last weeks, while the development rhythm picked up and on my side updated the Debian package more often than usual.

Now that you created a tag I was thinking on moving from picking up random git snapshot to the tagged RC, using the automatically generated by github, and then stick to the releases that I think you are going to cut frequently enough anyway :)

Thanks for the poke!

**Comment by chchwy** [comment]
Hey guys,

After a couple of days of rc4 out, I think it's time to officially release 0.6.
The real 0.6 version will include rc4 + translation updates + #425 + #802. You can find the release-ready code in the latest `release` branch.

But AppImage generating is broken #779 at the moment so I cant get the 0.6 Linux binary to release it.

So, 
1. If someone can create a 0.6 Linux AppImage for me, that's great.
2. Or temporarily go back to desktop version 1.0 to get Travis-CI process working and then find a proper way to do it with version 1.1 later.

Any thoughts?

In addition, I found this thread after some googling:
https://github.com/AppImage/AppImages/issues/166#issuecomment-343829147
Seems like the AppImage team is sticking with desktop file version 1.0?

**Comment by Jose-Moreno** [comment]
@chchwy I haven't been able to test the latest code, although I assume with most of the fixes that have been implemented lately it should be working as expected (need to test though). I also wanted to produce a few introductory videos with the RC, to have them ready for launch but it might take a while.

Regarding the AppImage issue, It would be great to have it ready, but if the problem is Travis, if we run out of time, I might be inclined towards your second proposal. Use 1.0 and look for proper way to implement 1.1 later.

**Comment by mapreri** [comment]
> Regarding the AppImage issue, It would be great to have it ready, but if the problem is Travis, if we run out of time, I might be inclined towards your second proposal. Use 1.0 and look for proper way to implement 1.1 later.

Definitely, please don't consider this a release blocker (despite being an unfortunate issue, if you ask me).

**Comment by chchwy** [comment]
Thank @scribblemaniac now AppImage generating is working!

So the 23 Nov 2017 version from GoogleDrive will be our official 0.6 in a few days if everything goes well. I'm going to join the test team to reconfirm the version is ok.
 
This special version doesn't have `Nightly Build` & date on window title, also no git commit & date in about dialog, just version number.

@Jose-Moreno about the intro video, just take your time. It's not in a hurry. I think it's ok to upload binary first and make a proper announcement later after the intro video is done. The What's new is also not done yet, i'm working on it.

**Comment by J5lx** [comment]
@Jose-Moreno BTW, does Pencil have a YouTube channel yet for collecting those videos? [This one](https://www.youtube.com/channel/UCexMjl4rq8OyzAc7C03uKCQ) looks like it might belong to the project, but it doesn’t seem to be linked from anywhere, has only a front page (no about page, videos page, etc.) and generally seems a little orphan, so I’m unsure.

**Comment by Jose-Moreno** [comment]
@J5lx Yup that's ours. It's tied to our Google Bussines page and Google+ community (which few people use sadly) We advertised it when it started, but since I don't have control over the website (pencil2d.org) I couldn't add it to the side bar links and wasn't able to shout more about it. I was using it mostly to subscribe to some open source projects and follow some artists that use pencil2D or are independent animation professionals.

I created playlists for the older pencil2d and pencil tutorials, as well as a playlist for art stuff. I was planning on uploading the showcase there to help get some traffic on the channel. Also the newer tutorials would be uploaded there, because the older ones I made were uploaded on my channel since it was originally more convenient.

Also I wanted to use the Livestream feature so we could maybe do some art streams, coding streams and stuff like that.

**Comment by chchwy** [comment]
@Jose-Moreno I didn't know there is an official youtube account XD

We have a **community** page on our new website:
http://pencil2d.github.io/community/

Once we get some tutorials & animation pieces in the channel I can put the link on it.

**Comment by chchwy** [comment]
Hey guys,

Since the 0.6-rc4 version has had [over 25k downloads][0] and doesn't meet any serious issues, I'm planning to release 0.6 in next a few days (maybe tomorrow if ready).

With the 0.6 release, I need you guys to give me a hand with **[0.6 What's new][1]**

Because there are SO MANY changes between 0.5.4 and 0.6, it could be very possible that I missed something in the document. Please just add them to the 0.6 release note if you consider something is worth mentioning. You all can edit the doc directly.

@Jose-Moreno Would you like to put the introduction video in this post?

Note: this document is mainly based on:

- [Pencil2d keyboard shortcuts][2] by @Kaikogf 
- [2013 Nightly build note][3]
- [2015 Nightly build note][4]

[0]: http://www.somsubhra.com/github-release-stats/?username=pencil2d&repository=pencil
[1]: https://docs.google.com/document/d/15EljWcjLnAipZ_TKe2FOBR8pJyY_ia21Y1QVgVjvBmU/edit#
[2]: http://www.pencil2d.org/forums/topic/pencil2d-keyboard-shortcuts/
[3]: https://www.pencil2d.org/forums/topic/nightly-builds/
[4]: https://www.pencil2d.org/forums/topic/pencil2d-nightly-builds-2015/

**Comment by Jose-Moreno** [comment]
@chchwy Sure thing. So far I haven't got any complaint on how the footage was used. So I'll re-render the video with some fixes and share the link so you can include it there. After wards I'll use social media to link the post directly.

I also edited the known issues on the document you shared. I marked it in red as a proposal along with a comment.

I think it's worth at least looking into the stroke rendering quality issue before release, but if it's not possible then I say we add that to the known issues. The thing is we need to be sincere, but we also need to make people want to use Pencil2D, otherwise all our efforts might get wasted. If we can't get the fix we at least need to hint to MyPaint Lib as the why we aren't fixing the current bitmap as much as possible.

I'll keep adding things that have changed to the best of my ability. If something is out of place let me know.

**Comment by chchwy** [comment]
Thank you @Jose-Moreno 
Will look into #809

**Comment by scribblemaniac** [comment]
Just so we can keep track of things during the release, what channels are we planning on releasing through and who is in charge of them? Here's what I can think of off the top of my head:

- [ ] Github releases ( @chchwy )
- [ ] pencil2d.github.io ( @chchwy )
- [ ] pencil2d.org ( @gordielachance ? )
- [ ] Debian/Ubuntu apt repository ( @mapreri ? )
- [ ] Homebrew cask ( @scribblemaniac )

Places we could release to, but probably won't unless someone steps up to do it:
- Windows Store
- Mac App Store
- MacPorts
- Other Linux package managers (pacman, yum, rpm, portage, etc.)

**Comment by J5lx** [comment]
I got an Arch package ready that I’ll push into the AUR once 0.6 is released. I’m not a TU though, so I can’t make a package for the official repos ([community] etc.).

**Comment by J5lx** [comment]
I just noticed that the screenshot on pencil2d.org is still from 0.4.4b, maybe we should update that as well.

**Comment by Jose-Moreno** [comment]
@J5lx You're right. Although it might take time to do a nice artwork. Or I could just photo-edit the drawing on top the new interface :laughing:

**Comment by J5lx** [comment]
Arch package is up: https://aur.archlinux.org/packages/pencil2d/

**Comment by mapreri** [comment]
Also uploaded this afternoon to Debian unstable! :)

**Comment by chchwy** [comment]
Updated the download links of 
- pencil2d.github.io
- pencil2d.org
- github README

**Comment by chchwy** [comment]
And here is the official announcement of 0.6
http://pencil2d.github.io/2017/12/introducing-pencil2d-0.6.html

**Comment by chchwy** [comment]
Hey @scribblemaniac 
How are the Homebrew cask and AppImage repository going?

Are you going to deploy pencil2d to these platforms?

**Comment by scribblemaniac** [comment]
Homebrew cask is finished. Mac users with it installed can (after updating) just call:
```
brew cask install pencil2d
```
To install the Pencil2D app. I'll add binary support later.

As for the AppImageHub repository, I'm will try submitting to it today, although I'm not entirely sure if it meets all the requirements.

**Comment by chchwy** [comment]
Thank you @scribblemaniac 

The work of 0.6 release is about to come to the end.
Anything related to AppImageHub please go to #823
I'm going to close this issue.
Well done all guys!
