### ISSUE TITLE
Memory Failure?

### ISSUE THREAD

**Issue by vicundcomic32** [pencil2d/pencil#521]
Whenever I select any tool (example I select the eraser) and I apply it to my frame, it will just delete in small squares and the if I try to redo or switch frames the entire frame will just delete and I cant get any work done and it says this

QPainter: : begin : paint device returned engine == 0,  type: 3
QPainter: : setCompositionMode: painter not active
QPainter: : end : painter not active, aborted
Error instancing bitmapimage.

and it will just repeat this everytime I try to erase, draw, paint, etc.

**Comment by vicundcomic32** [comment]
my mistake it was flipped

Error instancing bitmapimage. 
QPainter: : begin : paint device returned engine == 0, type: 3
 QPainter: : setCompositionMode: painter not active
 QPainter: : end : painter not active, aborted

**Comment by Jose-Moreno** [comment]
@vicundcomic32 Which version of Pencil2D are you using, and what OS do you have? 

Remember that it's good to always input this info first since Pencil2D normally works in Win, Mac and Linux and each has it's own quirks.

If by any mean you have an old version, would you like to try the development snapshots? They are at least more up to date and have many bugs fixed although there are still some critical ones that have to be fixed.

You can download the Nightly Builds here: https://pencil2d.github.io/download/

**Comment by vicundcomic32** [comment]
I was using 0.5.4 and thank you for the new nightly builds and I guess it slipped my mind I was frustrated and confused, but this should help a lot.

**Comment by Jose-Moreno** [comment]
@vicundcomic32 Don't worry. If you find any other bug related to this one in the Nightly Builds, please re-open and let us know. There Is a memory issue I posted earlier this week, but it's too big of a bug to fix quickly so we have to prevent it first from happening and then see how to fix it properly. Cheers.
