### ISSUE TITLE
please allow using system zlib

### ISSUE THREAD

**Issue by mapreri** [pencil2d/pencil#530]
since when I started packaging pencil2d for Debian, I'm carrying [a local patch](https://anonscm.debian.org/git/collab-maint/pencil2d.git/tree/debian/patches/remove-zlib.patch?h=debian/0.5.4_git20160902.50c5ddb%2bdfsg-1) to use the system zlib (I remove the whole 3rdparty/zlib from the tarball).

Now, that patch was a quick thing that just removes everything zlib-related and adds a `LIBS += -lz`, nothing clever.

I'm really dumb when it comes to qmake, so to me it's going to take a good while to come up with something usable also in other platforms and that falls back sanely to the bundled copy.  I wonder if somebody can come up with something here :)

Thanks in advance!

**Comment by Jose-Moreno** [comment]
@mapreri I really wouldn't know where to start either to be honest. Maybe @chchwy or @feeef know any better? If anyone else is using Linux distros, please respond.

**Comment by scribblemaniac** [comment]
Your patch works fine on macs since zlib is installed on the system. I would do something like this though to support the homebrew version of zlib:

```
unix: LIBS += -lz
macx {
  LIBS += -L/usr/local/opt/zlib/lib -lz
  INCLUDEPATH += /usr/local/opt/zlib/include
}
```

I have no idea how it would be setup for windows, so someone else will have to help you there.

**Comment by mapreri** [comment]
@scribblemaniac `/usr/local/opt/zlib/lib` sounds a bit weird to me: it's /usr/local, which according to the FHS is a place where system administrator puts their own stuff, according to whatever logic they like most (except the usual bin, etc, share,...).
Then, is that present on all system?  IMHO the build system should check for the presence of those libraries; for example in linux I'd try to use pkg-config with something like
```qmake
CONFIG += link_pkgconfig
findPackage(zlib){
    LIBS += -lz
}
```

**Comment by scribblemaniac** [comment]
@mapreri It is not present on all systems. On a clean installation, zlib is in `/usr/lib` I think, which will already be in the search path. Adding `/usr/local/opt/zlib/lib` is so that the the Homebrew (a popular package manager for mac, which uses `/usr/local`) version will be used if possible. The advantage of that version over they system version is that it is updated more often.

**Comment by chchwy** [comment]
No system zlib on Windows, and that's why zlib is included in pencil respository. 
If it is more common to use system zlib on linux, we could make zlib as a windows only build option.

**Comment by J5lx** [comment]
In case of interest, I did a quick "port" to the [Meson build system](http://mesonbuild.com/) at [J5lx:meson](https://github.com/J5lx/pencil/tree/meson). Meson is a toolkit-independent, cross-platform build system with focus on usability, speed and generally “doing things better”. I did it rather spontaneously within 30-45 minutes or so, so some TODOs and the tests are yet TBD and there might still be things that could be done better, but otherwise it is fully functional and works splendidly (on Linux, anyway, since most win32/macos bits are TBD). Most importantly, though, it will use system-wide zlib and QuaZip whenever available, and rather than keeping all those 3rd-party sources in-tree, they will be obtained automatically only when needed (that means good bye /3rdlib if qmake gets dropped).

Of course adding a new build system would be a comparably drastic move and I don’t want to force this upon anyone. Probably I’ll end up as sole proponent anyway, but maybe some of you can at least warm up to it :) While mostly boring, here’s an Asciicast of the build process: [![asciicast](https://asciinema.org/a/0i2vyvtgjhrtoaolbrm9ekjpz.png)](https://asciinema.org/a/0i2vyvtgjhrtoaolbrm9ekjpz)

**Comment by J5lx** [comment]
To elaborate on the “focus on speed” aspect, have a look at <https://travis-ci.org/J5lx/pencil/builds> and compare the build times on the meson branch and the other, qmake-based branches (for the Linux builds for now, since I still haven’t added OS X support). The meson build times are on average about one minute or ⅕ shorter than the qmake ones.

**Comment by J5lx** [comment]
To elaborate on the “focus on speed” aspect, have a look at https://travis-ci.org/J5lx/pencil/builds and compare the build times on the meson branch and the other, qmake-based branches (for the Linux builds for now, since I still haven’t added OS X support). The meson build times are on average about one minute or ⅕ shorter than the qmake ones.

*Edit*: Forget about that, I forgot about the missing tests so the actual difference should be not that much. Sorry for the noise.

**Comment by chchwy** [comment]
Interesting result, but I just wonder what else we can get from switching to a new build system, and does it worth?

Pencil currently is on a minimal build system, it does not require any other 3rd lib except Qt. Everything is included in repository.

**Comment by chchwy** [comment]
zlib sources are no longer in the repo after #850, i'm closing this.
