### ISSUE TITLE
Better icon for Pencil2D.exe?

### ISSUE THREAD

**Issue by alexandervrs** [pencil2d/pencil#532]
Perhaps there could be a better icon for Pencil2D.exe? The current one looks jaggy, small and ugly if you use larger icons/thumbnails.

I edited the .exe with a resource editor to add a better icon, so something like this perhaps?

![hs](https://cloud.githubusercontent.com/assets/899446/18411782/6056e432-7787-11e6-8fbd-3667c4819dbf.png)

I attach the icon file I was using: [https://dl.dropboxusercontent.com/u/17514039/Pencil2D%20Icon.ico](https://dl.dropboxusercontent.com/u/17514039/Pencil2D%20Icon.ico) (I think it was from a new logo thread on the forum)

Also perhaps would need to be updated in other platforms as well

**Comment by chchwy** [comment]
That's nice @alexandervrs 
I would update the icon soon.

**Comment by CandyFace** [comment]
Personally prefer the old icon, which looks much better on Mac. 
It looks like a bad scaling job, that's either automated or just done poorly by hand.
![icon](https://cloud.githubusercontent.com/assets/1045397/24821299/23d4c0ae-1bee-11e7-8a05-a9705be93f71.png)

I'll look into it.

**Comment by Jose-Moreno** [comment]
@CandyFace I have the source file for that logo. I removed the circles and uploaded an svg for you to tinker with. 

I didn't dislike the old Logo since It appear to be hand drawn but for the sake of updating and ease of use as a brand I went for a more vector look despite that. I did try to maintain the overall shape and details such as the shade and planes of the pencil though. 

Anyway here it is:

[pencil_vector_icon_small.zip](https://github.com/pencil2d/pencil/files/907019/pencil_vector_icon_small.zip)

**Comment by CandyFace** [comment]
[modified_pencil_icon_by_morr.svg.zip](https://github.com/pencil2d/pencil/files/907306/modified_pencil_icon_by_morr.svg.zip)

![modified_pencil_icon_by_morr](https://cloud.githubusercontent.com/assets/1045397/24827090/7b61d2f2-1c44-11e7-9355-b9a012ea541e.png)

Alright if we're going the svg route for the icon too, then i'm okay with that. I've some changes though, mainly to make the colors more relaxed, i've also rotated the icon so it resembles the old more, without making it too similar.

Whether this will fix the jaggies that persists on the windows, i'm not convinced, since the icon will become bitmap when used as an icon anyway. I've looked into the code and there's nothing to indicate that the icon shouldn't scale, it looks more like an issue with windows not handling its icons correctly when you scale them.

**Comment by Kaikogf** [comment]
Was this icon already implemented? I am in Windows and I see all the icons on the Tools box have changed, maybe this one was too, since I cannot tell the difference right now with the one I see
;)

**Comment by scribblemaniac** [comment]
The icon should look much cleaner now. We are still settling on a version of the new icon to use, but that will not be applied until after 0.6.1 is released
