### ISSUE TITLE
Pen wont keep up with movements 

### ISSUE THREAD

**Issue by JadeCroft** [pencil2d/pencil#538]
So I have a Tablet (Wacom Intuos Pen and Touch Small) and when I try to draw with it the line won't keep up so when i try to draw a line it has about a 3 second delay. So it won't keep up with my movements. I was looking through the setting to see if I could make it keep up with my pen movements but i didn't so now I'm looking for help, if you're able to figure out how to make the pen/pencil keep up with my movement that would be fantastic thank you for taking the time to read this :). ( Sorry i didn't explain it that well )

**Comment by Jose-Moreno** [comment]
@JadeCroft Hi Jade, this is a known problem that the developers are already trying to solve as reported here #486 . However this is not an easy task by any means. 

Hopefully sometime soon we can have a test version of an official effort that seeks to improve the overall drawing engine for Pencil2D and since some advanced users who have tested the code have already managed to create artwork with it, we have great hopes for that.

The only tip I can give you to slightly improve your issue for now is to reduce the **window size** of pencil2D if you need to draw "faster". 

For example if you have a screen resolution of 1920 x 1080, try using pencil2D in windowed mode and making it as wide as half your screen space. And test how much faster it works.

If the problem is too bothersome I can only recommend you two switch to a different program meanwhile this gets fixed, particularly if you're working on a deadline or an important project. 

Hope this helps, cheers.

**Comment by chchwy** [comment]
Hi @JadeCroft 
Can you tell me which OS do you use? are you using Macbook Pro with retina screen?

**Comment by JadeCroft** [comment]
No Im only using a basic MacBook Air it doesn't have any perks just a plain
MacBook Air. Os? (sorry I don't know what that means T.T)

**Comment by JadeCroft** [comment]
Thank you so much for the fast reply sorry I couldn't reply back sooner. I
actually tried sizing the window down but unfortunately it didn't do much
to improve it, I hope to see the test to be a success;). Again thank you so
much for replying in a fast amount of time!

-Jade

**Comment by Jose-Moreno** [comment]
@JadeCroft Hi Jade, sorry to hear it didn't improve things for you. Also when @chchwy spoke about OS, he meant "Operating System" and since you have a Macbook that means you have Mac OS (although we don't know the specific version).

The graphics test will take some time, however chchwy made a new test build with other fixes for MAC OSX and above. 

https://drive.google.com/drive/folders/0BxdcdOiOmg-CcWhLazdKR1oydHM

Try it out if you can and see if it works better or not. Also I think you don't have to delete or uninstall your previous version, just download the latest ZIP file for MAC, and uncompress it's contents inside a folder. I don't have a Mac so I'm afraid I can't guide you through this specific process.

Let us know what happens. We'll be more than glad to help out while we can :smile:

**Comment by JadeCroft** [comment]
Thank you so much for following up and sharing the zip file for Mac.  IT
WoRKeD - PeRFeCTLY!!  The pen keeps up and I'm not having any more
problems.  I'm very happy with this fix.  Thank you!!

**Comment by Jose-Moreno** [comment]
@JadeCroft Hi Jade, we're glad that it's working now for you! A word of caution though. Since this is an experimental release, it's prone to be very unstable, so I'd like to point you to this guide so you can prevent losing work even if you save your file.

http://www.pencil2d.org/pencil2d/faq/#corruptfiles

Also If you think this particular issues is resolved please press the "close" button which indicates to us that this particular problem has been solved. Thanks!
