### ISSUE TITLE
[BUG] Clipping of image in viewport

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#553]
### --Issue Summary--

There is a very small bit of clipping of the rendered area from the camera frame.
### --Actual Results

The rightmost column of pixels is covered, and the top and bottom rows are shaded(?).
### --Expected Results--

I would expect that the area inside the frame is the exact size of the camera dimensions and that none of the pixels inside are distorted in any way.
### --Video or Image Reference--

Imported image (exact size of canvas):
![bordertest](https://cloud.githubusercontent.com/assets/3461051/19428330/b59ea86c-9406-11e6-8fce-ee4b78874414.png)

Viewport screenshot:
![border screenshot](https://cloud.githubusercontent.com/assets/3461051/19428345/ce9037aa-9406-11e6-8bd5-94aa28ddd57e.png)
### --Steps to reproduce--
1. Download the "Imported image" from the previous section.
2. Open a new project
3. Set the camera layer size to 640x480 (the same size as the downloaded picture)
4. Import the picture.
### --System Information--
- Pencil2D Version:
  Nightly Build October 11 2016
- Operating System:
  macOS Sierra

**Comment by CandyFace** [comment]
As far as I can see, nothing is being distorted. What seems to be the issue here, is that the camera border is taking up 1 pixel all around of the canvas, therefore making the pink image border look shaded.
![border problem](https://cloud.githubusercontent.com/assets/1045397/23259594/2bcabab2-f9ce-11e6-9d9d-4f3d2af2a183.png)

**Comment by CandyFace** [comment]
This should be fixed now, review when PR has been merged.
