### ISSUE TITLE
website down again

### ISSUE THREAD

**Issue by gordielachance** [pencil2d/pencil#558]
Hi guys, I had to disable pencil2d.org again as my host said me the server charges were too high.
I'm not sure if they say that every X month to try to make me upgrade my plan (which I can't afford) or if there is a real issue.
Anyway, maybe we should buy another host for Pencil2D if you guys would agree that we buy one together.
My current host is about 70 € per year.
OR we shut down the website and use only Github, but that can be a problem for simple visitors who aren't used to it.

:/ :/ :/

**Comment by Jose-Moreno** [comment]
@gordielachance Hey man. It seems likely that they are now aware that Pencil2D traffic is a little intense for a regular bussiness page, so indeed this might be a stunt to get it down. However we can't neglect the fact that during previous weeks, there's been a lot of spammers bypassing the filters and messaging everyone and their mom via inbox in our forum.

I honestly think we might need to change the website paradigm. We spoke a few weeks back about separating the "user" pager from the developer page. That is going okay so far. But to be honest the forum is looking less and less attractive with each passing day. Yes a lot of people do register, half of them are bots. And barely a handful of true users comment (or change avatars). 

If anything it has been helpful to solve certain issues through mods. But most of the time help has to be escalated to developers. And if we're lucky Matt is around to help me out, like what happened last week, since there was someone who had MAC issues, but all I could do was to forward them to Nightly Builds and if that didn't work to other free software meanwhile we work on a fix.

We could use the static pencil2d.github.io website for most things, but I don't really know if the forum / hub could have a huge impact on how people interact with Pencil2D. To be honest the forum activity is rather sparse, and I'm sure even a facebook group would have more activity.

I think we have several questions we need to ask ourselves:
1. ¿Do we really need the forum? or can we supply that functionality with any other service? 
2. ¿Can we have a cost effective website with the forum?
3. If we change hosting is there a guarantee that we won't have this problem again, on behalf of the hosting company? The spammers will always come and go, but if we're fighting against the hosting company itself, I'd rather look for open solutions, like Github itself. We might just need to pay the domain.

I'd like others to give some input on this problem as well, if possible.

**Comment by chchwy** [comment]
@gordielachance  Sorry to hear that again.
I think It's time to redirect people to http://pencil2d.github.io and use it as our official website, and turn the original site to an pure user forum.

If we want the old site back, I am considering to support you to host the website, Linode has good reputation is hosting industry but I am not sure which plan is suitable for us.
https://www.linode.com/pricing
 
And I am wondering if there are any other lightweight forums that can reduce the cpu usage?

**Comment by gordielachance** [comment]
Hi guys.
Yeah that is SO boring :)  
It's not the first time and probably not the last one.  

It's kind of weird since Wordpress / bbPress should be (are?) quite secure.  I'm surprised how much difficulties we have with that stuff; that's why I suspect the host to try to force me to upgrade.  Which I'm not sure at all, I have no clues, but as @Jose-Moreno says,

> It seems likely that they are now aware that Pencil2D traffic is a little intense for a regular bussiness page, so indeed this might be a stunt to get it down.

They haven't turned off the website, I did (maintenance page) because if I didn't they would have turned off all my websites - which includes my professional one.

Personally, I like having an 'opensource' forum separated from Github / FB / whatever service, but well we have to face up to the evidence : this brings too much problems and is probably bad for the whole project.

@chchwy : bbPress is probably one of the most lightweight forums.  Well, that is how it intended to be : light and fast.  So i'm not sure another one would be better.
The problem _could_ be a bad cocktail (as for any overdose) of plugins; but I did try disabling some of them and they didn't notice a sufficient CPU usage difference.

I think forums are a great things for communities around projects like Pencil2D.  It's too bad there is none on Github.  Seems it could : they have one [here](https://platform.github.community/).

Well, what do we do ?
Do I redirect to http://pencil2d.github.io ?

**Comment by Jose-Moreno** [comment]
@gordielachance I think that github community platform skin is similar to what Natron, opensource uses as well. I think it's the open source forum platform called discourse: http://www.discourse.org/ they have the code on github as well.

It's decent, and might do the trick for us since I agree with the opensource forum idea. Wordpress is nice (I have it too for another website) but it just seems to bring too many issues, particularly since Pencil2D domain brings so much traffic, the spam bots have been increasing a lot now. Many have reported several messages just in the past 3 months. And i'ts not really "open", so potential exploits are difficult to patch for users, obviously.

The problem would be to migrate the login database to retain membership, if at all or just ask both old and new members to sign up again. We could send a mass mail hinting that the forums have to change due to security reasons and all their data will be erased to favour a more secure platform, hence having to sign up again. It is indeed a difficult decision.

If it were my call, I'd say let's go with the static page for now while we look into discourse, since we could use it with an address like "forum.pencil2d.org". But I don't really know if that would be for the best. If you decide to do it, you have my support and I'll help however I can. If you choose anything else, let us know and we'll see how we can assist you further as well.

**Comment by scribblemaniac** [comment]
@gordielachance Can you please add the download links (the bitbucket ones from the README) to the maintenance page? That way people can still download Pencil2D if they need to.

**Comment by Jose-Moreno** [comment]
@scribblemaniac @chchwy @gordielachance @feeef Guys I'm thinking of casting a poll over all of our social media sites to ask people the following:
1. Would you be willing to use a new forum that depends on open-source technologies and would act as a hub for the Pencil2D community?
2. Would you be willing to signup again to use the new community site forum . YES / NO
3. Would you be willing to contribute /donate at least $1 dollar to support the server hosting for the community site to remain active. YES / NO
4. Do you think a Facebook Group should be created simultaneously with the new community forum? YES / NO
5. Do you think we should only create a new Facebook Group and pump more activity into the existing Google+ group, instead of creating a separate community site?

What do you think? If you're ok with it I'll share the google form link later today, so you can share as well and vote too. I think we should also try and listen to the community at large in this case.

**Comment by DarckCrystale** [comment]
Hello there!

Was talking on Facebook page, you can follow this link if you want to read: https://www.facebook.com/pencil2dsoft/posts/1750031055257595?comment_id=1751081268485907

## Survey
@Jose-Moreno Like I said on Facebook, I agree with the poll. Maybe you could propose simpler answers (for non native speakers, like me T_T)

**1.** Would you like to use a new forum? _(it would be based on open-source technologies, and would act as a hub for the Pencil2D community)_
**2.** Would you like to signup again on this new forum/hub? _(yes/no)_
**3.** Would you like to contribute/donate to support the server hosting for this new forum/hub? _(at least, 1$)_
**4.** Would you like to use a Facebook Group? _(even if the new forum comes out)_
**6.** Do you think we should only create a new Facebook Group? _(it would include pump more activity into the existing Google+ group, and exclude to create the new forum/hub)_

What do you think about it?

## Database question
@gordielachance I asked on Facebook but CM could not answer, can you get a database save as a SQL file?

## Donation
Like I said on Facebook, if Pencil2D opens a Tipeee or a Patreon or whatever, I would be okay to contribute with 5 -> 20€/month depending of my income, your needs, and community contributions.

## New forum/hub/website
I insist (please forgive me T_T) on the host mode.

I think that a dedicated server would be nice: lower costs, and all the power in you hands.
You can find some here: https://www.kimsufi.com/en/servers.xml
I have one, and it runs a Mattermost server with 5-6 active members, a Teamspeak server which can handle without any problems 5-6 people, a music bot for the Teamspeak, and some game servers (Minecraft, Don't Starve Together, ...). I pay it ~18€/month.

With a simple (and uggly, yes) phpBB or myBB forum, it would be an easy way to have a forum.

@gordielachance if you don't know how to do with a dedicated server, some friends and me can teach you and show you how to begin.

(I repeat myself, if I am annoying with this topic, please tell me)

**Comment by gordielachance** [comment]
@DarckCrystale : you don't annoy anyone here :)

Guys, good (?) news, I had at least a real analysis from my host.  
They said the automatic CRON jobs from Wordpress was the problem and they explained me how to disable that.
The site is currently back online, they'll have a look to check if the CPU usage remains normal.
If it is, we can keep the website online !  We'll probably know that today.

@Jose-Moreno: discourse.org is 100$/month :)
@DarckCrystale: 18$ a month would be quite an expense for me, too.  
I'm paying about 70$ for my host; and I'm hosting 4 websites on it...  I know it's not the best solution but at least it is the less expensive one.

Fingers crossed!

**Comment by J5lx** [comment]
@gordielachance I don't know what kind of host you're using, but if you have access to Ruby you can install and use Discoure completely for free. The $100 fee is only needed for managed hosting.

**Comment by CandyFace** [comment]
Using discourse would be nice, it's elegant and works really well for discussions. It's indeed possible to set it up for free https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md 
The guide refers to OceanDigital but it should be be possible to use any host.

**Comment by J5lx** [comment]
… that has Ruby. As awesome as Ruby might be, the last time I looked I had a hard time finding dedicated hosts, and IIRC gordielachance mentioned somewhere that is current host is a PHP one. There are some PHP forum packages though that are not unlike Discourse, most notably [esoTalk](http://esotalk.org/) (and of course its successor [Flarum](http://flarum.org), but that one’s still in the early stages). In the NodeJS world there is also [NodeBB](https://nodebb.org/), used on the Qt Forums for instance, but I have absolutely no idea about Node hosting. And of course there are a gazillion other forum packages as well.

Depending on the amount of requests and storage requirements, maybe I could also host something on my server (not limited to PHP), but for now that’s also just a quick idea, I haven’t put much thought into it so far.

**Comment by J5lx** [comment]
Hello again, I just took the time to set up a discourse test instance for Pencil2D on my server, so we can have a closer look at it. There’s still some room left for adjusting it to our needs (i.e. replace the default logo, sifting through that giant heap of options the software provides, etc.), but I think it’s now at a stage where at least all the functionality is working and stuff like that. I also set up inbound mail, so it’s possible to reply to notification mails, and even entirely new topics can be created by sending mail to a specific address:

![Inbound mail addresses for all the categories. You can’t read text in images? Then I’m really sorry, but even I need to keep the spam bots at bay sometimes](https://user-images.githubusercontent.com/2063777/32698971-7d430efe-c7ae-11e7-9279-52ccbad37609.png)

For the best mail-based forum experience, make sure to turn on mailing list mode in your email preferences!

So yeah, as you might have already guessed at this point, for now you can reach the forum at <https://pencil2d-discuss-j5lx.de> (replace the second dash with a dot, I don’t want to get the search engine bots involved just yet). Please try it out and let me know what you think!

Also, it seems there is even an import script for bbPress available, so transferring the forum contents shouldn’t be much of a problem if that’s something we decide to do.

**Comment by Jose-Moreno** [comment]
@J5lx That's amazing man! thank you so much for taking the time to do this! Looks really modern and professional :smile:

**Comment by chchwy** [comment]
@J5lx Tha't cool man, I can't wait to give it a try. But at the moment, I am not able to get an activation email, have waited for an hour, not in spam either. (cry

**Comment by J5lx** [comment]
Yeah, all the mails that were sent to you got bounced. It seems that you misspelled your mail address (chhcwy instead of chchwy). I corrected it for you, so you should get your activation mail now.

**Comment by chchwy** [comment]
damn, i'm stupid. Thanks @J5lx

**Comment by Jose-Moreno** [comment]
@chchwy  I agree, Gordie has been incredibly generous with the project and very helpful overall with his web knowledge. Thanks a lot! :smile: 

Now regarding the website, from a SEO perspective I would be against letting go of Pencil2D.org, at least the domain name; we can easily have that domain redirect to the github page though. Of course we need to think ways to help with the payment, since Gordie is the one that has been maintaining that, along the hosting, ever since (plus dealing with the spammers and technical issues). I believe using two separate sites **that act as one** isn't that bad of an idea, particularly if machine resources can be spared.

Regarding the forum, there are countless threads that are not needed, some have already been solved, others are just the same questions and the reason why we made the FAQ, some are useful as proposalls and some that are worth keeping for historic purposes. I think it'd be better to weed out a lot of the useless threads that were unresolved, maybe just migrate over those that are worth keeping, and if that's a difficult task then just start fresh on topics.

What I'm actually worried about though is the user login database. We should think of making the transition as bearable as possible. People hate re-registering, that's almost an undeniable fact, so we have to warn them in advance, and even so, many people will not come back to the forum even if we send them an email (which only Gordie can do). Additionally a portion of the database is comprised of spammers as well, though I wouldn't mind them crossing over because we now have more control and time to moderate over such things, so we can ban them easily once they "activate".

**Comment by scribblemaniac** [comment]
Yes, thank you Gordie for hosting it so far and doing your best to keep it running well.

My thoughts on the matter are mostly expressed in this comment: https://github.com/pencil2d/pencil/issues/584#issuecomment-347108667
Although I agree with @J5lx's reply that a subdomain would be an even better idea. I am strongly against the idea of using https://pencil2d.github.io as our official website, but I am strongly for using the *content* of that site as the content for our official website at https://pencil2d.org, and even for using Github's servers to deliver said content to the user.

While your statistics do not surprise me at all, I don't think that is a good reason to separate our websites. @Jose-Moreno has been emphasizing the importance of community interaction, which I agree with wholeheartedly. If even 5% of the people who would normally just download-and-go see the prominently displayed forums and decide to participate in them, than that's worth it in my mind. Everyone who downloads the program should be aware that there is a place to ask for help if they need it, and share their work when they don't 😉

**Comment by gordielachance** [comment]
Hi folks !
First of all: congratulations for your great efforts with Pencil2D.

I can see this is now really getting some interest from the web; and even if there is now an other opensource solution (Krita), i'm sure there is some place for Pencil2D if it is able to [keep its own specificities](https://www.pencil2d.org/forums/topic/pencil2d-philosophy/). (keep it simple and efficient, have a nice workflow...) - 

**Thanks** for your nice words about me keeping the website up, even if I didn't get so much involved because of a lack of time.  But I paid the bills, yes.  Not a very difficult job though; in comparaison to what you did interacting with the community or developping the software.

As you saw, the problems we got with the current website is that there has always been a lot of spammers there. Don't know why exactly, never had such problems on other Wordpress installations.  
Probably because of BuddyPress and the high traffic we got (~4000 visitors a day).
My host sent me an email a few month ago to warn me that my hosting had been downgraded and is now much slower, but it's always better than switching it off like before.

So yes, it it time to think about a better solution because my other websites (hosted at the same place) are impacted by Pencil2D.

I'm always in favor of keeping a hand on the data: switching to another service without being able to migrate then is not a good solution in my opinion; but it can eventually avoid a lot of problems (spam, traffic, etc).
Handling it by ourselves is not the easiest solution but at least we can do what we want with our content.

The three solutions I see are:

- migrate pencil2d.org to its own host (so my other websites are not impacted by it)
- migrate the "community" (forums) to another services (github or so) and keep the "static" content like it is for now - we might be able to setup a subdomain for this (forums.pencil2d.org or something)
- completely shut down the actual website and do everything on Github.  Quite a convenient solution (I like Github) but we depend on them then.

I don't know how much spam there was those last months.  I think it was better than before; guess Wordpress & Buddypress keep evolving about it.

I can do whatever you want about this; you know Pencil2D better than me!  Also, as someone asked (I don't remember where or when), I found the credential for the twitter account https://twitter.com/pencil2d; that I can share (as of the Gmail account).

Thanks !

**Comment by gordielachance** [comment]
Please reply on this topic (https://github.com/pencil2d/pencil/issues/825) if there is stuff to update on the current host.

**Comment by chchwy** [comment]
Hey @gordielachance happy to see you here.

I think the best solution atm would be (not sure they are all possible or not):

1. Redirect the domain name `pencil2d.org` to `pencil2d.github.io` 
2. set a subdomain like `forum.pencil2d.org` to @J5lx's discourse forum.
3. Shutdown the current Wordpress site (and stop worrying about pencil2d stuff that impacts your own site).

Is the DNS provider of pencil2d.org allow it?

**Comment by CandyFace** [comment]
I'm not against taking the wordpress pencil2d.org site down but we should give a heads-up to the current userbase of pencil2d.org that we're moving the website to github, and that the forum will now be available via Discourse. Also if we can't migrate the old user logins to the discourse forum, that should be stated as well.

**Comment by gordielachance** [comment]
It seems it is possible to migrate it:
https://meta.discourse.org/t/migrating-from-bbpress-wordpress-plugin-to-discourse/48876

I can send the current forum database to @J5lx.

**Comment by J5lx** [comment]
My stance:

1. Make pencil2d.org serve the GitHub Page (i.e. set a CNAME to pencil2d.github.io)
2. Make a subdomain serve the discourse forum. This might be more tricky than a CNAME record due to the mail configuration. It might be easier setting the nameservers to some that I can control myself, or transfer the domain completely if you like, @gordielachance. I will look into migrating the old forum contents of you provide me with the database, potentially filtering out all the spam and such.
3. Let current users on the bbPress forum know beforehand.

**Comment by chchwy** [comment]
Hey @gordielachance How are you going with the domain name things?
It's alright If you're not able to do that. Just let us know and then we can find other ways.

**Comment by gordielachance** [comment]
Yes, sorry, I was thinking you guys were still discussing about all that
stuff.
I can do whatever you want within some days !

2017-12-13 0:45 GMT+01:00 Matt <notifications@github.com>:

**Comment by gordielachance** [comment]
I would need access to the github repo : https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

**Comment by gordielachance** [comment]
Would it be easier that I give you the pencil2d.org domain so you can handle this by yourself ?

**Comment by chchwy** [comment]
@gordielachance  Have invited you to the repo `pencil2d.github.io`

And it would be great if you are happy to give us the permissions to access the domain. @J5lx and I can tweak the settings no problem.

**Comment by gordielachance** [comment]
Ok, then i'll give up on the domain and the WP.  A new start for Pencil :)
Who would take this in charge ?  I could 'open' the domain so the transfer can be done

**Comment by J5lx** [comment]
I could take care of the domain, that would make the DNS configuration for the forum easier. Speaking of it, I got the import pretty much figured out now, as far as I've seen there's only some formatting (centered text etc) that actually “broke”.

**Comment by gordielachance** [comment]
Hi @J5lx , that seems nice ! Could you give me your email so I can send you the required code to transfer the domain ? Thanks

**Comment by J5lx** [comment]
My email address is j5lx@fmail.co.uk. Maybe you could also send me the current DNS entries / zone file in addition to the transfer code so I can migrate them easily. The Discourse forum can currently be reached at https://pencil2d-discuss-j5lx.de/, with the second dash replaced by a dot. However please don’t redirect the forum to it just yet, I don’t want search engines to pick up its current, temporary location.

**Comment by chchwy** [comment]
Cool @J5lx, I've seen all posts showing up in the new forum, good job!

A few questions
1. You said users were successfully imported, does it mean the old forum users are able to log in to the new discourse forum directly? do they have to do something like resetting password or verifying emails? 
2. Will a user be able to edit the posts imported from the old forum? If not it's fine. Just keep them in archive state.
3. Probably we can skip step 5. There are no important things recently. And maybe not worth to be 100% correct importing.

**Comment by J5lx** [comment]
1. That’s a good question actually. Since I created my account on the new forum manually, I’m using the password that I set in Discourse and I have no idea whether the one from the bbPress forum would work. Looking at the code of the importer it seems like the password hashes are imported, too, so I’d expect Discourse to be able to handle them, but maybe it’s better if someone who did not manually register on the new forum before the import (i.e. anyone except me, @CandyFace, @chchwy and you) could try it.
2. I can edit them at least and I don’t think there is any reason for non-admin authors not being able to edit their own posts. BTW, I just noticed that some posts are owned by system, but from a quick look it seems that those are only anonymous posts.
3. I’m planning to do a clean import for the final switch anyway, so it’s not a big deal for me. I’d just need an up-to-date backup from @gordielachance once the time has come, but if it’s too much effort for him then we can use the existing backup, sure.

One last thing I noticed is that uploads are not imported but hotlinked. Maybe we should import the image files (either into discourse or into the gh pages site).

**Comment by gordielachance** [comment]
No, I can export the database one more time when you need it, just tell me.

2017-12-15 1:08 GMT+01:00 Jakob Gahde <notifications@github.com>:

**Comment by scribblemaniac** [comment]
> someone who did not manually register on the new forum before the import (i.e. anyone except me, @CandyFace, @Jose-Moreno and you) could try it.

The login does not work for me with either my username or email.

**Comment by J5lx** [comment]
Ah, good to know. So we’ll have to remember to ask existing users to update their passwords after the migration.

BTW, the domain transfer is in progress, I’m currently waiting for @gordielachance’s registrar to approve it, which, according to my own registrar, should happen „before Dec 20, 2017 unless they refuse it”.

**Comment by Jose-Moreno** [comment]
@J5lx @chchwy @gordielachance I think we are missing the link to the new forums from the github page and then making the pencil2d.org point to the page as well, but I'm confused as to what happened with the domain transfer? I thought it was in progress over a month ago, was there an issue?

IF possible I'd like to ask gordie to issue a warning that we will be moving servers, so people don't get discouraged from visiting in the future. But ultimately we would be needing to wait for J5lx's report on the forum in order to make the transition.

**Comment by J5lx** [comment]
As I’ve already written privately to gordie some time ago, the domain transfer is complete. Basically all of the setup is in place (and it has been since early in January be honest), the only thing I’m still working on is making the import script import images as well because I’d rather do this *properly* instead of *quickly*, but the last few weeks have been filled for me with lecturers trying to get all of their (graded) assignments through all at once before the end of the semester, so I didn’t exactly make a lot of progress. However, the non-lecture period just started a few days ago, so hopefully I can get it done real quick now if I prioritise it. That said, if it’s really urgent then of course we can just dump those images and get it over with, in that case just send me an up-to-date backup, @gordielachance, and I’ll flip the switch asap. Otherwise give me just a few days at most to get the image import done, and I’ll report back here once I’m ready.

BTW, either way I’ll have to commit some files (CNAME and redirects) directly to the website repo without going through a PR process in order to make the transition seamless, just to avoid some unexpected surprises here.

Also, I’m very sorry for not keeping you posted on this! My updates in this thread in particular have been much more scarce than they should have been, but I especially regret that I didn’t even keep you, @gordielachance, up to date, even though you are still the one keeping the current website running. This is definitely something that I’ll have to take more seriously going forward.

**Comment by J5lx** [comment]
As I’ve already written privately to gordie some time ago, the domain transfer is complete. Basically all of the setup is in place (and it has been since early in January be honest), the only thing I’m still working on is making the import script import images as well because I’d rather do this *properly* instead of *quickly*, but the last few weeks have been filled for me with lecturers trying to get all of their (graded) assignments through all at once before the end of the semester, so I didn’t exactly make a lot of progress. However, the non-lecture period just started a few days ago, so hopefully I can get it done real quick now if I prioritise it. That said, if it’s really urgent then of course we can just dump those images and get it over with, in that case just send me an up-to-date backup, @gordielachance, and I’ll flip the switch asap. Otherwise give me just a few days at most to get the image import done, and I’ll report back here once I’m ready.

BTW, either way I’ll have to commit some files (CNAME and redirects) directly to the website repo without going through a PR process in order to make the transition seamless, just to avoid some unexpected surprises here.

Also, I’m very sorry for not keeping you posted on this! My updates in this thread in particular have been much more scarce than they should have been, but I especially regret that I didn’t even keep you, @gordielachance, up to date, even though you are still the one keeping the current website running. This is definitely something that I’ll have to take more seriously going forward.

**Comment by gordielachance** [comment]
No problemo :)
Just that I'm running out of ressources and this make all my other websites very slow. I'm sorry but I've temporary set up the maintenance mode to calm this down for a few hours.
Of course I can wait a few days or/and send you an up to date backup; but please don't wait too long :)
Thanks a lot !

**Comment by scribblemaniac** [comment]
@gordielachance Any chance you could update the maintenance mode page to point to the v0.6.0 downloads instead of v0.5.4?

**Comment by gordielachance** [comment]
Sure ! I've done it.
But i have also disabled the maintenance mode (and some WP plugins); we'll see if the CPU gets high again.

**Comment by J5lx** [comment]
Alright, image import is working now. @gordielachance, as soon as you send me an up-to-date backup I’ll start doing the migration. Please note, though, that it is already in the evening where I live and I’ll not be at home tomorrow from morning to afternoon, so depending on when the backup arrives I might not be able to work on it before around 14:00 CET tomorrow. Also, please note that it will take some time (the import script alone took almost 30 minutes the last time I ran it, and that’s not even the slowest script involved).

Also, @chchwy, I had a look at GitHub’s documentation on setting up a custom domain for GitHub pages, and apparently the procedure changed a little since the last time I did it. Therefore you’ll have to set **`www.pencil2d.org`** as the custom domain in the settings of the pencil2d/pencil2d.github.io repository as explained [here](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/), since I don’t have permission to do that. Please report back here once you did that since apparently it has to be done strictly before the DNS records are set.

**Comment by chchwy** [comment]
Hey @J5lx You're part of the web admin team, so you can push code to `pencil2d.github.io` repository directly. Just do anything you like.

**Comment by J5lx** [comment]
I know that I can push, but I can’t edit the settings:

![screenshot-github com 2018 02 08 23-33-25](https://user-images.githubusercontent.com/2063777/36001946-9536f524-0d28-11e8-9f3a-e4dbff474a1c.png)

That’s why I need you to do this.

**Comment by J5lx** [comment]
I know that I can push, but I can’t edit the settings:

![screenshot-github com 2018 02 08 23-33-25](https://user-images.githubusercontent.com/2063777/36001946-9536f524-0d28-11e8-9f3a-e4dbff474a1c.png)

That’s why I need you to do this.

**Comment by chchwy** [comment]
Ah sorry, done. have set `www.pencil2d.org` as the custom domain.

**Comment by J5lx** [comment]
Alright, then all that’s left is the forum migration. Thanks!

**Comment by chchwy** [comment]
@gordielachance Are we able to tell all the forum users about the new forum before shutting down wordpress?

**Comment by gordielachance** [comment]
Yes, I can set the maintenance mode with a custom message for the time we want.  Just tell me what to put there.  Meanwhile i've enabled the maintenance mode so the forums are "frozen".

**Comment by J5lx** [comment]
BTW, as already mentioned on IRC earlier, the migration is complete. The new forum is now live at <https://discuss.pencil2d.org> and pencil2d.github.io has moved to www.pencil2d.org. One thing we might want to figure out how to get HTTPS working for www.pencil2d.org (it’s already working on discuss.pencil2d.org and pencil2d.org, but the www subdomain is hosted by GitHub and GitHub doesn’t support TLS for custom domains). A popular solution seems to be CloudFlare, but from what I’ve read that comes with some caveats that I personally don’t exactly like. More discussion on that can be found in the chat logs on Discord.

Also @gordielachance, while technically the wordpress site is no longer needed now, please wait a day or two before disabling it since it can take some time for DNS changes to propagate.

**Comment by gordielachance** [comment]
Cool, thanks for your work.
I'll wait a few days before deleting it.
Good luck folks !

**Comment by scribblemaniac** [comment]
I'm going to close this since the migration is complete and nearly everything is working now. Any issues with the website can be brought up in new issues. Thanks again to everyone who helped with this, especially @gordielachance and @J5lx for hosting the old and new forum respectively, and for working together on the migration. ⭐️
