### ISSUE TITLE
i can get past the 800 frames it starts to glitch out and is really anoying losing 2 hours of work i really love pencil so i hope you fix it

### ISSUE THREAD

**Issue by marcomaureiraflores** [pencil2d/pencil#574]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ CPU:

+ Graphics Tablet:

---

**Comment by Jose-Moreno** [comment]
@marcomaureiraflores Hi, sorry to hear you lost work. I'd encourage you to read this article we made to address this issue before attempting another "long" animation.

http://www.pencil2d.org/faq#corruptfiles

Also we setup the tempalte because we need that info to better improve our chances to fix the problem, not writing anything makes things a bit hard so i'd like to ask the following:

1. Copy your title into the report description.
2. Edit your title to be shorter.
3. We don't know what is causing this problem, so if you could be more specific with your report, like letting us know what you were doing when you lost your work. Did it crash? Or it became unresponsive indefinitely? The more you can describe, the better.
4. If there's a crash report, please attach it to this thread. Like if you're on windows you can access your crash reports  this way:

**Windows:**
1. Click Windows Start button > Type event in Search programs and files field.
2. Select Event Viewer
3. Navigate to Windows Logs > Application, and then find the latest event with “Error” in the Level column and “Application Error” in the Source column
4. Copy and paste the text on the General tab to Notepad, and then save the log as .txt.
Or you can take a screenshot of the entire screen and save as a .jpg file.
5. Submit the log (.txt or .jpg) to this thread.

**MAC**
1. Open the Console. Go to Application->Utilities->Console
2. The Console app has the log files arranged by system level process or user level process. crashes
3. If you can't see the logs press the "Show Log List" Label
4. If you can't use the console app try to find the folder address ~/Library/Logs - where you will get the crashes logs and other stuff in separate files.
5. Try to find the latest crash log for Pencil2D and send it over as a text file or screenshot the whole report.

p.s For the folder address ~/Library/Logs/ the ~ sign refers to your Home directory.

**Comment by marcomaureiraflores** [comment]
well what happened i was arround 780 frame and out of no where the screen turns grey and i was like
i didn't use the bucket what happened , i tried to save (because i didn't wanted to lose my animation)
i clicked file and it crashes i lost like 100 frames then i draw all over again and when i get near the 780 it
gets grey again since i didn't want to lose all again i was quick and save but when i see my file there's something weird, originaly every image was the same  size but as i saw almost everything was a different size, well that's what happened.

**Comment by chchwy** [comment]
Hi @marcomaureiraflores  Sorry to hear that.
In order to help us to find the problem, could you send us your animation file?
I guess the file size is quite big so upload it to google drive or dropbox.
Thanks.

**Comment by scribblemaniac** [comment]
@marcomaureiraflores Also what version of pencil are you using?

**Comment by marcomaureiraflores** [comment]
https://drive.google.com/open?id=0BzCxkLG_vCtZcHRsalVubERrWHM

there's a zip file with everything

**Comment by chchwy** [comment]
Hi @marcomaureiraflores, thanks for uploading, but I need one more "la historia de las afps y su funcionamiento.pcl" file which is located at the same folder, it's the main file that pencil2d organize all this pictures together into a animation.

**Comment by CandyFace** [comment]
@marcomaureiraflores What version of Pencil2D did you use?

**Comment by chchwy** [comment]
Hi @marcomaureiraflores 
If you still like to use Pencil2D, please try the latest nightly build. This issue has been resolved in nightly build 04 March 2018.
http://www.pencil2d.org/download/#nightlybuild


Please don't hesitate to tell us if you get something else wrong.
I'm going to close this. :)
