### ISSUE TITLE
[enhancement] copy multiple frames at a time

### ISSUE THREAD

**Issue by sshipway** [pencil2d/pencil#575]
Currently, it seems only possible to duplicate a single frame in a layer.  When you have a sequence that you want to repeat, it is annoying to have to copy each one in turn.   It would be much easier to be able to highlight a range, and then duplicate them all in one go.

I'm not exactly sure how this would work in the UI -- maybe a 4th button 'duplicate multiple' ?  Maybe have the 'duplicate' button advance you to the frame after the copied frame, rather than move you to the newly created duplicate (so that the button can be clicked multiple times to copy a sequence)?

**Comment by Jose-Moreno** [comment]
@sshipway Hi! I totally agree with you. We surely need a way to copy / paste and duplicate multiple frames at any given time. I think we could use the same "duplicate frame" button react different when you have more than one frame selected. 

The thing is that right now it seems when you use the duplicate button you will duplicate the current frame (the one the playback head is over) and the duplicate will populate in the next empty frame space.

However It would be better to implement a different system for duplicating frames. I'm a fan of how TVPaint and Flash did it, which is "instancing" the keyframe itself to allow for exposure (cloned frames) to be increased or decreased. Also copy / pasting a range of frames effortlessly with CTRL + C / CTRL + V or ALT + Dragging the selection which allows for precision when placing the frames on the timeline.

**Comment by Kaikogf** [comment]
@CandyFace 
It seems the same topic as #2 (?)
If so you may close the other 👍 

Thank you

**Comment by davidlamhauge** [comment]
I would like to work on this issue. Please.

**Comment by chchwy** [comment]
@davidlamhauge please go ahead.

**Comment by Jose-Moreno** [comment]
**Note**: I'd like to ask that the copy / paste implementation allows the copied keyframes to be pasted to other layers different from the active layer, but of similar type e.g bitmap to bitmap, vector to vector, sound to sound, etc) And if possible the interface would allow us to select the layer similarly to the movie export dialog where you can select different camera layers if there's more than one.

**Comment by davidlamhauge** [comment]
I'll see what I can do, Jose

**Comment by davidlamhauge** [comment]
I intend to make a dialog where you can 1) Copy, 2) Move or 3) Delete a range of frames.
If the range-box is selected in the timeline, then this range will be suggested in the editable spinBox'es. If not it will be frame 1 and 2, and then you must define the range yourself.
What do you think? Is this ok with you?

**Comment by Jose-Moreno** [comment]
@davidlamhauge It think it sounds excellent :slightly_smiling_face:  thank you for considering my inquiry on your implementation and for sharing your possible solutions!

**Comment by davidlamhauge** [comment]
I can't see the use of such a feature, unless you animate a pendulum, but I would paste it like ordered. That is the content of last frame (if any) first. Then second last, third last and so on.
Is there another way to understand "reverse order"?

**Comment by sshipway** [comment]
@davidlamhauge - I'm thinking about animations where you have something moving back and forth in one layer - eg, mouth opening, hand waving, door open/close, etc.  I wouldn't say this was an essential feature, but might be useful to some users if not too onerous to add.
When reversing, the question is how to handle gaps in a string of frames (i.e. where a single frame is displayed for an extended time, as pencil allows this).  Would you preserve the gaps (treating them as frames), or treat the gap as an extension of the frame that precedes it in the original sequence?

**Comment by davidlamhauge** [comment]
@sshipway - Since I have no way to know what your intentions are with your animation, I can only interpret 'reverse' as 'reverse'.
So - if you have a 20 frames range that you want to reverse, and frames are like this (with 'b' as 'blank'):
1-b-b-b-b-b-b-b-9-b-11-b-b-b-b-b-17-b-19-b
Then I would reverse it like this:
b-19-b-17-b-b-b-b-b-11-b-9-b-b-b-b-b-b-b-1
To me, this is reversing a range.
In the dialog there are going to be several boxes where you define the range, and can chose where to put the first frame when you copy, move or reverse a range of frames. Maybe you can get your intended timing there, but I can't have any idea of what you want, so I will reverse if you want a reverse.

**Comment by davidlamhauge** [comment]
@Jose-Moreno and others: Are there any objections, if I integrate the 'reverse'-feature in the dialog as well?

**Comment by CandyFace** [comment]
I'd say it comes down to how "complex" the dialog has become at that point. If the feature has no relation to copying frames, it should be it's own dialog but I'd like to see what the dialog would look like first. The more we cramp into that dialog, the better we'll have to explain each feature in the UI.

**Comment by Jose-Moreno** [comment]
@davidlamhauge I'm not opposed to it and as a user I wouldn't have an issue with it as long as it works, but I agree with @CandyFace that we should review if the functionality itself is consistent and clear for the end user while being part of the multi-frame copy dialog.

If you already have the reverse order functionality implemented we have to consider that either you are copying the frames and pasting them in reverse order, or you are "ordering" the frames that are already positioned on the timeline.

If it's the former approach, then it would certainly be different from the Idea proposal I linked, and would probably be OK to come as part of this multi-frame copy dialog. The other proposal can be edited as a UX enhancement instead or something.

_Otherwise_ since "reversing frames" is a very specific behavior that allows you to re-order the selected keyframes, this doesn't necessarily mean it has to occur during copying+pasting operations or subject to the range, so a more direct approach would be to use the selected keyframes identifiers to physically exchange their absolute frame position. Since it's a very straightforward operation meant to speed up workflow it could be kept as a separate command to remove the need to use a dialog; a shortcut and a menu entry would do just fine. Also if you separate it there would be the benefit of having a third pull request count for Hacktoberfest :wink:

**Comment by J5lx** [comment]
Resolved via #1343
