### ISSUE TITLE
UGEE Tablet

### ISSUE THREAD

**Issue by tyendor** [pencil2d/pencil#576]
### --Issue Summary--
 When using a UGEE M1000L tablet, there is a huge lag time between what is drawn and what appears.

### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ CPU:

+ Graphics Tablet:
UGEE M1000L Driver version 1.26

---

**Comment by chchwy** [comment]
Hi @tyendor 
Could you please tell us what operating system are you using? do you use Windows or Mac?
And which version of pencil2d, 0.5.4 or nightly build?

We can't help you without these details, thanks.

**Comment by Jose-Moreno** [comment]
@chchwy There was a report regarding the UGEE way back, and today someone else commented on the same thread on the forum. They are both using Windows 10 (July report) and MAC OSX (november report) respectively. I'll leave the link to that thread.

https://www.pencil2d.org/forums/topic/pressure-sensitivity/

**Comment by tyendor** [comment]
I'm sorry...that would help would it? I am on Mac OSX 10.11.6 El Capitan. I searched your site for UGEE before posting my problem but didn't see any results. Nonetheless, there is no "lag" with other drawing programs such as Mischief, Gimp, and Krita.

**Comment by tyendor** [comment]
And using Pencil version 0.5.4 (26 July 2013).

**Comment by Jose-Moreno** [comment]
@tyendor Meanwhile Matt who's our lead dev answers would you mind trying the latest development build for MAC and let us know if that one is working incorrectly? That Pencil version 0.5.4 is very old. We have one for November, and it could help us corner the incompatibility since I've noticed it's related to "El Capitan" OS and possibly QT5 (our development framework used by many other software).

You can try out the newest Nightly Build by downloading from this google drive folder (you don't need an account to do so you can download directly the file)

https://drive.google.com/folderview?id=0BxdcdOiOmg-CcWhLazdKR1oydHM&usp=sharing#list

**Comment by tyendor** [comment]
Awesome! I'll give that a try and let you know what happens.

**Comment by tyendor** [comment]
I just downloaded and tried the newest version and am happy to say I am not experiencing any lag time with the UGEE tablet!

**Comment by chchwy** [comment]
Thanks for your feedback @tyendor!
I am going to close this issues if no more lag problem in nightly build.
Enjoy animating!
