### ISSUE TITLE
Gegl integration request

### ISSUE THREAD

**Issue by vpaintanimation** [pencil2d/pencil#607]
Pencil2d merges gimp kernel (gegl), becomes a tool cluster for pencil2d, for handling animated special effects. Looks very perfect, but do not know how far away.

**Comment by chchwy** [comment]
Actually I don't know what GEGL is for, so I cannot comment on this. Could anyone tell me what it is?

**Comment by J5lx** [comment]
It’s an image processing library. AFAIK its development is driven by GIMP developers and it’s intended to power the core operations of that program eventually. I think it’s still an ongoing effort, but I have no idea how far the library itself has come already.

**Comment by J5lx** [comment]
(IOW, I think Pencil is supposed to use it to provide more advanced editing (effects?) features.)

**Comment by Jose-Moreno** [comment]
This could be interesting, however I think that despite some very minor effects we must always strive to make Pencil2D as simple and as efficient as possible to fulfill it's purpose. 

Let's think in simple terms. We need the software to create animation.  If we need compositing, color adjustment, or anything that has to do with image processing we can use a dedicated compositor for our animated sequences like Natron, or even Blender's compositor.

There is a real danger to create a "one-for-all" kind of program. I think effort would be better invested in making the user life easier on what the program is supposed to do. For example, thinking of image processing an automatic multi-frame coloring feature or a vector auto-trace feature would be better.

Particle effects would be nice indeed, but again we should establish a limit as to how much we want Pencil2D to accomplish, and leave the rest for dedicated software so we won't clutter the app too much with the same old features that everyone want, just because they don't want to learn a new piece of software.

**Comment by Jose-Moreno** [comment]
As a side note we should look into Boris' real VPaint software since it has a great vector drawing paradigm. This only to strenghten Pencil2D's vector drawing. https://github.com/dalboris/vpaint

It's that or to take a look into OpenToonz considering they are also using QT and C++ as far as I know.

**Comment by vpaintanimation** [comment]
Pencil2d chose the GPL protocol, and vpaint chose the MIT protocol, both seem incompatible.

**Comment by Jose-Moreno** [comment]
No, MIT License is GPL-compatible.

https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility

And when I said Pencil2D should look into vpaint vector tools, I meant it only as a review. I've tested vpaint in the past and although it has a great vector drawing capability, it also has a completely different philosophy on how time and space affects the way drawings are represented on the canvas, and that could be an unnecessary element to incorporate on Pencil2D. 

Pencil2D's philosophy so far cares about simplicity and efficiency for animation production. Thank you for your interest and contributions to the discussion either way.

**Comment by mangeurdenuage** [comment]
@vpaintanimation 
Like " Jose-Moreno " said the GPL is compatible with the MIT license because the MIt license is a permissive one.
Their are very few free software licenses that aren't compatible with the GPL.
MIT and BSD are permissive licence.

Permissive means that the license lets people do anything without restrictions.
That also means letting people do bad things.
For example the MIT or BSD can let people make modification to the code and then compile it without sharing the modifications made in the source code (even if asked).
That means that a developers has power over the users.

Their are a lot of misconceptions about the GPL or license in general.
For example the GPL doesn't force you to share source code.
If you share a copy of the software to a individual you aren't forced to give the source code.
But if that person ask the source code you have to share the source.
If you make it publicly available, like for example the internet.
Then you are forced to share the source code at the same time.

The GPL protects both parties, developers and users (since developers are users).
See more about incompatibilities here:
https://www.gnu.org/licenses/license-list.en.html
good luck and
Happy hacking

note: if you look for brushes maybe krita has some interesting ones.

**Comment by chchwy** [comment]
Had a look at GEGL and it requires so many dependencies which will make compiling Pencil2D extremely complicated and I don't see the decisive reasons to adopt GEGL rather than other light-weight image processing libraries.

**Comment by J5lx** [comment]
For the record, what GEGL brings to the table in terms of unique features is mainly non-destructive editing AFAIK, so if anything it could be useful for stuff like effect layers (Synfig has those, I think). As far as that is concerned I recall reading something a while ago that hinted at the possibility of using G’MIC (which is relatively light on hard dependencies IIRC) for non-destructive operations as well, but I have no idea whether G’MIC itself has any support for that. Either way I guess even if we were going to implement something like that it would probably be later rather than sooner. Also, what you say about GEGL’s dependencies is certainly true, glib2 alone is a beast.

**Comment by CandyFace** [comment]
If anything I'd say that G'MIC would be much more viable than GEGL... but still adding such a complex image processing stack to an application that is supposed to be straight forward... to me that's just a huge contrast in UI/UX.
