### ISSUE TITLE
[ISSUE] The SWATCH colors on the COLOR PALETTE keeps changing when selecting another color on the COLOR WHELL

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#732]
### --Issue Summary--
When selecting a default colour from the COLOR PALETTE list, it will be replaced with a diferent color selected from the COLOR WHEEL
[I think I already reported this on another comment but I lost its track]

### --Actual Results
A colour selected on the COLOR PALETTE is changed by the one picket on the COLOR WHEEL
[it makes no sense to have them named as a specific color if they keep changing everytime]

### --Expected Results--
The default list of swatch colours on the COLOR PALETTE should be kept fixed, and any change on the COLOR WHEEL should not affect them

### --Steps to reproduce--
1. Open Pencil2D
2. Notice that the default swatch color already selected is BLACK
3. Go and select another color on the COLOR WHEEL, keeping an eye on the black swatch
4. RESULT: The default swatch's color was changed to the new selected color on the COLOR WHEEL
5. Same happens to any swatch color on the list

### --System Information--
+ Pencil2D Version:
Last build from 23 August 2017

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

---

**Comment by Jose-Moreno** [comment]
@Kaikogf Hey, glad to see you around. Actually, this is not a bug. This is intended. Just so you know this is how it works on Industry standard software like Toonboom Harmony. On TB however you can "double click" on the palette to bring the color wheel, so it works as a safety feature. But the only way to color on that program is by using the palette first, picking up the colors you will use, and then applying them on the canvas. Sort of like a real painter if you will.

Maybe we can ask for the developers to add a "safety lock" so you can choose not to change the selected palette color. However this is NOT a bug, it is intended that you USE the color palette as the main mean of coloring because it is geared mostly towards an animation production environment where there's a color model sheet you can import for a character or an environment, and you, as the animator are not supposed to change the colours. Normally a color stylist does that for you. You just animate.

On smaller teams you might have to color as the animator, but again this should be dictated by the character designer / color stylist.

For independent animators, I understand that one can have a rather artistic approach, but even though Pencil2D is not a painting app the principle still applies.

**Comment by Jose-Moreno** [comment]
Just to get the point across so others who join the discussion can understand the "why" of this behavior here  I attach a screenshot of toonboom harmony "colour palette" view

![image](https://user-images.githubusercontent.com/4912907/29653382-27c89620-886f-11e7-8082-f56a2eb313f1.png)

As you can see, there are two black colours. One says black, and the other one says "vectorized line" but it's still black. Their philosophy is that you should always use one distinct colour for every element, either stroke or fill should have an independent colour in the palette. So if you require changes later you can change independent elements on all the other drawings without having to re-paint it every frame. This works particularly good for vector drawing and fills.

Of course for bitmap the painter analogy would be similar. You get your physical palette, and paint tubes to spread pigment. You use different distinct colors and use them to mix new colors on the canvas.

**Comment by feeef** [comment]
It is a feature indeed but it may lack documentation.

The color palette is supposed to give you quick pre-defined colors. The color wheel lets you define the color within the palette.

For example, when you are working on a vector layer, you define your "skin color" and draw all skin with this color. If you decide to adjust this color with the wheel, you will change the color of the swatch in the palette and all references of this swatch in the drawing will be updated as well. This only work with vector drawing. Not bimap.

In bitmap mode, you may create a swatch that is called "free color" that you use select when painting with the wheel only. It will preserve other colors from the palette.

**Comment by CandyFace** [comment]
Imo. this should be optional, being locked to a palette as if you were back in the 90's on an indexed 256 colors, seems quite unintuitive to me. I know that usually you have a set of specific colors you use, which is fine but if you for example intend to paint a background, then you should be allowed to select colors freely, without changing your palette. This should not differ between the layer types. Maybe a lock as @Jose-Moreno mentions is a good option for this.. maybe not, we'll have to look at bit more into that I think.

**Comment by feeef** [comment]
I think that the palette should be locked as soon as you are in bitmap mode and unlocked when you are in vector mode as this dynamic swatch feature is only useful in vector mode. No need for an option here.

**Comment by feeef** [comment]
However, in vector mode, this feature is required as every single stroke is linked to a swatch. Working with 1000 colors from the wheel would create 1000 swatches. In that case, it is better to let the user create its own palette and avoid overloading his project file without being aware of it.

Vector drawings are not made to use that many colors anyway. It is the point of having a bitmap engine for proper painting (like backgrounds).

BTW, we also need to fix/redo the bucket tool on the vector engine

**Comment by CandyFace** [comment]
Hmm yes that makes sense, however this needs to be better explained, ideally without having to look at a manual, otherwise we might run into similar issues being created.

**Comment by Jose-Moreno** [comment]
@feeef @CandyFace Thanks for coming to discuss about this issue. I must agree that even in toonboom it is at first a counter-intuitive way of presenting the colors. However even though this is the standard if we can find a way to improve on this for future users, I'm sure it will be welcome.

The idea of locking it was the first that came to mind, but perhaps as Francois mentions we could make it only available for vector layers, mainly because you are not supposed to change the color overtime on a background painting. However I still think the analogy on painting is valid.

It's possible that since people are accustomed to suites like Krita, GIMP or Photoshop, it would be worth looking into a SWATCH (bitmap) vs PALETTE (vector) kind of behavior.

**Comment by scribblemaniac** [comment]
Another possible way of handling this would be to make it easy to select no options from the palette. Then if no option is selected, the color wheel doesn't affect any of the swatches. In vector mode painting with no color selected should automatically create a new color (or maybe select an identical color if one exists).

**Comment by Kaikogf** [comment]
Hey people!

I am glad it came to my attention this kind of behaviour of the Color Palette list.
I can see so far that it was in need to be addressed and since I was strictly speaking about using it while working with Bitmap Layers I quite understand its behaviour when using vector layers

The part of "naming the swatch" was a bit confusing to me. But I am happy to read some solutions:

@morr. The safety lock is a good idea and @feeef suggested a more intuitive solution, to have it locked automatically in bitmap layers and unlocked on vector layers as well. 
By now I am going to apply the "free color" swatch solution suggested. 👍 

Good!

Thank you

**Comment by chchwy** [comment]
Duplicated issue of #755

**Comment by Kaikogf** [comment]
Yes, it was a kind of duplicated issue 👍
