### ISSUE TITLE
[ISSUE] The BRUSH tool is lagging too much when Onion Skin is activated

### ISSUE THREAD

**Issue by Kaikogf** [pencil2d/pencil#742]
### --Issue Summary--
Brush tool is lagging considerable when OnionSkin is activated (Bitmap layer only)

### --Actual Results
The strokes are lagging only in bitmap layers

### --Steps to reproduce--
- Open Pencil2D
- Select Bitmap layer
- Select the BRUSH tool size around 10
- Add several frames and draw something in each one noticing how much it is lagging, or not
- Activate Previous and Next OnionSin and start drawing some lines noticing how much they lag now

### --System Information--
+ Pencil2D Version:
Last build 23August2017

+ Operating System:
Windows 8.1 x 64bits

+ RAM Size:
32GB

+ Graphics Tablet:
HUION GT185 HD

---

**Comment by CandyFace** [comment]
I've thought about this one and I while I know that the optimization I did on my recent cursor PR, should make this a whole lot better, I don't understand why showing more frames would slow the rendering down so much. Just talking out loud to the other contributors here: I assume we're only rendering the other frames once right and then use cached images, because there should be no reason to update all of them continuously, as we're only interesting in updating the frame we're working on. If this is not the case, then we should definitely look into that.

**Comment by CandyFace** [comment]
@Kaikogf can you confirm whether this has been fixed in latest master?

**Comment by Kaikogf** [comment]
@CandyFace 

Yes, it its now working with no perceptible lag ! I even use Brush size 50 and it is working just fine. 👍 

Issue fixed
Thanks
