### ISSUE TITLE
1 pixel wide brush draws nothing; 2 pixel wide brush sometimes draws 1 pixel

### ISSUE THREAD

**Issue by Spark01** [pencil2d/pencil#806]
This is most noticeable when AA and feathering are turned off. Applies to both the pen and brush tools.

**Comment by Spark01** [comment]
I've figured out that this problem is a result of Qt not drawing ellipses well at very small sizes; simply drawing a rectangle instead when the brush size is less than or equal to 2 fixes the issue.

Probably not the most elegant solution, but of all the solutions I tried it produced the best results. Does anyone take issue with that/prefer to do it another way?

**Comment by CandyFace** [comment]
Actually I think the problem lies in that the spinbox is taking in ints, while the brush size itself is in floats.. so while the slider goes from say 1-2, the brushSize outputs 0.2, 0.4.

You can verify this by dragging the slider slightly, noticing that the crosshair grows and that you can draw with a 1px stroke.

**Comment by Jose-Moreno** [comment]
@Spark01 I just noticed that using 2 px brushes literally creates 2 pixels instead of 4. 

**Pencil2D**
![image](https://user-images.githubusercontent.com/4912907/33244566-07b49494-d2c8-11e7-8900-67bbc402214f.png)

![image](https://user-images.githubusercontent.com/4912907/33244572-3076bf6a-d2c8-11e7-96aa-04d652e74a01.png)

This is why normally brushes work as circle dabs. It should be a matrix array of pixels 1 by 1 = 1px, 2 by 2 = 4 px, 3 by 3 = 6 px and so on. It works like this in photoshop. however when you get a 4 by 4 array, the corner pixels are slashed starting to resemble a circle.

**Photoshop**
![image](https://user-images.githubusercontent.com/4912907/33244585-52a977c6-d2c8-11e7-8c9d-1012b5103dfc.png)

**Comment by chchwy** [comment]
Might have been resolved in 28 Nov 2017 build. Please check.

**Comment by Spark01** [comment]
Yep seems to be fixed,
