### ISSUE TITLE
Internal Error- Pencil 2D Issue

### ISSUE THREAD

**Issue by ZoruaSparda** [pencil2d/pencil#808]
FileManager::save
strFileName = C:/Users/Zorua/Pictures/Animations/hack link fun skit.pclx
strTempWorkingFolder = C:/Users/Zorua/AppData/Local/Temp/Pencil2D/hack link fun skit.Y2xD/
layerCount = 5
layer[0] = Layer[id=1, name=Camera Layer, type=5]
layer[1] = Layer[id=2, name=Vector Layer, type=2]
layer[2] = Layer[id=5, name=Bitmap Layer, type=1]
layer[3] = Layer[id=4, name=Bitmap Layer 2, type=1]
layer[4] = Layer[id=6, name=Sound Layer, type=4]
- Layer[4] failed to save
Layer::save
strDataFolder = C:/Users/Zorua/AppData/Local/Temp/Pencil2D/hack link fun skit.Y2xD/data
- Keyframe[1] failed to save

Error Display
Title: Internal Error
Description: An internal error occurred while trying to save the file. Some or all of your file may not have saved.

System Info
Pencil version: 0.5.4
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 10.0.15063
Product name: Windows 10

I would really like to know what is the issue in this scenario and how I can fix this problem/bug so I can animate my skit. Thanks. 

This only occurs when trying to save my project.

**Comment by CandyFace** [comment]
Hi ZoruaSparda

You're using a very old version of Pencil2D, please try the latest release candidate 0.6
http://pencil2d.github.io/download/

**Comment by Jose-Moreno** [comment]
@ZoruaSparda Hi, if you really have version 0.5.4, we reccommend upgrading the software to the latest version found here:

https://github.com/pencil2d/pencil/releases

However if you still have Pencil2D open and don't want to lose work. You should be able to save by deleting the sound layer and saving. This was caused by an issue where a sound file that was previously deleted would retain data on an empty keyframe on the sound layer. so deleting that keyframe / layer would allow you to save the file properly.

**Comment by ZoruaSparda** [comment]
Thank you. I have lost some of my work but it's nothing fatal. I would prefer back if there is another problem. ;)

**Comment by Tyor123** [comment]
Im using the latest version but this error it's still there!

**Comment by Jose-Moreno** [comment]
@Tyor123 This issue is closed because it pertained to an older version, but there's another issue that was left open to keep track of this problem and developers are investigating how to solve it.

Let me ask you by the way, is your operating system also Windows 10 by any chance?
