### ISSUE TITLE
[Feature Request] Add video export support to command line interface

### ISSUE THREAD

**Issue by scribblemaniac** [pencil2d/pencil#810]
Currently Pencil2d's command line interface only supports export as an image sequence, but now that the sound and video export is working, the CLI needs to be updated accordingly. Additionally, the image sequence export got left behind during [this refactor](https://github.com/pencil2d/pencil/commit/dd8daf7e41fd9e2fc3787e80ac28e44412eb7343) and should be moved as well.

Relevant code:
- https://github.com/pencil2d/pencil/blob/master/app/main.cpp#L57-L185
- https://github.com/pencil2d/pencil/blob/master/core_lib/interface/editor.cpp#L692-L719
- https://github.com/pencil2d/pencil/blob/master/app/actioncommands.cpp

**Comment by J5lx** [comment]
I think I’ll whip this up this afternoon unless somebody else wants to do it.

**Comment by J5lx** [comment]
I just noticed the program currently uses a private instance of ActionCommands in MainWindow2, so I can’t easily move the cli image sequence export to ActionCommands as you suggested because it’s not possible to call any methods on ActionCommands from handleArguments() without making MainWindow2::mCommands public or moving lots of other stuff around. I believe option 1 is a rather crude “solution”, and option 2 takes some time, so I think I’ll leave it as is for now and then hopefully do a proper refactor separately.
