### ISSUE TITLE
Ink/Pen Tool Pressure Sensitivity does not function with Surface Pro 4

### ISSUE THREAD

**Issue by diegog7** [pencil2d/pencil#829]
This is the only software I have found that has an actual onion skin, isn't pixel based, and doesn't crash.  I want to thank everyone involved in making it.  I've found it very enjoyable.  Would be nice if SP4 was actually compatible with at least one piece of software.  The Surface Pro is the ugly duckling of the drawing tablets.

### --Issue Summary--
When I select the pen tool, check Pressure check box on, and draw using the Surface Pro 4.  The line is drawn at only the brush size selected regardless of how much pressure I apply on the screen.

### --Actual Results
The brush size was always the selected brush size when painting with Pressure check on.

### --Expected Results--
I expected the brush size to range from a very small size to the selected brush size.

### --System Information--
+ Pencil2D Version:   0.6.0

+ Operating System:   Windows 10

+ RAM Size:   4 GB

+ Graphics Tablet:  Microsoft Surface Pro 4

**Comment by chchwy** [comment]
Hey @diegog7 Thanks for reporting

About surface pro's pen pressure issue I found some info on the internet.
Basically, you need to install two things from https://www.microsoft.com/en-us/download/details.aspx?id=49498 
- The Surface Pro Drivers, (SurfacePro4_Win10_xxxxxx.msi)
- Win Tab, (Wintab_x64_xxxxx.zip)

I can't test it by myself since I don't have a Surface pro 4.
Please tell us how it goes. cheers.

**Comment by ManuAros** [comment]
@chchwy 

Hello!
I installed the files you mentioned on my Surface Pro 4 but unfortunately I could not see any difference. The pen works but without pressure sensitivity. If there is anything you'd like to test to come to the root of the problem I'm willing to work with you to solve it. Unfortunately I'm no programmer but I'd help you with any kind of test runs you'd like me to do and report back. It would be huge step forward for Pencil to get this to work on the surface book pro. :)

**Comment by chchwy** [comment]
Hi @ManuAros 
Unfortunately we don't have Surface pro 4 device to test, all the solutions are from [Krita forum](https://forum.kde.org/viewtopic.php?f=281&t=129080).

Could you please follow the instructions of the link? In the end of thread, the user installed `Visual C++ 2010 Redistributable 64-bit` and it works.
https://forum.kde.org/viewtopic.php?f=281&t=141331

**Comment by J5lx** [comment]
@ManuAros Could you try to use your Surface Pro with [Krita](https://krita.org/) and let us know how it goes? Since Krita relies on some of the same technology as Pencil2D, this might help us pin down where exactly the problem originates. Maybe you could also list some other programs where tablet input works or does not work as well.

**Comment by ManuAros** [comment]
@chchwy  @J5lx 

Ok. problem solved. I used Krita to test pen compability. At first it did not work. So I installed VC++2010 but that was not enough. I then re-installed my Wintab drivers because I remembered that I had installed those before. I re-installed Wintab and pen pressure (via Wintab) works both in Krita and Pencil2D. 👍 and it's just awesome.  Thanks for the heads up !!

**Comment by chchwy** [comment]
@ManuAros Cool, happy to know that works.
I think we could put this in the FAQ, i'm closing this issue.

**Comment by diegog7** [comment]
I have downloaded the same thing as ManuAros when I was trying out Krita.  But it turned out that those drivers make every other piece of drawing software NOT work.  Either Krita/Pencil 2D work(with the band aid drivers), or everything else works (without the band aid drivers).

Using those drivers causes much more issues for me, so I can't use those.  The Microsoft Surface Pro 4 is pretty lousy hardware.

Thanks for asking.

**Comment by ManuAros** [comment]
@diegog7 

Sorry to hear you have that problem. For me Krita, Sketchbook and Leonardo paint programs works like normal along side with Pencil2D. Maybe if you do a workaround like explained here:

https://www.facebook.com/notes/michael-ng/surfacepro-4-and-wintab-driver-toggle/10156922702355503

then you could maybe still use both programs.
