### ISSUE TITLE
Can't open after download

### ISSUE THREAD

**Issue by Zoruax** [pencil2d/pencil#844]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

after i download and try to run the program it says there is a file missing, yet i can see it in the folder

**Comment by Jose-Moreno** [comment]
@Zoruax Hi, we are missing key details from your report. Please state:
1) What operating system you are using
2) What is exactly the file that says it's missing

If you're using windows there are a few possible cases that are happening:

a) it's possible that your file is getting blocked due to the OS strict file policy coming from other computers. To unblock the zip file so it allows to extract all the actual files you need to right click on the downloaded zip file > go to properties > on the general tab look for a button that says "unblock" and then press accept.

b) Check your antivirus, since it's possible it might be aggressively deleting any of the files, so you'd have to tell it to ignore the folder where you downloaded Pencil2D.

c) Ultimately, it's possible you're missing a key component from the windows system which you have to get from microsoft. If possible please comment with the exact error message you're getting, or post a screenshot as a comment (you can copy and paste from clipboard directly into the github comment)

If you're using any other operating system, please attach the info accordingly.

**Comment by Jose-Moreno** [comment]
**Closing**
---
_**Reason**_
OP didn't provide enough information on their initial report. After providing windows targeted support, OP never commented back after 6 months so further troubleshooting to discard possible bugs is impossible.
