### ISSUE TITLE
the program "lags" and experts at a different speed

### ISSUE THREAD

**Issue by 0-name-0** [pencil2d/pencil#845]
### --Issue Summary--

animation is not as fast as it should be.

### --Actual Results--

When I play my animation it's slower than when i export it and this is a real problem for me because a lot of my projects include lip-syncing and when the speed messes up i can't tell if the animation is smooth/"on-time."

### --Expected Results--

the speed should be how fast the fps is set to and not different each time

### --Steps to reproduce--

- open pencil2D
- create sound layer (with audio) and/or create a few frames on each layer
- go to beginning and play the animation

### --System Information--
+ Pencil2D Version:

Nightly Build 2017-10-23
+ Operating System:

Windows 10 (64-bit)
+ RAM Size:

Idk I can't find it (sorry)
+ Graphics Tablet:

Wacom Intous PT S

---

**Comment by Jose-Moreno** [comment]
@0-name-0 Hi, sorry to hear you're having issues. However this is a problem that was already fixed. Since another animator reported a similar issue and I tested it among others so developers could fix it. 

Since you seem to be using an older nightly build, allow me to let you know that the Pencil2D Team has already released version 0.6 of Pencil2D. There's even a newer Nightly Build from Dec 20th with even more improvements as well.

Please download either the stable version of the latest nightly build at: http://pencil2d.github.io/download

Try it out and please let us know if this fixes your issue. If not then we would have to investigate further.

**Comment by chchwy** [comment]
Hey @0-name-0 
I just made some improvements it so the frame rate is more accurate now.

Please download the latest nightly build (should be 1 Jan 2018), and tell us how it goes.
http://pencil2d.github.io/download/#nightlybuild

**Comment by 0-name-0** [comment]
I found out that part of the problem was happening because i made the camera layer too big, but other than that, the problem is fixed! Thank you!!
