### ISSUE TITLE
whole animation mirrors in export

### ISSUE THREAD

**Issue by rgburl** [pencil2d/pencil#847]
I've just started using Pencil 2d.  I downloaded the latest night build, but, it still mirror images my whole animation on export.

Thank you.

**Comment by chchwy** [comment]
Hi @rgburl 
Can you check your horizontal flip button? Was it pressed?

![Imgur](https://i.imgur.com/5N6WjLg.png)

**Comment by rgburl** [comment]
thank you.
yes horizontal button showed "on" and it wouldn't click "off" no matter what i tried. but it played perfectly in the window, just not on export.

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 5, 2018 at 12:12 AM, Matt<notifications@github.com> wrote:   
Hi @rgburl
Can you check your horizontal flip button? Was it pressed?

**Comment by Jose-Moreno** [comment]
@rgburl Is it possible that you can share a screenshot of your Pencil2D interface? or even better if you can share the file to help the developers investigate this issue? Otherwise if you managed to fix the issue would you mind sharing what you did to fix it? Thanks.

**Comment by Kaikogf** [comment]
I have tested it (win8.1x64bits) with the last build (Jan2018) and I am not able to replicate this behaviour. 

Everything is working fine here, even when flipping its content V/H the whole animation is exported correctly (tested on AVI, MP4, WebM)

**Comment by Jose-Moreno** [comment]
@rgburl Don't worry, and thank you for responding back! Hopefully we can find a way to help you out and fix this issue for you and for others who might experience a similar problem :smile:

**Comment by rgburl** [comment]
Here is the file. I made it with everything going left to right. But somehow the whole thing got mirrored. If I click on mirror to make it go left to right again, the mirror button won't click off. Maybe I'm missing something simple?Thanks.
Also, if you haven't already, please check your documentation to let everyone know a selection can be rotated by holding, think it's shift key and dragging. I had to do a Google search for it because i didn't easily see it in documentation.  
Your app is a good one between Animation Desk and Open Toonz because the last i checked on Animation Desk, they don't allow importing images into each frame, only as background image. And, OpenToonz has so many options, it's hard for me to even get started. I probably will wrestle with it at some point, but right now i just want to do very simple things, am learning, and your interface is more friendly.
I currently use Krita and your Pencil 2d app.
Ritagail B.


Sent from Yahoo Mail on Android 
 
  On Thu, Jan 11, 2018 at 10:20 PM, Kaíko<notifications@github.com> wrote:   
I have tested it (win8.1x64bits) with the last build (Jan2018) and I am not able to replicate this behaviour.

Everything is working fine here, even when flipping its content V/H the whole animation is exported correctly (tested on AVI, MP4, WebM)

**Comment by Jose-Moreno** [comment]
@rgburl Hey, thanks! although since i'm using github to write to you we didn't get a file attachment. Is it possible for you to upload it to mega.nz, dropbox, google drive or any other service you consider and post the direct link in a reply? Sorry to trouble you with that, but it's only because we can't see the attachments if you reply directly from your email client.

Regarding the documentation I agree there are many features that are lacking documentation, but im afraid it will take us some time before overhauling those. Hopefully we can do it before march. thanks again for your input!

**Comment by rgburl** [comment]
ok. sorry. had lost password to here, then it wouldn't let me upload that type of file, then google drive told me i had outdated version, so wrestled with signing up for dropbox and had to download their app....soooooo..... almost hope you DO find it's a bug and not simply "user error" on my part.

to refresh your memory, i created this with everything going left to right. if it comes up going right to left, please hit mirror button, then see if you can get it to switch back off. hope the link to file works. thanks.
https://www.dropbox.com/s/490b3qtgfvwptow/secondtestb.pclx?dl=0

**Comment by Jose-Moreno** [comment]
@rgburl I just tested the file. I'm afraid, I'm not getting the mirror stuck. When I ticked and unticked the mirror view button the original animation is going from right to left...so here's what I think happened. 

The only logical explanation is that without realizing it, you drew everything from the beginning with the mirror view mode activated, that's why when you export you get the video flipped. Because without the mirror mode the character is actually entering from right to left, and not from left to right. I'll attach a gif to demonstrate, please take notice of my display panel (where the view flip buttons are located)

![pencil2d_possible_error](https://user-images.githubusercontent.com/4912907/34909535-ee7d4ede-f870-11e7-9a30-c185f1ba54ed.gif)

It's still weird that you can't uncheck the button state, but that is a behaviour that I'm not getting on the latest version . 
Can you try going to the view menu and see if the horizontal flip function restores the view so your button should become unticked. Or try pressing Shift + H to invoke the mirror view function and take notice if the arrow button becomes "unpressed".

![image](https://user-images.githubusercontent.com/4912907/34909570-c5ba1738-f871-11e7-8d03-99f843635463.png)

Along with that, since there is no way to flip the export result from Pencil2D at the moment, I'd suggest you finish it with the mirror view on as you intended, export it (it will come out un-flipped) and then with a video editor you flip the video again so you have the result you wanted.

For video editor you can use windows movie maker (which has a mirror horizontal feature) which should come with your computer. Or get the free and open source shotcut https://www.shotcut.org/ and apply a "rotate" filter and input a negative "scale" (-100%) to invert the video.

**Comment by rgburl** [comment]
thanks. will try it in the next few days and let you know, sooner if possible.

i appreciate how much time and diligence you have taken.

**Comment by rgburl** [comment]
Sorry it took me so long.  Nothing I tried took the "horizontal hold" off.

You may be right, I may have accidentally clicked it on at the beginning.

I'm working on a series of simple things, and the first one has exported fine.  Thanks!

**Comment by Jose-Moreno** [comment]
@rgburl It's alright!. What's important is that there's a solution. If I may give provide some advice, next time take your time to prepare your workspace and your tool to make sure things will export correctly. Consider it part of the whole process of animation. So If you feel unsure about the tool, make a small test, for example just draw a simple line moving and export it. If everything works fine, then you can save your file and begin your process. Either way have fun and keep up the nice work :smile:
