### ISSUE TITLE
Animation wont play on more than 12 FPS

### ISSUE THREAD

**Issue by Hoparduc-Snowpanther** [pencil2d/pencil#851]
okay so it wont play on 24 speed

even if i set it to 24, it still plays on 12
please fix  this issue

**Comment by Jose-Moreno** [comment]
@Hoparduc-Snowpanther Hi, developers require more information to investigate issues like this. Please let them know:

1) What operating system are you using?
2) Which version of Pencil2D are you using? (Pencil2D > help > about menu)

Also, did you change the FPS on the timeline? You can enter the number you want directly.

![image](https://user-images.githubusercontent.com/4912907/34789922-09d13a98-f60e-11e7-9c39-a130736496dd.png)

If you did, was it before starting playback, or during playback? if you change the speed during playback the speed of the playback will not change until you stop and start it again.

Also, even if you set it at 24 speed, if your computer does not have a powerful CPU and enough RAM, your preview playback might come out rather slow, in such case you might have to export the movie to "preview" how it's going. Although it's rare for people to have computers with low specs nowadays, it's still a real possibility that can affect the outcome of the playback speed.

**Comment by Hoparduc-Snowpanther** [comment]
i am using linux. 
the version of pencil is 0.6.0
it doesnt matter when i change the speed, it wont change the speed of the playback
and yes i changed it there

**Comment by Jose-Moreno** [comment]
@Hoparduc-Snowpanther Thank you for the quick reply! if you're using a linux distro do you know if it's a 32bit or 64 bit version? (also what distro? i.e Ubuntu, Archlinux, etc).

Either way please try the latest nightly build (Jan 9 2018) APP Image, to see if it's possible that the issue has been fixed already. Please download it here:  https://drive.google.com/open?id=1VHITDSfmIQCfTyz2mV8tu5ZYdztNjduS

If the problem still persist for you in this Nightly build, I'll try to test it on a linux laptop I have to see if I can reproduce the issue, that way I can help to pinpoint the issue and devs can assist us in fixing this problem.

**Comment by Hoparduc-Snowpanther** [comment]
i have tried the nightly build, but it would not start. i am using the 64bit one. should i try the 32bit one and see if it fixes the issue?

**Comment by Jose-Moreno** [comment]
@Hoparduc-Snowpanther Hey. Well using 64 or 32 bit software depends on your system. If the nightly build does not start it could be because of the following:

1) When using an app image you have to right click on the app image go to properties and "allow executing file as program" (here's a guide, just in case: https://itsfoss.com/use-appimage-linux/)

2) You indeed have a 32 bit linux OS and since the appimage executables only comes for 64 bits linux distros (32 bits have to be hand made) it's not starting due to that. However if Pencil2D has been working before for you, most likely this isn't the issue.

**Comment by chchwy** [comment]
Hey, @Hoparduc-Snowpanther thanks for reporting.

Did you set the FPS to any other numbers less than 12? like 6, or 8? Does the speed change?
I want to find out it's a performance issue or not.

**Comment by Hoparduc-Snowpanther** [comment]
it does not play on anything other than 12fps. and yes pencil has been working for me before

**Comment by Jose-Moreno** [comment]
@Hoparduc-Snowpanther If possible can you tell us what Linux version and distribution you are using? Is it Ubuntu? or something else? If you don't know please try the following guide for terminal commands

https://www.if-not-true-then-false.com/2010/show-linux-version-distribution-distro-system-information/

***
**Note for Developers**
@chchwy I'm thinking, since on Windows most of the properties are hard coded on a registry table, what is the registry equivalent for Linux systems? maybe the FPS value is not being properly written on that table either due to permissions or a different cause that is dependent on the Linux version of the user. Considering other Linux users are not having this issue, It could be specific to the user's Linux flavor as well.

**Comment by Hoparduc-Snowpanther** [comment]
i am using ubuntu yes

**Comment by Hoparduc-Snowpanther** [comment]
thank you very much!
and i am glad i could help!

**Comment by martinvanzijl** [comment]
I can also reproduce this on my Ubuntu 14.04. I've got a fix working for me - will send a Pull Request shortly.

**Comment by chchwy** [comment]
Hi @Hoparduc-Snowpanther
Could you please download the 23 Feb 2018 Nightly build and confirm this is fixed?
http://www.pencil2d.org/download/#nightlybuild
