### ISSUE TITLE
Application on Latest Build (1 December 2017) Would not Start

### ISSUE THREAD

**Issue by Paul-Stompbox** [pencil2d/pencil#852]
### --Issue Summary--

Upon downloading the current bulid of Pencil 0.6 (December 2017), and then extracting the entire .zip folder to the Desktop, as I did for the previous 2017-08-22 build, when I open Pencil2D.exe in the extracted folder, an error would pop up and the application would not start.

### --Actual Results--

Double clicking the executable file would show the popup:
"The application was unable to start correctly (0xc000007b). Click OK to close the application."
The only option to click is OK and when I do so, the application does not start.

### --Expected Results--

As the previous version worked, and it did not show this popup, it would open a new blank Pencil2D application screen as expected. 

### --Steps to reproduce--

Download Pencil2D 0.6, extract it to the desktop in Windows 8.1, and then open Pencil2D.exe.

### --System Information--
+ Pencil2D Version: Version 0.6.0 (1 December 2017), (Latest stable build as of the time of this post.)

+ Operating System: Windows 8.1, 64bit

+ RAM Size:  8 GB

**Comment by Jose-Moreno** [comment]
@Paul-Stompbox Hi. Windows has a particularly annoying issue that tends to block the contents of any zipped file that comes from a different computer, I have Windows 7 and it becomes worse on every upgrade.

There are a few possible cases that are happening, and meanwhile a dev takes a look at this, please test the following methods to rule them out as possible sources for this issue:

a) it's possible that your file is getting blocked due to the OS strict file policy coming from other computers. 

You have to unblock the ZIP file and re-extract it's contents, so it allows to extract all the actual files you Pencil2D requires.

Right click on the downloaded zip file > go to properties > on the general tab below the attributes look for a button that says "unblock" and then press accept.

If you require a visual guide please take a look at this tutorial I did last year (it has english CC since sometimes i speak too quick or too softly):
https://www.youtube.com/watch?v=S8nS7aeBD04

b) Right click on Pencil2D.exe > Go to properties > Go to Compatibility Tab > Check the "Execute this program in compatibility mode for: " > Select Windows 7

c) Check your antivirus, since it's possible it might be aggressively deleting any of the files, so you'd have to tell it to ignore the folder where you downloaded Pencil2D.

**Comment by chchwy** [comment]
Hi @Paul-Stompbox 

I guess the Visual C++ Redistributable caused the issue (Visual C++ is the development tool of Pencil2D). We did change the Visual C++ version on last November. It explained why the 22 August version was working but v0.6 is not.

Could you go to `Control Panel` -> `Programs`, uninstall `Microsoft Visual C++ 2015 Redistributable` and reinstall it? You can download it from <https://www.microsoft.com/en-us/download/details.aspx?id=48145>, `vc_redist.x64.exe` is for 64bit version and `vc_redist.x86.exe` for 32bit.

**Comment by Jose-Moreno** [comment]
@Paul-Stompbox Sorry to bother as I'm sue you're no longer interested in Pencil2D, but can you test if the comment previously made by chchwy as well as using the latest development build fixes this problem for you or not? Are you still using Windows 8.1? Please let us know so we can have investigate this further.

For the latest development version please download it here http://pencil2d.org/download#nightlybuild

**Comment by Jose-Moreno** [comment]
**Closing**
---
_**Reason**_
OP was approached with different solutions following their initial report. After providing windows targeted support, OP never commented back after 6 months so further troubleshooting to discard possible bugs is impossible.
