### ISSUE TITLE
(REQUEST) Changing FPS during animation

### ISSUE THREAD

**Issue by infinityglitches** [pencil2d/pencil#863]
This is not really a bug but more of a request or enhancement.

Could you add a feature where I can change the FPS during the animation, like lets say my animation is running 2 FPS but at one point in the animation, let's say from frame 73 to 189 I want it to run at 6 FPS, then go back to normal 2 FPS, and I can do this multiple times, because in my animation (and many others) there are things like fight scenes, and fight scenes at 2 FPS isn't that good lol.

Thank You,
infinityglitches

**Comment by Jose-Moreno** [comment]
Hmm interesting. This would be like a time-remap effect kind of thing, which could prove useful (for reference look at After Effects time remap). 

Normally to achieve these effects what one has to do in any software, even studio-based software like toonboom or tvpaint, is to "hold" the drawings for more or less frames to give the speed you're looking for.

For example, say you're working at 24 fps. If you want your animation to go at 2 fps at one part, that is 2 frames every second, you have to hold, or keep showing, the first drawing for 12 frames (that is use the same drawing for 12 frames straight), and hold the second drawing for another 12 frames, effectively using up a whole second for just 2 drawings.

If you want it to be 6 fps, you have to hold each drawing 4 frames each. Because 24 divided by 6 = 4; and so on.

***
Note for devs
Sometimes in video editors they have those kind of effects. In Blender VSE they have a "speed" strip, which can be used to achieve such effect, but you'd have to duplicate the main animation a lot to work different parts with different speeds, so you have to accommodate the strip for the lost or added time (if you make the fps low, you're adding frames, expanding time, if you make the fps higher you're subtracting frames, contracting time.

**Comment by CandyFace** [comment]
I personally think this goes against being able to set playback fps, since you're messing with frames per seconds depending on some extra factor. I've seen it implemented in some pixel drawing applications with animation features but that's because they didn't have a frame by frame timeline.

The purpose of the timeline is imo. to allow such freedom by placing the frames wherever you feel like.

In some way I can see the benefit because we could most likely get smaller projects because of less frames and thereby saving memory and space, but on the other hand... frames lose their meaning, because 12 frames is not 12 frames anymore.

**Comment by infinityglitches** [comment]
Jose-Moreno, although that would make sense, First of all, it would be easier if there was a way to do the thing I said, and second of all, if the maximum number of frames is 999, then the animation would be shorter because you would have to spend more time on one drawing then have it so you could just have different FPS at different times.

and CandyFace, you could have a 12 FPS base, which is like your first FPS, then have like 4 or 5 different bars next to the FPS bar which all have a range bar so you could select which time or frame  and then have that move at a different FPS then stop at the end of the range selection. It wouldn't change the fact that 12 FPS is the starting base of the project.

**Comment by chchwy** [comment]
Won't implement this as it will introduce unnecessary complications and the timeline can now extend to 9999 frames.
