### ISSUE TITLE
Inconsistent use of Helvetica

### ISSUE THREAD

**Issue by J5lx** [pencil2d/pencil#874]
While working on #872 I noticed that in some places the font is explicitly set to Helvetica (most notably in various timeline-related widgets: timeline, timecontrols, etc.), while most other code simply uses the default font. It might be a good idea to decide on one solution here: Use Helvetica everywhere, or nowhere. If we use it everywhere, though, we should probably at least think about the cases where it isn’t available. My system, for instance, does not have it and uses DejaVu Sans instead, which is (indirectly) based on Verdana rather than Helvetica, so it kinda defeats the purpose. Not like it’s super important (in the end a font is a font), but I just wanted to drop it here for thought.

**Comment by CandyFace** [comment]
I disagree, a font is not just a font. some UI's are terrible, simply because of the font choice. Font choices are always at the bottom of the "todo" stack or left to be chosen by the engineer because nobody cares enough to figure out what to use. The result of that is that we end up with 'Arial' more often that not because it's usually the default choice. 

Whether it makes the UI more readable (especially with smaller font sizes) or make it more slick to look it, there are plenty of things to be considered when choosing a font.

I think we should decide on a good UI font, and not one that's necessarily available on our system, we could just include it as a resource.

UI font should be: sans-serif, the font should just be there and be readable.

My candidates would be:
* Roboto 
* Lucida Grande

Both are fonts made for clarity and UI usage, Roboto for Android and Lucida Grande for OSX.

It's still low priority compared to everything else though :P

**Comment by J5lx** [comment]
I do get your argument about engineers doing design choices, but the default fonts we’re talking about here were not chosen by some sort of indie developer, but by large corporations and communities with dedicated design teams. We’re not talking about Arial here (anymore?), we’re talking about Segoe UI (2007-), Cantarell (2011-), Oxygen (?-), San Francisco (2015-), Helvetica Neue (2014-2015) and, yes, Lucida Grande (2001-2014). In fact, Helvetica Neue appears to be the only one of these fonts remotely related to Arial. To me personally, trying to outdo the designers behind these choices as mere indie developers (see where the circle ends?) feels a little awkward. As you wrote, there are plenty of things to be considered when choosing a font, and I personally would rather leave that choice to the same people who also came up with the rest of the design (vaguely related: #550).

Lastly, while I see why you made your choices, I’d like to note that Lucida Grande might not be licensed appropriately for us to redistribute it (?), and that Roboto has faced some strong criticism in the past. Last I heard they fixed some of the complaints in a newer version, but I honestly don’t know how that affected the big picture. In that regard, I might as well throw some of the better-known free fonts in, such as Cantarell, DejaVu (both GNOME) and Noto (Android). Nonetheless, my preference towards relying on the defaults still stands, I look forward to your thoughts on it!

**Comment by CandyFace** [comment]
> We’re not talking about Arial here (anymore?), we’re talking about Segoe UI (2007-), Cantarell (2011-), Oxygen (?-), San Francisco (2015-), Helvetica Neue (2014-2015) and, yes, Lucida Grande (2001-2014)

That's true, The default value however seems to be that the "algorithm" will decide for you. So for all we know, the default font could be 'Helvetica'. If we instead set it to use the default System font explicitly, then we would always be sure that it would make the most "native" choice.

I did look into the Lucida Grande EULA and you might be right about redistributing it, so maybe that's not a good idea after all. 

Anyway I agree that whatever font we use, it should be consistent and never fixed to specific values.

**Comment by J5lx** [comment]
Hmm, could you clarify what you mean by the default value decided by the algorithm and setting the system font explicitly? Isn’t Qt using the default system font by default?

**Comment by CandyFace** [comment]
Not quite, although i'm not sure what goes into the 'font matching algorithm', the documentation for QFont just says
> 
QFont::AnyStyle | ? | leaves the font matching algorithm to choose the family. This is the default.
-- | -- | --

http://doc.qt.io/qt-5/qfont.html#StyleHint-enum

So I would assume that if you for example had Helvetica installed, then it would use that but because that's not the case, it's using the system font.

What I meant by explicitly setting the font to what the system uses:

QFont::System | ? | the font matcher prefers system fonts.
-- | -- | --

**Comment by J5lx** [comment]
Have a look at the description of the QFont::StyleHint enum as a whole, though (emphasis by me):

> Style hints are used by the font matching algorithm to find an appropriate default family **if a selected font family is not available**.

Thus, as I understand it, this is only used when searching for a fallback for an explicitly selected font. On the other hand, I found this piece of information for [QApplication::setFont()](http://doc.qt.io/qt-5/qapplication.html#setFont):

> On application start-up, **the default font depends on the window system**. It can vary depending on both the window system version and the locale. This function lets you override the default font; but overriding may be a bad idea because, for example, some locales need extra large fonts to support their special characters.

Which reads to me like Qt does in fact default to using system default fonts.

**Comment by chchwy** [comment]
All the `Helvetica` things are legacy code from previous pencil development, I think that's because Pencil was Mac first at that time. And `Helvetica` is one of the system built-in font on Mac. (not on Win & Linux) After I picked up the project, I intentionally leave the font setting blank when making new interfaces.

And don't forget that every language has its own font.
Take a look at this page (and it's just Windows):
https://msdn.microsoft.com/en-us/library/dn467844(v=vs.85).aspx

**Comment by J5lx** [comment]
Oh, absolutely… the [list for Google’s Noto fonts](https://www.google.com/get/noto/) is just as long… So would it be fine if I remove the remaining places where the font is set explicitly?

**Comment by chchwy** [comment]
@J5lx yeah it could be a good idea.
