### ISSUE TITLE
Export Issues: animation does not line up with the audio

### ISSUE THREAD

**Issue by RandRAnimationsOfficial** [pencil2d/pencil#879]
Okay, I am really sorry for not following the guidelines but I don't really know how to put this through and I don't know how to fill out most of the information. When you export your animation as a movie, some reason the animation does not line up with the audio and ends up speeding up. I have tried finding other ways to fix this problem but was not successful. I hope you will update this software, it is really excellent in my opinion.
                      - R&R Animations -OFFICIAL-

**Comment by chchwy** [comment]
Hi @RandRAnimationsOfficial 
Could you please test this with our latest nightly build?
http://pencil2d.github.io/download/#nightlybuild (You can download it here!)

We have done some improvements on the playback accuracy recently, and it will be included in the next release.

**Comment by RandRAnimationsOfficial** [comment]
It's doing the exact same thing as the previous update    :(

**Comment by Jose-Moreno** [comment]
@RandRAnimationsOfficial Is it possible that you can upload the files so we can take a look? It's rather difficult to gauge the issue since it's not happening to other users. Can you also let us know which operating system you are using?

Also, this step would be for speeding investigation but it won't guarantee a fix until there's concrete evidence of how the problem occurs. So considering that you might be needing to finish your work soon, I might suggest that while we investigate the file  you upload, you could try to export both an image sequence and the sound separately from pencil2D and then join them up inside a free video editor (like Kdenlive)

This way it would be easier to properly match them up and create a full video to upload on the web.

**Comment by chchwy** [comment]
It's fixed in 0.6.1
