### ISSUE TITLE
Bitmap/Vector content does not stick to the canvas when motion tweening

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#912]
### --Issue Summary--
When you draw something on a bitmap or vector frame, then make a camera frame and translate, rotate or scale it, the content will follow the motion when you go back to the bitmap or vector layer and play or just move the scrubber.

### --Actual Results--
Bitmap and vector content moves with the camera

### --Expected Results--
Camera tweening shouldn't happen when you're on a bitmap or vector layer.

### --Video or Image Reference--
![tweening](https://user-images.githubusercontent.com/1045397/36947014-7f05de22-1fc6-11e8-9e47-8786fc664a73.gif)

### --Steps to reproduce--
+ draw something on a bitmap or vector layer
+ move a couple of frames ahead and create a camera frame
+ make a motion of some sort
+ go back to the bitmap or vector layer
+ interact with the scrubber within the motion tweened frames or just hit play,

### --System Information--
+ Pencil2D Version:
Nightly build: Commit 63d052a

**Comment by Jose-Moreno** [comment]
@CandyFace I think ideally we should have a "camera stand" mode and a drawing mode. This is something that most animation specialized apps do have, because in traditional animation the animator couldn't preview the camera movements on their own so they either had to "fake" it (moving the character in the paper as if the paper was the camera sensor) or they had to send the animation to the "camera man" to they could apply such motion and film it to see the result.

In Pencil2D would be great to keep the camera (layer) as an independent entity form the drawing, because most of the time you want to adjust your drawing independently from the camera movement. At least I've always thought that when I select the camera layer i'm sort of entering "camera mode", ready to "film" the animation after my motion is done, and when you select any drawing layer (bitmap / vector) you enter "drawing mode" to correct the animation.

These have to be separate tasks because that's how it works on most pipelines and applications.

**Comment by CandyFace** [comment]
Well we already have a "camera stand mode" and drawing mode, the bug is exactly that the motion tweening shouldn't happen when you're drawing.

**Comment by CandyFace** [comment]
Hmm my bad I somehow thought that the camera on "camera layer" already was its own identity where the view you have on bitmap and vector was different different but I see that's not the case... I forgot that the gray area is actually the camera, so the behaviour is intentional and makes sense. 

This is more of a UI/UX problem than a bug, so i'm closing the issue. A new discussion regarding how the camera should work though would be good I think, I've been talking a bit about on discord already.
