### ISSUE TITLE
Icons missing in Toolbox

### ISSUE THREAD

**Issue by tirbo** [pencil2d/pencil#916]
[
![pencil_ubuntu](https://user-images.githubusercontent.com/37225945/37227960-02d51916-23f0-11e8-8669-e55f1a40108f.jpg)
](url)
ubuntu 16.04
Уже давно не вижу инструменты.

**Comment by J5lx** [comment]
Confirmed on 64 bit Arch Linux with the Nightly Build from 2018-03-07 but not master at 3f335c89fe298cfc45ef143a81c9c641e2856f90. I wonder what the reason is…

**Comment by chchwy** [comment]
@J5lx  do you think this issue is related to the deprecated symbol defines in #917?
I don't have any idea why it happens.

**Comment by J5lx** [comment]
Nope, that change was introduced after the affected nightly build was released, so if anything it would have to be the reason why master is not affected. Given that the other changes after that nightly build are rather minor, I suspect that this bug is most likely related to the build environment or the AppImage packaging process. After all, the toolbox icons are vector images while most of the others are bitmap images, so maybe it’s just the SVG support that’s messed up.

**Comment by J5lx** [comment]
I just inspected the AppImage, and it’s indeed missing the SVG libraries and plugins. So I guess we’ll have to take a close look at linuxdeployqt again.
