### ISSUE TITLE
how do i convert from a pcx file so i can actually open my animation?

### ISSUE THREAD

**Issue by chiara198** [pencil2d/pencil#925]
### --System Information--
+ Pencil2D Version:

+ Operating System:

+ RAM Size:

+ Graphics Tablet:

---

**Comment by chiara198** [comment]
I STILL don't know how to use that weird preview thing soooo I'm making a separate comment. basically, I need to submit an animation for a contest, but I cant even pull the ones I made already up on my laptop because of the file type, is there a way to make the file accessible?

**Comment by Jose-Moreno** [comment]
@chiara198 To be honest your problem isn't super clear, so apologies if what i'm about to mention does not apply to your particular issue.

So, those filetypes (pclx) are only able to be opened with Pencil2D. There is not possible conversion to other files. If you want to show your animation through the web you have to export them as a video or a GIF file. If you want the other person to be able to open the file, then tell them to download Pencil2D and send them the pclx directly.

If you can't export your animation because you are using an older version of the software please go to pencil2d.org/download#nightlybuild and get the latest development version.

If you just can't open them in Pencil2D and are having an error while opening the files, please upload the pclx files you are having trouble with so a developer can assist you in figuring out what's the problem.

**Comment by chiara198** [comment]
ok, thank you. i might just try to download a different software. pencil 2d does seem a bit buggy for my taste.

**Comment by Jose-Moreno** [comment]
@chiara198 Sure, no problem, too bad we didn't continue the support thread, since I honestly don't fully understand what happened.

Hopefully you can find a software that suits your workflow better. Just to help out we have a list for other animation software in Pencil2D's tumblr blog, take care:

http://pencil2d-software.tumblr.com/post/145767476221/when-youve-worked-all-day-on-your-animation

**Comment by CandyFace** [comment]
You don't convert a pclx or pcx file to something else, you export your animation as a gif, a png sequence or a video. This is not a bug nor is it different from how similar animation software does it. Sorry to hear you leaving before we had this issue resolved properly, but it sounds more like you've misunderstood something rather than it being a bug in the software.
