### ISSUE TITLE
backup project before saving

### ISSUE THREAD

**Issue by CandyFace** [pencil2d/pencil#938]
We're seeing more and more people having corrupted projects in one way or another. As a measurement to prevent this, I suggest that we backup the old project file as soon as we press save. This will not prevent all cases where the project ends up being corrupted but it should make it possible to recover to the state before the project got corrupted.

Another thing is that we shouldn't write to the project file unless we know that the data has been stored correctly.

**Comment by Kaikogf** [comment]
I am too cautious about working with Pencil since it is not easy to be calm when we loose something that we have being working from a long time, and since I am using two different versions of it (last build and Pencil2D-Mypaint).
My workflow is similar to what you have described: I always duplicate the pencil-file I will start working before opening Pencil2D and when closing Pencil I use to check the one that was saved to see if it is working.... so I am doing it manually but your idea, that I think should be implemented as soon as possible, shows the same process but automatically.

Great idea.

**Comment by chchwy** [comment]
Let's put it into the 0.6.2 todo list

**Comment by chchwy** [comment]
I'll be doing it soon.

**Comment by chchwy** [comment]
Done in the nightly build 5 June 2018
