### ISSUE TITLE
Pencil2D 0.6.1.1 Linux Appimage -  Missing icons at tools

### ISSUE THREAD

**Issue by petr-akhlamov** [pencil2d/pencil#957]
After running of app in his tools missing icons, what which makes it difficult to it use.

### System Information
+ Pencil2D Version:
0.6.1.1

+ Operating System:
Simply Linux 8.2.0 (i386)
---
![pencil](https://user-images.githubusercontent.com/16255202/39465589-cd6d1952-4d2c-11e8-9025-3d2c2c3572b5.png)

**Comment by Jose-Moreno** [comment]
@petr-akhlamov Thank you for the report. I don't have a linux box handy, but i'll try to test this when I can in order to help the developers.

Have you tried this with a different distro using a LIVE CD? does the APPIMAGE behave the same on a different distro?

**Comment by chchwy** [comment]
@scribblemaniac  could you please have a look at this issue?
The missing icons occurred in #916 as lack of qt svg plugin, and I remember we had a very similar issue when releasing v0.6.

**Comment by scribblemaniac** [comment]
Yes, that change was missing from my build script, thanks @chchwy . Unfortunately when I incorporated the changes, it fails because `iconengines/libqsvgicon.so` doesn't exist. Anyone have an idea why this is happening?

**Comment by scribblemaniac** [comment]
It took longer than expected because I decided to switch to Lubuntu. The good news is that this issue should be fixed now, and thanks to the upgrade high-dpi support is now working as well.

@petr-akhlamov This issue should be fixed now. If you are still interested in using Pencil2d, you can download the fixed AppImage directly from this link: https://github.com/pencil2d/pencil/releases/download/v0.6.1.1/pencil2d-linux-i386-0.6.1.1.AppImage
