### ISSUE TITLE
[Request] migrate Pencil2D environment configuration from registry to an editable file

### ISSUE THREAD

**Issue by Jose-Moreno** [pencil2d/pencil#980]
### --Issue Summary--
It's been a while since I've seen the need for this. Normally there's a lot of "hidden" variables that are written to the registry (windows, possibly macosx and linux too) which directly manipulate Pencil2D's behavior. In my opinion these "system" variables along with other configuration values for the preferences dialog (most of the user choices and keyboard shortcuts too) should be written to a configuration file that can be edited by the user if there's choice. This file could be perhaps created and updated everytime the program starts, changes or quits just the same way the it does with the registry right now.

I think this would allow for easier debugging of certain interface problems and would help to make Pencil2D's editor configuration and preferences more accessible to the advanced user, while also making it portable in case they move from one computer to another. Last but not least this could open a way for advanced users and to hack their way into Pencil2D when things don't seem work with those values.

Ideally this should have an interface in the future, but for now a simple read & write file should help a lot. Let me know what you think :slightly_smiling_face: 

Registry KEY
![image](https://user-images.githubusercontent.com/4912907/40516581-d7bad366-5f76-11e8-8a0b-19ff60040562.png)

Registry Values
![image](https://user-images.githubusercontent.com/4912907/40516593-e7c96722-5f76-11e8-91a3-e202e85fdd0a.png)

**Comment by chchwy** [comment]
Firstly, It's Qt's default behaviour:
http://doc.qt.io/qt-5/qsettings.html
QSettings stores values in registry on Windows, plist on mac and ini on Linux.

These settings are Intentionally hidden. Usually, Pencil2D doesn't check the setting values before using it because Pencil2D knows the values are written by itself. So it's a question to expose it to users.

For the portability, we can make a setting import/export features.

**Comment by J5lx** [comment]
I really don’t the see a point in doing this. Exporting/importing settings can of course be helpful, but instead of changing the internal workings of the program just to enable a *workaround* for missing functionality, we should instead implement it as a proper feature IMO. I also don’t think “accessibility to advanced users” is a valid concern here – if you’re advanced enough to launch Windows Explorer to find a configuration file holed up in a structure of hidden directories and edit the sometimes cryptic options in it using Notepad, you’re also advanced enough to launch the Registry Editor, find the right keys and edit the same sometimes cryptic options there. Wikipedia even [explains](https://en.wikipedia.org/wiki/Windows_Registry#Keys_and_values) the registry using the file system as a one-on-one analogy:

> Registry keys are container objects similar to folders. Registry values are non-container objects similar to files. Keys may contain values and subkeys. Keys are referenced with a syntax similar to Windows' path names, using backslashes to indicate levels of hierarchy.

I also don’t see enough “hidden options” in Pencil to warrant some about:config-like interface, like you seem to be suggesting, TBH. If it’s somehow to related to those “implicit” options like window geometry and such, I’d much rather spend my time making sure that manually fixing those options isn’t necessary in the first place.

Also, while I’m already talking about implementation: It’s not like we can just switch over our backend to use text files and be done with it, we also need to implement a migration from registry to those text files and maintain it for a some amount of time (unless we want to risk annoying our users). IMO it’s just not worth the effort.

**Comment by Jose-Moreno** [comment]
@chchwy @J5lx Fair points, thank you both! I'd like to hear the others input as well, but I'm already taking the hint that this is probably a futile endeavor a.k.a not worth it mainly due to the reasons Jakob mentioned. 

I do think however that at least exposing some of those variables so the user can modify them. Which variables? that remains to be seen of course, might be one or ten. I'd have to review which ones are really worth exposing, or else suggest functionality based on those which then would be seen as missing.

**Comment by CandyFace** [comment]
I agree with @J5lx and @chchwy 

If something should be exposed, then we should find a way to do it from the application, we should avoid modifying registries.

**Comment by scribblemaniac** [comment]
I agree with @J5lx, @chchwy, and @CandyFace. Import/export settings might be useful, but the last thing I want is for the internal settings to be easily manipulated by the user. Errors in the configuration could cause persistent issues with Pencil2d that would be very difficult to debug and very easy to cause. Exposing the settings through the Pencil2d application would be the way to go if they have to be shown, since we can then have control over the type, range, etc. of the settings.

If there are some advanced users looking to "hack their way into Pencil2d", I hear there's some code repository thing available online where they can change any part of the program, and the are even looking for people to help fix things. I can't remember where it is off the top of my head though... 😉

**Comment by Jose-Moreno** [comment]
@chchwy @CandyFace @J5lx @scribblemaniac Ok got it. I feel some of the cheekiness was unnecessary though, but all the comments were fair, so point taken. When I went for the "hack" comment I was thinking of laying a groundwork for how other software actually have macros or scripting languages so the advanced users exactly don't have to mess with the source code to solve some low level issues (like when windows used to disappear and you had to delete the registry key to bring them back), but I digress. 

I'm going to close this as it seems to be unanimous that it's a bad idea to let the non-technical users to be able to handle that information, but with all due respect (and in most "cheeky" fashion so i'm hopefully not misunderstood in my intention :wink: ) the idea of the user being in control of the program as it's often chanted in FOSS projects doesn't necessarily mean that most of them can actually control it, so it's annoying from a user point of view that If you want something to be fixed you are said "there's the source code, go fix it yourself",  that's why from within the development side we should aim to provide them users with enough tools to make their experience most comfortable. 

Either way thanks for weighing into this everyone, it's all good then let's move on from this concept to something more sensible :slightly_smiling_face:

**Comment by scribblemaniac** [comment]
@Jose-Moreno Sorry if I took my cheekiness too far. It was never my intent to insult you or your idea. Your suggestion was valuable to start a discussion on this possibility and document the direction we want to go in with concerns to this.

I wouldn't mind seeing a macro or plugin system, I just hope that by the time we get something like that done, there rest of the program will be so stable and functional that there won't be any need to use it for hack-y workaround like you describe 😁
