### ISSUE TITLE
My files won't save properly. I exported all of the newer frameworks to a file with each frame so I have them, but what do I do so it saves?

### ISSUE THREAD

**Issue by KinBunAnimations** [pencil2d/pencil#988]
FileManager::save
strFileName = C:/Users/Shara Crowley/Desktop/APUSH Presentation.pclx
strTempWorkingFolder = C:/Users/Shara Crowley/AppData/Local/Temp/Pencil2D/APUSH Presentation.Y2xD/
layerCount = 4
layer[0] = Layer[id=1, name=Camera Layer, type=5]
layer[1] = Layer[id=2, name=Vector Layer, type=2]
layer[2] = Layer[id=3, name=Bitmap Layer, type=1]
layer[3] = Layer[id=4, name=Bitmap Layer, type=1]

Error Display
Title: Internal Error
Description: An internal error occurred. Your file may not be saved successfully.

System Info
Pencil version: 0.6.1.1
Build ABI: x86_64-little_endian-llp64
Kernel: winnt 10.0.17134
Product name: Windows 10 (10.0)

**Comment by Jose-Moreno** [comment]
@KinBunAnimations It seems a newer windows update broke how Pencil2D performed their save operation. this problem is already being investigated and fixed and once there is a development build ready to test that a proper solution has been found I'll gladly post it here. 

For now I'm afraid there is not an easy workaround other than to export the drawings as IMAGE SEQUENCE (PNG) with transparency enabled to preserve your drawings, and then you'd have to re-import them into a new file to keep working, otherwise you'd lose your work completely. Note that if you have several layers you would have to export an image sequence per layer, and you would re-import them in the same way, one layer at a time.

**Comment by KinBunAnimations** [comment]
Okay, Ill use another program until the issue gets fixed.

**Windows 10 Breaks Pencil 2D**

**Comment by Jose-Moreno** [comment]
@KinBunAnimations Sure. Just a small clarification. Please note that it is my personal opinion that Windows 10 update is the culprit as everyone that have reported this problem is using Windows 10, but from a technical standpoint it may be something else and as I mentioned the developers are looking for a fix right now. Once it is fixed i'll tag your username here in case you're still interested.

If you want to try and use other software either free or commercial, we have a convenient list in our blog for those cases, we hope it's useful in your search for a proper animation software: http://pencil2d-software.tumblr.com/post/145767476221/when-youve-worked-all-day-on-your-animation

**Comment by chchwy** [comment]
Hi @KinBunAnimations 
Could you please try the latest nightly build?
https://www.pencil2d.org/download/#nightlybuild

 We put some fixes in the 5 June version but not sure it matches your case.

**Comment by Jose-Moreno** [comment]
@KinBunAnimations Hi, there's been a new fix implemented for the save file bug, if you can please test it and if the problem has been solved for you please let us know and close this issue:

Download the nightly build for July 3rd 2018 here:
https://www.pencil2d.org/download/#nightlybuild

**Comment by KinBunAnimations** [comment]
Hey! Sorry, Ill look into it now. I had to reset my computer because I
caught a bug and had to remove a lot of my apps. I'll look at the update
now and let you know!
KinBun Animations

**Comment by Jose-Moreno** [comment]
@KinBunAnimations Hey. It's been a while, we never got word from you back then, but well that's fine. Just wanted to let you know that we have a new Pencil2D version available that can try to test if you still have trouble saving or not. 

We doubt you will have issues like before since the version you originally used was very unstable compared to the latest one so I'm going to close this issue, however if you have the same problem again, please comment here so we can reopen it and keep track of it.
